---
permalink: online-help/concept-cluster-components-and-why-they-can-be-in-contention.html 
sidebar: sidebar 
keywords:  
summary: 當叢集元件發生爭用時、您可以識別叢集效能問題。使用該元件的Volume工作負載效能變慢、而用戶端要求的回應時間（延遲）也會增加、這會在Unified Manager中觸發事件。 
---
= 叢集元件及其爭用的原因
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當叢集元件發生爭用時、您可以識別叢集效能問題。使用該元件的Volume工作負載效能變慢、用戶端要求的回應時間（延遲）也會增加、這會在Unified Manager中觸發事件。

發生爭用的元件無法在最佳層級執行。效能下降、其他叢集元件和工作負載（稱為_als受害者_）的效能可能會增加延遲。若要避免元件爭用、您必須減少其工作負載或提高其處理更多工作的能力、才能使效能恢復正常水準。由於Unified Manager會在五分鐘的時間間隔內收集和分析工作負載效能、因此只有在叢集元件持續過度使用時、Unified Manager才會偵測。在五分鐘間隔內、僅持續一段短時間的暫時性過度使用尖峰不會被偵測到。

例如、儲存Aggregate可能會因其上的一或多個工作負載競相執行其I/O要求而發生爭用。集合體上的其他工作負載可能會受到影響、導致效能降低。若要減少Aggregate上的活動量、您可以採取不同步驟、例如將一或多個工作負載移至較不忙碌的Aggregate、以減少目前Aggregate的整體工作負載需求。對於QoS原則群組、您可以調整處理量限制、或將工作負載移至不同的原則群組、使工作負載不再受到節流。

Unified Manager會監控下列叢集元件、在發生爭用時發出警示：

* *網路*
+
代表iSCSI傳輸協定或叢集光纖通道（FC）傳輸協定所發出的I/O要求等待時間。等待時間是指在叢集回應I/O要求之前、等待iSCSI Ready to Transfer（R2T）或FCP Transfer Ready（XFER_RDY）交易完成所花費的時間。如果網路元件發生爭用、表示區塊傳輸協定層的等待時間過長、會影響一或多個工作負載的延遲。

* *網路處理*
+
代表叢集內與傳輸協定層和叢集之間I/O處理相關的軟體元件。在偵測到事件之後、處理網路處理的節點可能已經變更。如果網路處理元件發生爭用、表示網路處理節點的高使用率會影響一或多個工作負載的延遲。

* * QoS原則*
+
代表工作負載所屬的儲存服務品質（QoS）原則群組。如果原則群組元件發生爭用、表示原則群組中的所有工作負載都會受到設定的處理量限制所限制、這會影響其中一或多個工作負載的延遲。

* *叢集互連*
+
代表叢集節點實體連接的纜線和介面卡。如果叢集互連元件發生爭用、表示叢集互連的I/O要求等待時間過長、會影響一或多個工作負載的延遲。

* *資料處理*
+
代表叢集內與叢集與包含工作負載的儲存Aggregate之間I/O處理相關的軟體元件。自偵測到事件後、處理資料的節點可能已變更。如果資料處理元件發生爭用、表示資料處理節點的高使用率會影響一或多個工作負載的延遲。

* *《資源*》MetroCluster
+
代表MetroCluster 用MetroCluster 作鏡射資料的各種資源、包括NVRAM和交換器間連結（ISL）、這些資源用於鏡射整個叢集之間的資料。如果存在爭奪、表示來自本機叢集上工作負載的高寫入處理量、或是連結健全狀況問題會影響本機叢集上一或多個工作負載的延遲。MetroCluster如果叢集並非MetroCluster 採用E32組態、則不會顯示此圖示。

* * Aggregate或SSD Aggregate Ops *
+
代表工作負載執行所在的儲存Aggregate。如果Aggregate元件發生爭用、表示Aggregate上的高使用率會影響一或多個工作負載的延遲。集合體由所有HDD組成、或混合使用HDD和SSD（Flash Pool Aggregate）。「SSD Aggregate」（「SD Aggregate」）包含所有SSD（All Flash Aggregate）、或是混合使用SSD和雲端層（FabricPool a Sd Aggregate）。

* *雲端延遲*
+
代表叢集內與叢集與雲端層之間I/O處理相關的軟體元件、以儲存使用者資料。如果雲端延遲元件發生爭用、表示來自雲端層上裝載磁碟區的大量讀取內容、會影響一或多個工作負載的延遲。

* *同步SnapMirror *
+
代表叢集中的軟體元件、該元件會以SnapMirror同步關係、將使用者資料從主要磁碟區複寫到次要磁碟區。如果同步SnapMirror元件發生爭用、表示SnapMirror同步作業的活動會影響一或多個工作負載的延遲。


