---
permalink: online-help/concept-how-annotation-rules-work-in-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: 附註規則是您定義的標準、可用來為儲存物件（Volume、叢集或儲存虛擬機器）加上附註。您可以使用條件群組或條件來定義註釋規則。 
---
= 註釋規則在Unified Manager中的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
註釋規則是您定義的準則、用來註釋儲存物件（Volume、叢集或儲存虛擬機器（SVM））。您可以使用條件群組或條件來定義註釋規則。

* 您必須將註釋規則與註釋建立關聯。
* 您必須為附註規則建立物件類型的關聯、註釋規則只能建立一個物件類型的關聯。
* Unified Manager會在每個監控週期之後、或在建立、編輯、刪除或重新排序規則時、從儲存物件新增或移除註釋。
* 註釋規則可以有一個或多個條件群組、而且每個條件群組可以有一個或多個條件。
* 儲存物件可以有多個附註。特定附註的附註規則也可以在規則條件中使用不同的附註、將另一個附註新增至已附註的物件。




== 條件

您可以建立多個條件群組、而且每個條件群組可以有一或多個條件。您可以在註釋的註釋規則中套用所有已定義的條件群組、以便為儲存物件加上註釋。

條件群組中的條件會使用邏輯AND執行。必須符合條件群組中的所有條件。當您建立或修改註釋規則時、會建立一個條件、以套用、選取及註釋僅符合條件群組中所有條件的儲存物件。當您想要縮小要註釋的儲存物件範圍時、可以在條件群組中使用多個條件。

您可以使用下列運算元和運算子、並指定所需的值、以建立儲存物件的條件。

|===
| 儲存物件類型 | 適用的操作數 


 a| 
Volume
 a| 
* 物件名稱
* 擁有叢集名稱
* 擁有SVM名稱
* 註釋




 a| 
SVM
 a| 
* 物件名稱
* 擁有叢集名稱
* 註釋




 a| 
叢集
 a| 
* 物件名稱
* 註釋


|===
當您選取註釋作為任何儲存物件的運算元時、可使用「is」運算子。對於所有其他操作數、您可以選擇「is」或「contains'」作為運算子。當您選取「is」運算子時、系統會評估條件、使其與所選運算元所提供的值完全相符。當您選取「包含」運算子時、系統會評估條件以符合下列其中一項條件：

* 運算元值與所選運算元的值完全相符。
* 運算元值包含所選運算元所提供的值。




== 附有條件的附註規則範例

請針對具有下列兩種情況的Volume、考慮具有單一條件群組的註釋規則：

* 名稱包含「'vol'」
* SVM名稱為「data_SVM」


此註釋規則會在名稱中註釋所有包含「'vol'」的磁碟區、並在SVM上以名稱「'data_Svm'」加上所選註釋和註釋類型。



== 條件群組

條件群組是使用邏輯OR執行、然後套用至儲存物件。儲存物件必須符合其中一個條件群組的要求才能加上註解。符合所有條件群組條件的儲存物件會加上註釋。您可以使用條件群組來增加要註解的儲存物件範圍。



== 具有條件群組的註釋規則範例

請針對一個Volume考慮具有兩個條件群組的註釋規則、每個群組包含下列兩個條件：

* 條件群組1
+
** 名稱包含「'vol'」
** SVM名稱為「data_SVM」。此條件群組會在名稱中註釋所有包含「vol'」的磁碟區、並在SVM上以「data_SVM」的名稱來裝載這些磁碟區。


* 條件群組2.
+
** 名稱包含「'vol'」
** 資料優先順序的註釋值為「critical」（關鍵）。此條件群組會在名稱中註釋所有包含「vol'」的磁碟區、並以「'critical」（關鍵）註釋資料優先順序註釋值。




將包含這兩個條件群組的附註規則套用至儲存物件時、會註釋下列儲存物件：

* 所有名稱中包含「'vol'」的磁碟區、以及在SVM上裝載的名稱為「'data_Svm'」的磁碟區。
* 所有名稱中包含「'vol'」的磁碟區、並以「'critical（關鍵）」的資料優先註釋值加以註釋。

