---
permalink: online-help/concept-how-group-rules-work-for-groups.html 
sidebar: sidebar 
keywords:  
summary: 群組規則是您定義的準則、可讓儲存物件（磁碟區、叢集或SVMs）納入特定群組。您可以使用條件群組或條件來定義群組規則。 
---
= 群組規則如何適用於群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
群組規則是您定義的準則、可讓儲存物件（磁碟區、叢集或SVM）納入特定群組。您可以使用條件群組或條件來定義群組規則。

* 您必須將群組規則與群組建立關聯。
* 您必須為群組規則建立物件類型的關聯；群組規則只會建立一個物件類型的關聯。
* 儲存物件會在每個監控週期之後、或在建立、編輯或刪除規則時、從群組中新增或移除。
* 群組規則可以有一個或多個條件群組、而且每個條件群組可以有一個或多個條件。
* 儲存物件可以根據您建立的群組規則屬於多個群組。




== 條件

您可以建立多個條件群組、而且每個條件群組可以有一或多個條件。您可以將群組規則中所有已定義的條件群組套用至群組、以指定群組中包含哪些儲存物件。

條件群組中的條件會使用邏輯AND執行。必須符合條件群組中的所有條件。當您建立或修改群組規則時、系統會建立條件、以套用、選取及群組符合條件群組中所有條件的儲存物件。當您想要縮小要納入群組的儲存物件範圍時、可以在條件群組中使用多個條件。

您可以使用下列運算元和運算子、並指定所需的值、以建立儲存物件的條件。

|===
| 儲存物件類型 | 適用的操作數 


 a| 
Volume
 a| 
* 物件名稱
* 擁有叢集名稱
* 擁有SVM名稱
* 註釋




 a| 
SVM
 a| 
* 物件名稱
* 擁有叢集名稱
* 註釋




 a| 
叢集
 a| 
* 物件名稱
* 註釋


|===
當您選取註釋作為任何儲存物件的運算元時、可使用「is」運算子。對於所有其他操作數、您可以選擇「is」或「contains'」作為運算子。

* 運算元
+
Unified Manager中的操作數清單會根據選取的物件類型而變更。清單包括您在Unified Manager中定義的物件名稱、擁有叢集名稱、擁有SVM名稱及註釋。

* 營運者
+
運算子清單會根據某個條件所選的運算元而變更。Unified Manager支援的營運者包括「is」和「contained」。

+
當您選取「is」運算子時、系統會評估條件、使其與所選運算元的值完全相符。

+
當您選取「包含」運算子時、系統會評估條件以符合下列其中一項條件：

+
** 運算元值與所選運算元所提供的值完全相符
** 運算元值包含所選運算元所提供的值


* 價值
+
「值」欄位會根據選取的運算元而變更。





== 具有條件的群組規則範例

請針對具有下列兩種情況的磁碟區、考慮條件群組：

* 名稱包含「'vol'」
* SVM名稱為「data_SVM」


此條件群組會選取名稱中包含「'vol'」的所有磁碟區、以及名稱為「data_SVM」的SVM。



== 條件群組

條件群組是使用邏輯OR執行、然後套用至儲存物件。儲存物件必須符合要納入群組的其中一個條件群組。所有條件群組的儲存物件都會合併在一起。您可以使用條件群組來增加要納入群組的儲存物件範圍。



== 具有條件群組的群組規則範例

請針對一個磁碟區考慮兩個條件群組、每個群組包含下列兩個條件：

* 條件群組1
+
** 名稱包含「'vol'」
** SVM名稱為「data_SVM」、條件群組1會選取名稱中包含「vol'」的所有磁碟區、並以「data_SVM」的名稱裝載在SVM上。


* 條件群組2.
+
** 名稱包含「'vol'」
** 資料優先順序的註釋值為「關鍵」條件群組2、會選取名稱中包含「vol'」的所有磁碟區、並以「關鍵」的資料優先順序註釋值來註解。




將包含這兩個條件群組的群組規則套用至儲存物件時、下列儲存物件會新增至選取的群組：

* 所有名稱中包含「'vol'」的磁碟區、以及在SVM上以「data_SVM」名稱代管的磁碟區。
* 所有名稱中包含「'vol'」的磁碟區、並以資料優先順序註釋值「'critici'」註釋。

