---
permalink: online-help/concept-types-of-snapmirror-protection.html 
sidebar: sidebar 
keywords:  
summary: 根據資料儲存拓撲的部署、Unified Manager可讓您設定多種類型的SnapMirror保護關係。SnapMirror保護的所有變體都提供容錯移轉災難恢復保護、但在效能、版本靈活度及多重備份複本保護方面、都有不同的功能。 
---
= SnapMirror保護類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根據資料儲存拓撲的部署、Unified Manager可讓您設定多種類型的SnapMirror保護關係。SnapMirror保護的所有變體都提供容錯移轉災難恢復保護、但在效能、版本靈活度及多重備份複本保護方面、都有不同的功能。



== 傳統SnapMirror非同步保護關係

傳統SnapMirror非同步保護可在來源與目的地磁碟區之間提供區塊複寫鏡射保護。

在傳統的SnapMirror關係中、鏡射作業的執行速度比其他SnapMirror關係快、因為鏡射作業是以區塊複寫為基礎。然而、傳統的SnapMirror保護要求目的地Volume必須在ONTAP 相同主要版本（例如8.x到8.x、9.x到9.x或9.x到9.x版）的相同或更新次要版本的作業系統下執行、作為來源Volume。



== SnapMirror非同步保護、具備版本彈性的複寫功能

SnapMirror採用版本彈性複寫的非同步保護功能、可在來源與目的地磁碟區之間提供邏輯複寫鏡射保護、即使這些磁碟區是在ONTAP 不同版本的E8.3或更新版本軟體（例如8.3到8.3、8.3到9.1或9.0到8.3）下執行。

在SnapMirror與版本彈性複寫的關係中、鏡射作業的執行速度並不像傳統SnapMirror關係那樣快。

由於執行速度較慢、採用版本彈性複寫保護的SnapMirror不適合在下列任一情況中實作：

* 來源物件包含超過1000萬個要保護的檔案。
* 受保護資料的恢復點目標為兩小時或更短。（也就是目的地必須永遠包含鏡射的可恢復資料、且資料的時間不得超過來源資料的兩小時。）


在上述任一情況下、都需要以區塊複寫方式更快執行預設的SnapMirror保護。



== SnapMirror非同步保護、具備版本彈性的複寫與備份選項

SnapMirror非同步保護搭配版本彈性的複寫與備份選項、可在來源與目的地磁碟區之間提供鏡射保護、並可在目的地儲存多個鏡射資料複本。

儲存管理員可以指定從來源到目的地鏡射哪些Snapshot複本、也可以指定在目的地保留這些複本的時間長度、即使這些複本是從來源處刪除。

在SnapMirror與版本彈性複寫與備份選項的關係中、鏡射作業的執行速度並不像傳統SnapMirror關係那樣快。



== SnapMirror同步保護、並具有嚴格的同步功能

SnapMirror同步保護搭配「嚴格」同步、可確保主要和次要磁碟區永遠是彼此的真實複本。如果嘗試將資料寫入次要磁碟區時發生複寫失敗、則用戶端I/O會中斷至主要磁碟區。



== SnapMirror同步保護與一般同步

SnapMirror同步保護搭配「鏡面」同步、並不需要主磁碟區和次磁碟區一律是彼此的真實複本、因此可確保主磁碟區的可用度。如果在嘗試將資料寫入次要Volume時發生複寫失敗、則主要和次要磁碟區會不同步、而用戶端I/O會繼續寫入主要磁碟區。

[NOTE]
====
從「健全狀況/磁碟區」目錄頁面或「健全狀況/磁碟區詳細資料」頁面監控同步保護關係時、無法使用「還原」按鈕和「關係」操作按鈕。

====