---
permalink: online-help/concept-understanding-counter-charts.html 
sidebar: sidebar 
keywords:  
summary: 「計數器圖表」窗格中的圖表可讓您檢視及比較根物件和從關聯物件網格新增之物件的效能資料。這有助於您瞭解效能趨勢、並找出及解決效能問題。 
---
= 瞭解計數器圖表
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「計數器圖表」窗格中的圖表可讓您檢視及比較根物件和從關聯物件網格新增之物件的效能資料。這有助於您瞭解效能趨勢、並找出及解決效能問題。

預設顯示的計數器圖表為「事件」、「延遲」、「IOPS」和「Mbps」。您可以選擇顯示的選用圖表包括使用率、使用的效能容量、可用的IOPS、IOPS/TB及快取遺失比率。此外、您也可以選擇檢視延遲、IOPS、Mbps和效能使用容量圖表的總值或明細值。

Performance Explorer預設會顯示特定的計數器圖表、無論儲存物件是否支援全部計數器。不支援計數器時、計數器圖表會顯示空白訊息 `Not applicable for <object>` 即會顯示。

這些圖表會顯示根物件和您在比較窗格中選取之所有物件的效能趨勢。每個圖表中的資料排列如下：

* * X軸*
+
顯示指定的時段。如果您尚未指定時間範圍、預設值為前72小時。

* * Y軸*
+
顯示所選物件或物件的專屬計數器單位。



趨勢線色彩符合比較窗格中顯示的物件名稱色彩。您可以將游標放在任何趨勢線上的某個點上、以檢視該點的時間和值詳細資料。

如果您想要在圖表中調查特定時間段、可以使用下列其中一種方法：

* 使用「*」按鈕展開「計數器圖表」窗格以跨越頁面寬度。
* 使用游標（當游標轉換成放大鏡時）、在圖表中選取時間範圍的一部分、以對焦並放大該區域。您可以按一下「重設圖表縮放」、將圖表恢復為預設時間範圍。
* 使用「*縮放檢視*」按鈕可顯示包含擴充詳細資料和臨界值指標的大型單一計數器圖表。


[NOTE]
====
偶爾會顯示趨勢線的落差。落差表示Unified Manager無法從儲存系統收集效能資料、或Unified Manager可能已經關閉。

====