---
permalink: online-help/concept-how-storage-qos-can-control-workload-throughput.html 
sidebar: sidebar 
keywords:  
summary: 您可以建立或編輯服務品質（QoS）原則群組、以控制其所包含工作負載的每秒I/O（IOPS）或處理量（Mbps）限制。如果工作負載位於沒有設定限制的原則群組中（例如預設原則群組）、或設定的限制不符合您的需求、您可以增加限制、或將工作負載移至具有所需限制的新原則群組或現有原則群組。 
---
= 儲存QoS如何控制工作負載處理量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立或編輯服務品質（QoS）原則群組、以控制其所含工作負載的每秒I/O（IOPS）或處理量（Mbps）限制。如果工作負載位於沒有設定限制的原則群組中（例如預設原則群組）、或設定的限制不符合您的需求、您可以增加限制、或將工作負載移至具有所需限制的新原則群組或現有原則群組。

「標準」QoS原則群組可指派給個別工作負載、例如單一磁碟區或LUN。在此情況下、工作負載可以使用完整的處理量限制。QoS原則群組也可以指派給多個工作負載、在此情況下、處理量限制會在工作負載之間共用。例如、指派給三個工作負載的QoS限制為9、000 IOPS、會將合併的IOPS限制在超過9、000 IOPS。

也可將「Adaptive」QoS原則群組指派給個別工作負載或多個工作負載。然而、即使指派給多個工作負載、每個工作負載仍會獲得完整的處理量限制、而非與其他工作負載共享處理量值。此外、調適性QoS原則會根據每個工作負載的磁碟區大小、自動調整處理量設定、因此隨著磁碟區大小變更、IOPS與TB的比率也會維持不變。例如、如果調適性QoS原則中的尖峰設定為5、000 IOPS/TB、則10 TB磁碟區的處理量上限為50、000 IOPS。如果磁碟區稍後調整至20 TB、調適性QoS會將上限調整為100、000 IOPS。

從推出《S25 9.5版」開始ONTAP 、您可以在定義可調適的QoS原則時納入區塊大小。如此可有效地將原則從IOPS/TB臨界值轉換成Mbps臨界值、適用於工作負載使用非常大的區塊大小、最終使用大量處理量的情況。

對於共享群組QoS原則、當原則群組中所有工作負載的IOPS或Mbps超過設定限制時、原則群組會節流工作負載以限制其活動、進而降低原則群組中所有工作負載的效能。如果動態效能事件是由原則群組節流所產生、則事件說明會顯示相關原則群組的名稱。

在「效能/磁碟區」目錄頁面中、您可以依IOPS和Mbps來排序受影響的磁碟區、以查看哪些工作負載的使用率可能是事件的最大原因。在「Performance / Volumes Explorer（效能/磁碟區資源管理器）」頁面中、您可以選取其他磁碟區或LUN來比較受影響的工作負載IOPS或Mbps處理量使用量。

原則群組會將過度使用節點資源的工作負載指派給較嚴格的原則群組設定、藉此節流工作負載以限制其活動、進而減少該節點上的資源使用量。不過、如果您希望工作負載能夠使用更多節點資源、可以增加原則群組的值。

您可以使用System Manager或ONTAP 列舉一些指令來管理原則群組、包括下列工作：

* 建立原則群組
* 新增或移除原則群組中的工作負載
* 在原則群組之間移動工作負載
* 變更原則群組的處理量限制
* 將工作負載移至不同的Aggregate和/或節點

