---
permalink: online-help/concept-what-happens-to-performance-threshold-policies-when-an-object-is-moved-opm.html 
sidebar: sidebar 
keywords:  
summary: 因為效能臨界值原則會指派給儲存物件、所以如果您移動物件、所有指派的臨界值原則都會在移動完成後附加到物件上。例如、如果您將磁碟區或LUN移至不同的Aggregate、則新Aggregate上的磁碟區或LUN的臨界值原則仍會處於作用中狀態。 
---
= 物件搬移時、效能臨界值原則會發生什麼變化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
因為效能臨界值原則會指派給儲存物件、所以如果您移動物件、所有指派的臨界值原則都會在移動完成後附加到物件上。例如、如果您將磁碟區或LUN移至不同的Aggregate、則新Aggregate上的磁碟區或LUN的臨界值原則仍會處於作用中狀態。

如果臨界值原則（組合原則）存在次要計數器條件（例如、如果將其他條件指派給Aggregate或節點）、則次要計數器條件會套用至新的Aggregate或節點、而該新的Aggregate或節點已移至該磁碟區或LUN。

如果使用變更臨界值原則的物件存在任何新的作用中事件、則這些事件會標示為已過時、而且臨界值原則會開始將計數器監控為新定義的臨界值原則。

Volume Move作業會導致ONTAP 功能不全地傳送資訊變更事件。「效能總管」頁面的「事件」時間軸和「效能/ Volume詳細資料」頁面上會出現變更事件圖示、指出完成移動作業的時間。

[NOTE]
====
如果您將物件移至不同的叢集、則會從物件移除使用者定義的臨界值原則。必要時、您必須在移動作業完成後、將臨界值原則指派給物件。不過、動態和系統定義的臨界值原則會在物件移至新叢集後自動套用至物件。

====


== HA接管和恢復期間的臨界值原則功能

在高可用度（HA）組態中執行接管或恢復作業時、從一個節點移至另一個節點的物件、會以手動移動作業的相同方式保留其臨界值原則。由於Unified Manager每15分鐘檢查一次叢集組態變更、因此在下次輪詢叢集組態之前、不會識別切換到新節點的影響。

[NOTE]
====
如果接管和恢復作業都發生在15分鐘的組態變更收集期間內、您可能看不到效能統計資料從一個節點移至另一個節點。

====


== 集合體重新配置期間的臨界值原則功能

如果您使用將Aggregate從一個節點移至另一個節點 `aggregate relocation start` 命令會同時保留所有物件的單一和組合臨界值原則、而且臨界值原則的節點部分會套用至新節點。



== 切換時的臨界值原則功能MetroCluster

從一個叢集移至MetroCluster 另一個叢集的物件、若為使用者定義的臨界值原則設定、則不會保留這些物件。如果需要、您可以在移至合作夥伴叢集的磁碟區和LUN上套用臨界值原則。物件移回原始叢集後、使用者定義的臨界值原則會自動重新套用。

xref:concept-volume-behavior-during-switchover-and-switchback.adoc[切換和切換期間的Volume行為]
