---
permalink: online-help/reference-cluster-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: 「儲存摘要」報告可讓您檢視HA配對中儲存容量的摘要資訊。此資訊可協助您瞭解可能的容量風險、並採取適當行動來重新平衡工作負載。報告中看不到單節點叢集資訊。 
---
= 儲存摘要報告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「儲存摘要」報告可讓您檢視HA配對中儲存容量的摘要資訊。此資訊可協助您瞭解可能的容量風險、並採取適當行動來重新平衡工作負載。報告中看不到單節點叢集資訊。



== 儲存摘要報告圖表檢視

「儲存摘要」報告會以兩種格式顯示：

* 儲存摘要報告圖表檢視
* 儲存摘要報告表格檢視


此圖表顯示一段時間內、集合體已使用和未使用資料容量的容量趨勢。總資料容量會顯示在垂直（y）軸上、而叢集名稱則顯示在水平（x）軸上。因此、圖表中的每個長條代表一個叢集。您可以將游標定位在特定點上、以檢視圖表上特定點的詳細資料。

* *叢集名稱*
+
顯示叢集名稱。

* * HA配對*
+
顯示透過形成兩個節點所獲得的HA配對值。

* *模型*
+
顯示模型名稱。

* *作業系統版本*
+
顯示ONTAP 使用的版本。

* *總原始容量*
+
顯示陣列中所有磁碟的實體容量總計。

* *未設定原始容量*
+
顯示容器類型不是Aggregate、中斷、備用或共享的磁碟未設定容量。此容量一律高於ONTAP 支援的實體磁碟容量。例如、考慮使用2 TB磁碟。磁碟的實體容量ONTAP 為1.6 TB、而Unified Manager中未設定的原始容量則為1.8 TB。

* * Aggregate總容量*
+
顯示使用者可用集合體的總大小。這包括Snapshot複本保留。

* * Aggregate已用容量*
+
顯示已在Aggregate上使用的容量。這包括磁碟區、LUN及其他儲存效率技術經常成本所消耗的容量。

* *彙總未使用的容量*
+
顯示可用於在集合體上儲存其他資料的容量。這包括Snapshot複本保留。

* *已分配LUN容量*
+
顯示對應的LUN容量。

* *未分配LUN容量*
+
顯示所有未對應至主機的LUN容量。

* * Volume總容量*
+
顯示磁碟區的總容量（已使用加上未使用）。

* * Volume已用容量*
+
顯示磁碟區的已用容量。

* * Volume未使用的容量*
+
顯示磁碟區未使用的容量。

* * Volume Protection Capacity *
+
顯示已SnapVault 啟用SnapMirror和功能不實的磁碟區容量。

* *叢集授權雲端層總計*
+
顯示已在雲端層授權的總容量。此欄位會顯示給需要FabricPool 使用支援功能的儲存供應商、例如Amazon S3、IBM Cloud Object Storage、Microsoft Azure Cloud或Alibaba Cloud Object Storage。

* *已使用叢集授權的雲端層*
+
顯示雲端層中的資料所使用的空間、以供需要FabricPool 使用支援功能的儲存供應商使用。

* *使用叢集StorageGRID 功能*
+
顯示雲端層中的資料所使用的空間、以供不需要FabricPool 使用支援功能的儲存供應商使用、例如StorageGRID 、


