---
permalink: online-help/reference-create-schedule-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 「建立排程」對話方塊可讓您針對SnapMirror和SnapVault 關聯性傳輸建立基本或進階的保護排程。您可以建立新的排程、以增加頻繁更新資料所造成的資料傳輸頻率、或是在資料不常變更時建立較不常用的排程。 
---
= 建立排程對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「建立排程」對話方塊可讓您針對SnapMirror和SnapVault 關聯性傳輸建立基本或進階的保護排程。您可以建立新的排程、以增加頻繁更新資料所造成的資料傳輸頻率、或是在資料不常變更時建立較不常用的排程。

無法設定SnapMirror同步關係的排程。

* *目的地叢集*
+
您在SnapVault 「組態保護」對話方塊的「還原」索引標籤或「SnapMirror」索引標籤中選取的叢集名稱。

* *排程名稱*
+
您為排程提供的名稱。排程名稱可以包含A到Z、a到z、0到9等字元、以及下列任何特殊字元：！@#$%｛caret｝&*（）_-。排程名稱不得包含下列字元：<>。

* *基本或進階*
+
您要使用的排程模式。

+
基本模式包括下列元素：

+
** 重複
+
排程傳輸的發生頻率。選項包括每小時、每天和每週。

** 天
+
如果選取每週重複、則會在每週的某一天進行轉帳。

** 時間
+
選取「每日」或「每週」時、即會發生傳輸的時間。



+
進階模式包括下列元素：

+
** 數月
+
以逗號分隔的數字清單、代表一年中的月份。有效值為0到11、零代表一月、依此類推。此元素為選用項目。將此欄位留白表示每個月都會進行轉帳。

** 天
+
以逗號分隔的數字清單、代表每月的日期。有效值為1到31。此元素為選用項目。將此欄位留白表示每月的每一天都會進行轉帳。

** 工作日
+
以逗號分隔的數字清單、代表一週中的天數。有效值為0到6、0代表星期日、依此類推。此元素為選用項目。將欄位留白表示每週的每一天都會進行轉帳。如果指定的是一週中的某一天、但未指定該月的某一天、則只會在該週的指定日期進行轉帳、而非每天。

** 時數
+
以逗號分隔的數字清單、代表一天中的小時數。有效值為0到23、0代表午夜。此元素為選用項目。

** 分鐘
+
以逗號分隔的數字清單、代表一小時內的分鐘數。有效值為0至59。此元素為必填項目。




