---
permalink: online-help/reference-edit-alert-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以編輯警示內容、例如警示所關聯的資源、事件、指令碼和通知選項。 
---
= 編輯警示對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以編輯警示內容、例如警示所關聯的資源、事件、指令碼和通知選項。



== 名稱

此區域可讓您編輯警示的名稱和說明。

* *警示名稱*
+
可讓您編輯警示名稱。

* *警示說明*
+
可讓您指定警示的說明。

* *警示狀態*
+
可讓您啟用或停用警示。





== 資源

此區域可讓您根據您要觸發警示的動態規則、選取個別資源或群組資源。您可以從下拉式清單中選取資源類型來搜尋資源、也可以指定確切的資源名稱來顯示特定資源。

* *包括*
+
可讓您加入要觸發警示的資源。您可以指定文字字串來群組符合字串的資源、然後選取要納入警示的群組。例如、您可以將名稱包含「'vol0'」字串的所有磁碟區分組。

* *排除*
+
可讓您排除不想觸發警示的資源。例如、您可以排除名稱包含「'xyz'」字串的所有磁碟區。

+
[NOTE]
====
只有當您選取特定資源類型的所有資源時、才會顯示「排除」索引標籤、例如 <<All Volumes>> 或 <<All Volumes whose name contains '_xyz_'>>。

====




== 活動

此區域可讓您選取要觸發警示的事件。您可以根據特定嚴重性或一組事件觸發事件警示。

* *事件嚴重性*
+
可讓您根據嚴重性類型選取事件、嚴重性類型可以是「重大」、「錯誤」或「警告」。

* *事件名稱包含*
+
可讓您選取名稱包含指定字元的事件。





== 行動

此區域可讓您指定通知方法和通知頻率。

* *提醒這些使用者*
+
可讓您編輯電子郵件地址或使用者名稱、或指定新的電子郵件地址或使用者名稱來接收通知。

* *通知頻率*
+
可讓您編輯管理伺服器傳送通知的頻率、直到事件被確認、解決或移至過時狀態為止。

+
您可以選擇下列通知方法：

+
** 僅通知一次
** 以指定頻率通知
** 在指定時間範圍內以指定頻率通知


* *發出SNMP陷阱*
+
可讓您指定是否要將SNMP設陷傳送至全域設定的SNMP主機。

* *執行指令碼*
+
可讓您將指令碼與警示建立關聯。此指令碼會在產生警示時執行。





== 命令按鈕

* *儲存*
+
儲存變更並關閉對話方塊。

* *取消*
+
捨棄變更並關閉對話方塊。


