---
permalink: online-help/reference-edit-volume-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以設定警示、以便在產生與磁碟區容量相關的事件時傳送通知、也可以針對事件採取修正行動。例如、針對「Volume Full」（磁碟區已滿）臨界值、您可以設定警示、以便在特定期間內條件持續存在時傳送通知。 
---
= 「編輯Volume臨界值」對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定警示、在產生與磁碟區容量相關的事件時傳送通知、也可以針對事件採取修正行動。例如、針對「Volume Full」（磁碟區已滿）臨界值、您可以設定警示、以便在特定期間內條件持續存在時傳送通知。

您必須OnCommand 具備「管理員」或「儲存管理員」角色。

「編輯Volume臨界值」對話方塊可讓您設定套用至所選磁碟區的Volume層級臨界值。當臨界值在磁碟區層級設定時、其優先順序會高於群組層級臨界值或全域層級臨界值。

您可以在磁碟區層級設定容量、Snapshot複本、qtree配額、成長和inode的臨界值設定。設定Volume臨界值類型的群組動作時、群組動作臨界值會用於未在Volume層級設定的設定。如果未設定Volume臨界值類型的群組動作、則「編輯Volume臨界值」對話方塊中尚未設定的區域會使用全域臨界值。



== 容量區域

「容量」區域可讓您設定下列Volume容量臨界值條件：

* *空間幾乎已滿*
+
指定一個磁碟區被視為幾乎已滿的百分比。它也會顯示與指定臨界值對應的Volume大小。

+
您也可以使用滑桿來設定臨界值。

* *空間已滿*
+
指定磁碟區被視為已滿的百分比。它也會顯示與指定臨界值對應的Volume大小。

+
您也可以使用滑桿來設定臨界值。

* *直到完整日*
+
指定磁碟區達到完整容量之前的剩餘天數。





== Snapshot複本

Snapshot Copies區域可讓您針對Volume中的Snapshot複本、設定下列臨界值條件。

* * Snapshot保留已滿*
+
指定保留給Snapshot複本的空間被視為已滿的百分比。

* *直到完整日*
+
指定保留給Snapshot複本的空間達到完整容量之前的剩餘天數。

* *計數*
+
指定磁碟區上被視為太多的Snapshot複本數目。





== qtree配額區域

Qtree Quota區域可讓您針對選取的磁碟區設定下列qtree配額臨界值條件：

* *幾乎過度使用*
+
指定qtree配額將某個磁碟區視為幾乎過度委派的百分比。

* *過度使用*
+
指定qtree配額將磁碟區視為過度委派的百分比。





== 成長領域

成長區可讓您針對Volume成長設定下列臨界值條件：

* *成長率*
+
指定系統產生Volume成長率異常事件之前、磁碟區成長率被視為正常的百分比。

* *成長率敏感度*
+
指定套用至Volume成長率標準差的因素。如果成長率超過計入的標準差、就會產生Volume成長率異常事件。

+
成長率敏感度的值越低、表示該磁碟區對成長率的變化非常敏感。

+
[NOTE]
====
如果您在全域臨界值層級修改磁碟區的成長率敏感度、則變更也會套用至全域臨界值層級之集合體的成長率敏感度。

====




== inode區域

inode區域可讓您設定下列inode臨界值條件：

* *幾乎已滿*
+
指定一個磁碟區被視為消耗其大部分inode的百分比。

+
您也可以使用滑桿來設定臨界值。

* *完整*
+
指定一個磁碟區被視為已使用其所有inode的百分比。

+
您也可以使用滑桿來設定臨界值。





== 命令按鈕

命令按鈕可讓您針對選取的Volume執行下列工作：

* *還原為預設值*
+
可讓您將臨界值還原為下列其中一項：

+
** 群組值（如果磁碟區屬於某個群組且該群組具有Volume臨界值動作類型）。
** 全域值、如果磁碟區不屬於任何群組、或是屬於沒有Volume臨界值動作類型的群組。


* *儲存*
+
儲存所有臨界值設定。

* *儲存並關閉*
+
儲存所有臨界值設定、然後關閉對話方塊。

* *取消*
+
忽略臨界值設定的變更（若有）、並關閉對話方塊。


