---
permalink: online-help/reference-remote-authentication-page.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用「遠端驗證」頁面設定Unified Manager與驗證伺服器通訊、以驗證嘗試登入Unified Manager Web UI的遠端使用者。 
---
= 遠端驗證頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「遠端驗證」頁面設定Unified Manager與驗證伺服器通訊、以驗證嘗試登入Unified Manager Web UI的遠端使用者。

您必須OnCommand 具備「管理員」或「儲存管理員」角色。

選取「啟用遠端驗證」核取方塊後、即可使用驗證伺服器啟用遠端驗證。

* *驗證服務*
+
可讓您設定管理伺服器、以驗證目錄服務供應商（例如Active Directory、OpenLDAP）中的使用者、或是指定您自己的驗證機制。只有在啟用遠端驗證時、才能指定驗證服務。

+
** * Active Directory *
+
*** 系統管理員名稱
+
指定驗證伺服器的系統管理員名稱。

*** 密碼
+
指定存取驗證伺服器的密碼。

*** 基礎辨別名稱
+
指定驗證伺服器中遠端使用者的位置。例如、如果驗證伺服器的網域名稱是ou@domain.com、則基礎辨別名稱就是 `cn=ou,dc=domain,dc=com`。

*** 停用巢狀群組查詢
+
指定是否啟用或停用巢狀群組查詢選項。此選項預設為停用。如果您使用Active Directory、可以停用對巢狀群組的支援、以加速驗證。

*** 使用安全連線
+
指定用於與驗證伺服器通訊的驗證服務。



** * OpenLDAP*
+
*** 連結辨別名稱
+
指定用於在驗證伺服器中尋找遠端使用者的繫結辨別名稱、以及基礎辨別名稱。

*** 連結密碼
+
指定存取驗證伺服器的密碼。

*** 基礎辨別名稱
+
指定驗證伺服器中遠端使用者的位置。例如、如果驗證伺服器的網域名稱是ou@domain.com、則基礎辨別名稱就是 `cn=ou,dc=domain,dc=com`。

*** 使用安全連線
+
指定安全LDAP用於與LDAPS驗證伺服器通訊。



** *其他*
+
*** 連結辨別名稱
+
指定連結辨別名稱、搭配基礎辨別名稱使用、以在您設定的驗證伺服器中尋找遠端使用者。

*** 連結密碼
+
指定存取驗證伺服器的密碼。

*** 基礎辨別名稱
+
指定驗證伺服器中遠端使用者的位置。例如、如果驗證伺服器的網域名稱是ou@domain.com、則基礎辨別名稱就是 `cn=ou,dc=domain,dc=com`。

*** 傳輸協定版本
+
指定驗證伺服器所支援的輕量型目錄存取傳輸協定（LDAP）版本。您可以指定是否必須自動偵測通訊協定版本、或將版本設定為2或3。

*** 使用者名稱屬性
+
指定驗證伺服器中包含要由管理伺服器驗證之使用者登入名稱的屬性名稱。

*** 群組成員資格屬性
+
根據在使用者驗證伺服器中指定的屬性和值、指定一個值來指派管理伺服器群組成員資格給遠端使用者。

*** UGid
+
如果遠端使用者是驗證伺服器中的一群組功能名稱物件成員、則此選項可讓您根據該群組功能名稱物件中的指定屬性、將管理伺服器群組成員資格指派給遠端使用者。

*** 停用巢狀群組查詢
+
指定是否啟用或停用巢狀群組查詢選項。此選項預設為停用。如果您使用Active Directory、可以停用對巢狀群組的支援、以加速驗證。

*** 成員
+
指定驗證伺服器用來儲存群組個別成員資訊的屬性名稱。

*** 使用者物件類別
+
指定遠端驗證伺服器中使用者的物件類別。

*** 群組物件類別
+
指定遠端驗證伺服器中所有群組的物件類別。

*** 使用安全連線
+
指定用於與驗證伺服器通訊的驗證服務。





+
[NOTE]
====
如果您想要修改驗證服務、請務必刪除任何現有的驗證伺服器、然後新增驗證伺服器。

====




== 驗證伺服器區域

驗證伺服器區域會顯示管理伺服器用來尋找及驗證遠端使用者的驗證伺服器。遠端使用者或群組的認證資料由驗證伺服器維護。

* *命令按鈕*
+
可讓您新增、編輯或刪除驗證伺服器。

+
** 新增
+
可讓您新增驗證伺服器。

+
如果您要新增的驗證伺服器是高可用度配對的一部分（使用相同的資料庫）、您也可以新增合作夥伴驗證伺服器。這可讓管理伺服器在其中一個驗證伺服器無法連線時、與合作夥伴通訊。

** 編輯
+
可讓您編輯所選驗證伺服器的設定。

** 刪除
+
刪除選取的驗證伺服器。



* *名稱或IP位址*
+
顯示驗證伺服器的主機名稱或IP位址、用於驗證管理伺服器上的使用者。

* *連接埠*
+
顯示驗證伺服器的連接埠號碼。

* *測試驗證*
+
此按鈕會驗證遠端使用者或群組、以驗證驗證驗證伺服器的組態。

+
測試時、如果您只指定使用者名稱、管理伺服器會在驗證伺服器中搜尋遠端使用者、但不會驗證使用者。如果同時指定使用者名稱和密碼、管理伺服器會搜尋並驗證遠端使用者。

+
如果停用遠端驗證、則無法測試驗證。


