---
permalink: online-help/reference-events-report.html 
sidebar: sidebar 
keywords:  
summary: 「事件」報告可讓您檢視特定期間內事件趨勢的相關資訊。此資訊可讓您比較最近的活動與任何過去的營運活動、例如組態變更、升級等。這些資訊也能協助您判斷任何未解決的事件。 
---
= 事件報告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「事件」報告可讓您檢視特定期間內事件趨勢的相關資訊。此資訊可讓您比較最近的活動與任何過去的營運活動、例如組態變更、升級等。這些資訊也能協助您判斷任何未解決的事件。



== 事件報告圖表檢視

「事件」報告會以兩種格式顯示：

* 事件報告圖表檢視
* 事件報告表格檢視


事件圖表以兩種格式顯示：

* 事件嚴重性趨勢（所有開啟的事件）
* 事件狀態趨勢


此圖表顯示一段時間內所有開啟事件的事件嚴重性趨勢。事件計數會顯示在垂直（y）軸上、日期會顯示在水平（x）軸上。您可以將游標定位在特定點上、以檢視圖表上特定點的詳細資料。詳細資料會顯示事件嚴重性、特定嚴重性類別的事件數、以及事件日期。

顯示的事件嚴重性類型包括「嚴重」、「錯誤」和「警告」。事件嚴重性會因不同的色彩而有所差異。在不同的狀態下、同一日期的事件數量可能相同。

* *計數*
+
顯示事件數。

* *日期*
+
顯示日期。x軸顯示事件發生時間到目前日期為止的資料。您可以按一下並縮放圖表以取得詳細資料。



圖表顯示一段時間內每天的事件狀態趨勢。事件計數會顯示在垂直（y）軸上、日期會顯示在水平（x）軸上。詳細資料會顯示事件狀態、特定狀態的事件數、以及事件日期。

事件狀態為「新增」、「已確認」及「已解決」。事件狀態會依不同的色彩而有所差異。

圖表會以綠色表示的長條圖、顯示每日累計產生的新事件。確認和解決的事件數量會顯示為每日確認和解決的時間。

圖表中提供縮放功能。您可以使用此功能來縮放圖表中的特定點、以獲得更清楚的說明。

* *資料來源*
+
顯示事件來源。

* *狀態*
+
顯示事件的嚴重性。您可以篩選此欄以顯示特定嚴重性類型的事件。事件嚴重性類型為「重大」、「錯誤」或「警告」。

* *州*
+
顯示事件狀態：「新增」、「已確認」、「已解決」或「已過時」。您可以篩選此欄以顯示特定狀態的事件。

* *活動*
+
顯示事件名稱。

* *觸發時間*
+
顯示事件產生的時間。同時顯示時間和日期。

* *尚待處理的天數*
+
顯示事件發生之間的天數、以及其解決方案或標示為「已過時」。

* *來源類型*
+
顯示事件關聯的物件類型（例如、Storage Virtual Machine（SVM）、Volume或qtree）。

* *資料優先順序*
+
根據儲存物件的資料優先順序顯示註釋類型。

* *影響層級*
+
顯示事件是否歸類為事件、風險或資訊。

* *影響範圍*
+
顯示事件是容量、可用度、效能、保護還是組態事件。

* *指派對象*
+
顯示指派事件的使用者名稱。

* *指派時間*
+
顯示事件指派給使用者的時間。

* *附註*
+
顯示為事件新增的附註數目。

* *認可者*
+
顯示確認事件的使用者名稱。如果事件未被確認、則此欄位為空白。

* *確認時間*
+
顯示事件確認後經過的時間。如果經過的時間超過一週、時間戳記會顯示事件的確認時間。

* *解決者*
+
顯示已解決事件的使用者名稱。如果事件未解決、欄位為空白。

* *解決時間*
+
顯示事件解決後經過的時間。如果經過的時間超過一週、時間戳記會在事件解決時顯示。

* *過時時間*
+
顯示事件狀態變成過時的時間。


