---
permalink: online-help/reference-nfs-shares-health-fields.html 
sidebar: sidebar 
keywords:  
summary: NFS匯出報告可讓您稽核有關NFS匯出原則及其儲存系統中磁碟區相關規則的資訊。 
---
= NFS匯出報告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS匯出報告可讓您稽核有關NFS匯出原則及其儲存系統中磁碟區相關規則的資訊。



== NFS匯出報告表格檢視

* *叢集*
+
顯示叢集名稱。

* *儲存虛擬機器*
+
顯示具有NFS匯出原則的SVM名稱。

* * Volume *
+
顯示具有NFS匯出原則的磁碟區名稱。

* * Qtree *
+
顯示具有NFS匯出原則之磁碟區上qtree的名稱。

* * Volume狀態*
+
顯示Volume的目前狀態。狀態可以是「離線」、「線上」或「限制」。

+
** 離線
+
不允許對磁碟區進行讀取或寫入存取。

** 線上
+
允許對磁碟區進行讀寫存取。

** 受限
+
允許執行有限的作業、例如同位元檢查重建、但不允許存取資料。



* *交會路徑*
+
顯示掛載磁碟區的路徑。

* *交會路徑作用中*
+
顯示存取掛載磁碟區的路徑為作用中或非作用中。

* *匯出原則*
+
顯示定義所匯出之磁碟區存取權限的規則。

* *規則索引*
+
顯示與匯出原則相關的規則、例如驗證傳輸協定和存取權限。

* *存取傳輸協定*
+
顯示為匯出原則規則啟用的傳輸協定。

* *用戶端配對*
+
顯示具有存取磁碟區資料權限的用戶端。

* *唯讀存取*
+
顯示用於讀取磁碟區資料的驗證傳輸協定。

* *讀寫存取*
+
顯示用於在磁碟區上讀取或寫入資料的驗證傳輸協定。

* *安全風格*
+
顯示匯出之磁碟區的存取權限。安全樣式可以是UNIX、統一化、NTFS或混合式。

+
** UNIX（NFS用戶端）
+
Volume中的檔案和目錄具有UNIX權限。

** 統一化
+
Volume中的檔案和目錄具有統一的安全風格。

** NTFS（CIFS用戶端）
+
磁碟區中的檔案和目錄具有Windows NTFS權限。

** 混合
+
磁碟區中的檔案和目錄可以具有UNIX權限或Windows NTFS權限。



* * Unix權限*
+
以八進位字串格式顯示UNIX權限位元、這是針對匯出的磁碟區所設定的格式。它類似於UNIX樣式的權限位元。


