---
permalink: online-help/reference-capacity-all-clusters-view.html 
sidebar: sidebar 
keywords:  
summary: 「健全狀況/叢集儲存摘要」頁面可讓您檢視所有叢集中儲存容量與使用率的摘要資訊。此資訊可協助您瞭解可能的容量風險、並採取適當行動重新平衡工作負載。 
---
= 健全狀況/叢集儲存摘要頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「健全狀況/叢集儲存摘要」頁面可讓您檢視所有叢集中儲存容量與使用率的摘要資訊。此資訊可協助您瞭解可能的容量風險、並採取適當行動重新平衡工作負載。

使用*匯出*按鈕、將所有受監控叢集的詳細資料匯出為以逗號分隔的值 (`.csv`）檔案。

* *叢集*
+
叢集名稱。

* * HA配對*
+
透過形成兩個節點所獲得的HA配對值。

* *型號/系列*
+
叢集的模型或系列名稱。

* *作業系統版本*
+
系統上安裝的版本ONTAP 。

* *總原始容量*
+
顯示陣列中所有磁碟的實體容量總計。

* *未設定原始容量*
+
容器類型不是Aggregate、中斷、備援或共享的磁碟未設定容量。此容量一律高於ONTAP 支援的實體磁碟容量。例如、考慮使用2 TB磁碟。磁碟的實體容量ONTAP 為1.6 TB、而Unified Manager中未設定的原始容量則為1.8 TB。

* * Aggregate總容量*
+
使用者可用集合體的總大小。這包括Snapshot複本保留。

* * Aggregate已用容量*
+
已在Aggregate上使用的容量。這包括磁碟區、LUN及其他儲存效率技術經常成本所消耗的容量。

* *彙總未使用的容量*
+
可用於在Aggregate上儲存其他資料的容量。這包括Snapshot複本保留。

* *已分配LUN容量*
+
對應LUN的容量。

* *未分配LUN容量*
+
未對應至主機的所有LUN容量。

* * Volume總容量*
+
磁碟區的總容量（已使用加上未使用）。

* * Volume已用容量*
+
磁碟區的已用容量。

* * Volume未使用的容量*
+
磁碟區未使用的容量。

* * Volume Protection Capacity *
+
已啟用SnapMirror和SnapVault 支援功能的磁碟區容量。

* *叢集授權雲端層總計*
+
已在雲端層授權的總容量。此欄位會顯示給需要FabricPool 使用支援功能的儲存供應商、例如Amazon S3、Microsoft Azure Cloud、IBM Cloud Object Storage或Alibaba Cloud Object Storage。

* *已使用叢集授權的雲端層*
+
雲端層中的資料所使用的空間、是儲存供應商需要FabricPool 使用支援功能的空間。

* *使用叢集StorageGRID 功能*
+
雲端層中的資料所使用的空間、是儲存供應商不需要FabricPool 使用支援功能的空間、例如StorageGRID 、


