---
permalink: online-help/reference-dashboards-performance-page.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用Unified Manager效能儀表板來檢視所有受監控叢集的高層效能狀態。當Unified Manager無法與監控的叢集通訊時、「儀表板/效能」頁面也會顯示橫幅訊息。 
---
= 儀表板/效能頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Unified Manager效能儀表板來檢視所有受監控叢集的高層效能狀態。當Unified Manager無法與監控的叢集通訊時、「儀表板/效能」頁面也會顯示橫幅訊息。



== 總覽

叢集的排序依據嚴重性、使用下列條件：

. 如果叢集無法連線、
. 如果叢集有一或多個作用中的關鍵效能事件（紅色物件圖示）。
. 如果叢集有一或多個作用中的警示效能事件（黃色物件圖示）。
. 如果叢集沒有作用中的效能事件（綠色物件圖示）：叢集會依最高IOPS排序。


當使用者定義的效能臨界值原則超過臨界限制時、就會產生重大事件。當使用者定義的效能臨界值原則超過警告限制、或超過系統定義的臨界值原則或動態臨界值時、就會傳送警告事件。

[NOTE]
====
排序順序取決於作用中（新的或已確認的）事件總數、而非具有事件的物件數目。例如、如果叢集A有七個重大磁碟區延遲事件、而且叢集B有兩個重要的磁碟區延遲事件和兩個關鍵節點IOPS事件（總共四個關鍵事件）、即使叢集B有兩個紅色物件圖示、叢集A（有一個紅色物件圖示）仍會在清單上顯示得較高。

====
每個叢集都會顯示下列常見的監控事件類型：

* 儲存虛擬機器（SVM）、磁碟區和LUN的延遲事件
* 節點和SVM的IOPS事件
* 節點和SVM的Mbps事件
* 用於節點和集合體的效能容量
* 節點和集合體的使用率事件


Unified Manager可接收其他儲存物件和計數器的效能事件、例如、集合體的Mbps事件、以及磁碟區的IOPS事件。如果叢集有這些類型的事件、叢集名稱旁的圖示會指出警告（黃色）或嚴重（紅色）事件。如果五個計數器面板圖示中沒有黃色或紅色的圖示、此圖示可能表示事件存在、因為這些事件類型不符合現有的計數器面板類別。

您可以按一下物件圖示來顯示該物件的「效能詳細目錄」頁面、您可以在此檢視此叢集中該類型的所有物件。例如、按一下Volume圖示會顯示「Performance / Volume Inventory」（效能/ Volume資源清冊）頁面、其中會顯示所選叢集中所有磁碟區的清單、從最差到最佳的效能排序。



== 效能計數器

每個叢集都有五個效能計數器、每個計數器都顯示在獨立的面板中。此資訊會在每五分鐘收集期間之後自動更新：

|===
| 計數器 | 說明 


 a| 
延遲
 a| 
顯示叢集回應用戶端應用程式要求的速度（以毫秒為單位）（毫秒/秒）。圖示區域會指出是否有任何SVM、Volume或LUN具有任何作用中事件、其取決於超過臨界值設定的延遲值。



 a| 
IOPS
 a| 
顯示儲存系統的作業速度、以每秒輸入/輸出作業次數（IOPS）為單位。

* 圖示區域會根據超過臨界值設定的IOPS數目、指出任何節點或SVM是否有任何作用中事件。
* 底部區域會顯示最近五分鐘收集期間的叢集IOPS總計。




 a| 
Mbps
 a| 
顯示叢集的資料傳輸量、單位為兆位元組/秒（Mbps）。

* 圖示區域會指出任何節點或SVM是否有任何作用中的事件、這些事件取決於超過臨界值設定的Mbps值。
* 底部區域會顯示最近五分鐘收集期間的叢集處理量總計。




 a| 
使用的效能容量
 a| 
顯示是否有任何節點或集合體過度使用其可用的效能容量。

* 圖示區域會根據超出臨界值的效能使用容量值、指出任何節點或集合體是否有任何作用中事件。
* 底部區域顯示最繁忙節點和最繁忙集合體的最高效能使用容量值。


[NOTE]
====
效能容量資料只有在叢集中的節點安裝ONTAP 有VMware 9.0或更新版本的軟體時才能使用。

====


 a| 
使用率
 a| 
顯示是否過度使用任何節點或集合體上的資源。

* 圖示區域會根據使用率值跨越臨界值設定、指出任何節點或集合體是否有任何作用中事件。
* 底部區域顯示最繁忙節點和最繁忙集合體的最高使用率值。


|===
省略符號（...）在標頭區域中、表示目前正在收集效能資料。

您可以按一下「*檢視叢集詳細資料*」來顯示效能事件的叢集、以顯示「效能叢集登陸」頁面、您可以在其中檢視叢集和其他儲存物件的詳細效能資訊。



== 叢集狀態訊息

如果Unified Manager管理的叢集無法使用、效能計數器上方會顯示狀態訊息橫幅。如果叢集無法連線、狀態訊息橫幅右側會顯示*詳細資料*按鈕。按一下狀態訊息中的* Details（詳細資料）按鈕、即可瀏覽至叢集資料來源頁面、其中會顯示有關問題的完整資訊。在「叢集資料來源」頁面上、您可以找到疑難排解導致叢集無法使用之問題所需的資料。
