---
permalink: online-help/reference-volume-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: Volume容量與使用率報告可讓您檢視叢集中磁碟區容量與使用率的相關資訊。此資訊可讓您瞭解可能的容量風險、並檢視已設定、已使用及未使用的集合體容量。此外、此報告也能協助您決定是否啟用空間節約功能、例如重複資料刪除和精簡配置。 
---
= Volume容量與使用率報告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Volume容量與使用率報告可讓您檢視叢集中磁碟區容量與使用率的相關資訊。此資訊可讓您瞭解可能的容量風險、並檢視已設定、已使用及未使用的集合體容量。此外、此報告也能協助您決定是否啟用空間節約功能、例如重複資料刪除和精簡配置。



== Volume容量與使用率報告表格檢視

* *叢集*
+
顯示叢集名稱。

* *儲存虛擬機器*
+
顯示包含磁碟區的儲存虛擬機器（SVM）名稱。

* * Volume *
+
顯示磁碟區名稱。

* *總資料容量*
+
顯示磁碟區中的總資料容量（已使用及可用）。

* *已用資料容量*
+
顯示磁碟區中已使用的資料容量。

* *已用資料%*
+
以百分比顯示磁碟區中已使用的資料。

* *可用的資料容量*
+
顯示磁碟區中的可用資料容量。

* *可用資料%*
+
以百分比顯示磁碟區中的可用資料容量。

* *每日成長率%*
+
顯示每24小時在磁碟區內發生的成長率。

* *天滿*
+
顯示磁碟區達到完整容量之前的預估剩餘天數。

* *空間完整臨界值%*
+
指定被視為已滿磁碟區的限制。

* *空間接近完整臨界值%*
+
指定被視為幾乎已滿的磁碟區限制。

* *成長率臨界值%*
+
指定在系統產生Aggregate成長率異常事件之前、將Aggregate的成長率視為正常。

* *成長率敏感度臨界值*
+
指定套用至Volume成長率標準差的因素。如果成長率超過計入的標準差、就會產生Volume成長率異常事件。

* *直到完整臨界值的天數*
+
指定達到完整容量之前的剩餘天數。

* * Snapshot溢位%*
+
顯示Snapshot複本使用的資料空間百分比。

* * Snapshot保留已用容量*
+
顯示磁碟區中Snapshot複本使用的空間量。

* * Snapshot保留已使用%*
+
以百分比顯示磁碟區中Snapshot複本所使用的空間量。

* * Snapshot保留可用容量*
+
顯示磁碟區中Snapshot複本的可用空間量。

* * Snapshot保留可用%*
+
以百分比顯示磁碟區中Snapshot複本的可用空間量。

* * Snapshot保留總容量*
+
顯示磁碟區中的Snapshot複本總容量。

* * Snapshot複本保留完整臨界值%*
+
指定保留給Snapshot複本的空間被視為已滿的百分比。

* * Snapshot複本計數臨界值*
+
指定磁碟區上被視為太多的Snapshot複本數目。

* * Snapshot會複製數天直到完整臨界值*
+
指定保留給Snapshot複本的空間達到完整容量之前的剩餘天數。

* * inode數量*
+
顯示Volume中的inode數量。

* * inode使用率%*
+
指定磁碟區中使用的inode空間百分比。

* * inode完整臨界值*
+
指定一個磁碟區被視為已使用其所有inode的百分比。

* *幾乎達到完整臨界值*
+
指定一個磁碟區被視為消耗其大部分inode的百分比。

* *配額已認可容量*
+
顯示磁碟區中保留的空間。

* *配額過度委派容量*
+
顯示系統在產生Volume Quota過度委派事件之前可以使用的空間量。

* *配額過度使用臨界值%*
+
指定磁碟區即將過度使用的百分比。

* *配額接近過度使用臨界值%*
+
指定磁碟區空間即將過度使用的百分比。

* * Snapshot自動刪除*
+
顯示是否啟用或停用自動刪除Snapshot複本。

* *重複資料刪除*
+
顯示磁碟區是否啟用或停用重複資料刪除。

* *重複資料刪除空間節約效益*
+
顯示使用重複資料刪除技術在磁碟區中所節省的空間量。

* *壓縮*
+
顯示磁碟區是否已啟用或停用壓縮。

* *壓縮空間節約效益*
+
使用壓縮功能顯示儲存在磁碟區中的空間量。

* *快取原則*
+
顯示與所選磁碟區相關的快取原則。此原則提供有關如何為磁碟區進行Flash Pool快取的資訊。如需快取原則的詳細資訊、請參閱健全狀況/磁碟區目錄頁面。

* *快取保留優先順序*
+
顯示用於保留快取集區的優先順序。

* *精簡配置*
+
顯示是否為選取的Volume設定空間保證。有效值為「是」和「否」

* *自動擴充*
+
顯示FlexVol 當空間不足時、是否會自動增加大小。

* *空間保證*
+
當Volume從Aggregate移除可用區塊時、會顯示FlexVol 「聲音區」設定控制項。

* *州*
+
顯示正在匯出的Volume狀態。

* *《類型*》SnapLock
+
指出該Volume是SnapLock 一個不含SnapLock的磁碟區、還是一個非SnapLock磁碟區。

* *到期日*
+
The不再是截止日期SnapLock 。

* *分層政策*
+
如果此磁碟區部署在啟用FabricPool的Aggregate上、則會顯示該磁碟區的分層原則集。


