---
permalink: online-help/reference-add-alert-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以建立警示、以便在產生特定事件時通知您、以便迅速解決此問題、進而將對環境的影響降至最低。您可以針對單一資源或一組資源、以及特定嚴重性類型的事件、建立警示。您也可以指定警示的通知方法和頻率。 
---
= 新增警示對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立警示、以便在產生特定事件時通知您、以便迅速解決此問題、進而將對環境的影響降至最低。您可以針對單一資源或一組資源、以及特定嚴重性類型的事件、建立警示。您也可以指定警示的通知方法和頻率。

您必須OnCommand 具備「管理員」或「儲存管理員」角色。



== 名稱

此區域可讓您指定警示的名稱和說明：

* *警示名稱*
+
可讓您指定警示名稱。

* *警示說明*
+
可讓您指定警示的說明。





== 資源

此區域可讓您根據您要觸發警示的動態規則、選取個別資源或群組資源。動態規則_是根據您指定的文字字串篩選的一組資源。您可以從下拉式清單中選取資源類型來搜尋資源、也可以指定確切的資源名稱來顯示特定資源。

如果您是從任何儲存物件詳細資料頁面建立警示、則儲存物件會自動包含在警示中。

* *包括*
+
可讓您加入要觸發警示的資源。您可以指定文字字串來群組符合字串的資源、然後選取要納入警示的群組。例如、您可以將名稱包含「'abc'」字串的所有磁碟區分組。

* *排除*
+
可讓您排除不想觸發警示的資源。例如、您可以排除名稱包含「'xyz'」字串的所有磁碟區。

+
只有當您選取特定資源類型的所有資源時、才會顯示「排除」索引標籤：例如、 <<All Volumes>> 或 <<All Volumes whose name contains '_xyz_'>>。

+
如果資源同時符合您指定的INCLUDE和EXclude規則、排除規則將優先於INCLUDE規則、而且不會針對事件產生警示。





== 活動

此區域可讓您選取要建立警示的事件。您可以根據特定嚴重性或一組事件、為事件建立警示。

若要選取多個事件、請在選取時按住Ctrl鍵。

* *事件嚴重性*
+
可讓您根據嚴重性類型選取事件、嚴重性類型可以是「重大」、「錯誤」或「警告」。

* *事件名稱包含*
+
可讓您選取名稱包含指定字元的事件。





== 行動

此區域可讓您指定觸發警示時要通知的使用者。您也可以指定通知方法和通知頻率。

* *提醒這些使用者*
+
可讓您指定要接收通知的使用者電子郵件地址或使用者名稱。

+
如果您修改為使用者指定的電子郵件地址、然後重新開啟警示以進行編輯、則「名稱」欄位會顯示空白、因為修改後的電子郵件地址不再對應至先前選取的使用者。此外、如果您已從「管理/使用者」頁面修改所選使用者的電子郵件地址、則所選使用者的修改電子郵件地址不會更新。

* *通知頻率*
+
可讓您指定管理伺服器傳送通知的頻率、直到事件被確認、解決或移至過時狀態為止。

+
您可以選擇下列通知方法：

+
** 僅通知一次
** 以指定頻率通知
** 在指定時間範圍內以指定頻率通知


* *發出SNMP陷阱*
+
選取此方塊可讓您指定是否要將SNMP設陷傳送至全域設定的SNMP主機。

* *執行指令碼*
+
可讓您將自訂指令碼新增至警示。此指令碼會在產生警示時執行。





== 命令按鈕

* *儲存*
+
建立警示並關閉對話方塊。

* *取消*
+
捨棄變更並關閉對話方塊。


