---
permalink: online-help/reference-edit-qtree-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以設定警示、以便在產生與qtree容量相關的事件時傳送通知、也可以針對事件採取修正行動。例如、對於Qtree完整臨界值、您可以設定警示、以便在條件持續超過指定期間時傳送通知。 
---
= 編輯Qtree臨界值對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定警示、以便在產生與qtree容量相關的事件時傳送通知、也可以針對該事件採取修正行動。例如、對於Qtree完整臨界值、您可以設定警示、以便在條件持續超過指定期間時傳送通知。

您必須OnCommand 具備「管理員」或「儲存管理員」角色。

「編輯Qtree臨界值」對話方塊可讓您設定套用至所選qtree的qtree層級臨界值。當臨界值設定為qtree層級時、其優先順序會高於群組層級臨界值或全域層級臨界值。

您可以在qtree層級設定容量臨界值設定。設定qtree臨界值類型的群組動作時、群組動作臨界值會用於未在qtree層級設定的設定。如果未設定qtree臨界值類型的群組動作、則「編輯Qtree臨界值」對話方塊中尚未設定的區域會使用全域臨界值。



== 容量區域

「容量」區域可讓您設定下列qtree容量臨界值條件：

* *空間幾乎已滿*
+
指定qtree被視為幾乎已滿的百分比。它也會顯示對應於指定臨界值的qtree大小。

+
您也可以使用滑桿來設定臨界值。

* *空間已滿*
+
指定qtree被視為完整的百分比。它也會顯示對應於指定臨界值的qtree大小。

+
您也可以使用滑桿來設定臨界值。





== 命令按鈕

命令按鈕可讓您針對選取的qtree執行下列工作：

* *還原為預設值*
+
可讓您將臨界值還原為下列其中一項：

+
** 群組值（如果qtree屬於某個群組且該群組具有qtree臨界值動作類型）。
** 全域值、如果qtree不屬於任何群組、或是屬於沒有qtree臨界值動作類型的群組。


* *儲存*
+
儲存所有臨界值設定。

* *儲存並關閉*
+
儲存所有臨界值設定、然後關閉對話方塊。

* *取消*
+
忽略臨界值設定的變更（若有）、並關閉對話方塊。


