---
permalink: online-help/reference-dynamic-performance-event-chart-details.html 
sidebar: sidebar 
keywords:  
summary: 對於動態效能事件、「事件詳細資料」頁面的「系統診斷」區段會列出延遲最長或使用爭用叢集元件的最高工作負載。效能統計資料是根據上次分析事件之前偵測到效能事件的時間而得。這些圖表也會顯示爭用叢集元件的歷史效能統計資料。 
---
= 動態效能事件圖表詳細資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於動態效能事件、「事件詳細資料」頁面的「系統診斷」區段會列出延遲最長或使用爭用叢集元件的最高工作負載。效能統計資料是根據上次分析事件之前偵測到效能事件的時間而得。這些圖表也會顯示爭用叢集元件的歷史效能統計資料。

例如、您可以識別具有高使用率元件的工作負載、以決定要移至使用率較低元件的工作負載。移動工作負載可減少目前元件的工作量、有可能使元件不爭用。在本節中、是偵測到事件並進行最後分析的時間和日期範圍。對於作用中事件（新事件或已確認事件）、上次分析的時間會持續更新。

當您將游標停留在圖表上時、延遲和活動圖表會顯示最重要的工作負載名稱。按一下圖表右側的工作負載類型功能表、即可根據工作負載在事件中的角色（包括_Sharks _、_bulies _或_als受害者_）來排序工作負載、並顯示其延遲及其在爭用叢集元件上使用的詳細資料。您可以比較實際值與預期值、查看工作負載何時超出預期的延遲或使用範圍。請參閱 xref:concept-types-of-workloads-monitored-by-unified-manager.adoc[由Unified Manager監控的工作負載]。

[NOTE]
====
當您依延遲尖峰差異排序時、系統定義的工作負載不會顯示在表格中、因為延遲僅適用於使用者定義的工作負載。低延遲值的工作負載不會顯示在表格中。

====
如需動態效能臨界值的詳細資訊、請參閱 xref:reference-performance-event-analysis-and-notification.adoc[什麼是事件]。如需Unified Manager如何排列工作負載及決定排序順序的相關資訊、請參閱 xref:concept-how-unified-manager-determines-the-performance-impact-for-an-incident.adoc[Unified Manager如何判斷事件的效能影響]。

圖表中的資料會顯示上次分析事件之前24小時的效能統計資料。每個工作負載的實際值和預期值取決於事件涉及的工作負載時間。例如、工作負載可能會在偵測到事件後介入事件、因此其效能統計資料可能與事件偵測時的值不符。根據預設、工作負載會依延遲的尖峰（最高）偏移進行排序。

[NOTE]
====
由於Unified Manager最多可保留30天5分鐘的歷史效能和事件資料、因此如果事件超過30天、就不會顯示效能資料。

====
* *工作負載排序欄*
+
** *延遲圖*
+
顯示上次分析期間事件對工作負載延遲的影響。

** *元件使用率欄*
+
顯示爭用叢集元件之工作負載使用量的詳細資料。在圖表中、實際使用量是一條藍線。紅色長條會強調事件持續時間、從偵測時間到上次分析時間。如需詳細資訊、請參閱 xref:reference-workload-performance-measurement-values.adoc[工作負載效能測量]。

+
[NOTE]
====
對於網路元件、由於網路效能統計資料來自叢集之外的活動、因此不會顯示此欄。

====
** *元件使用率*
+
以百分比顯示QoS原則群組元件的網路處理、資料處理和集合體元件使用率歷程記錄、或是活動歷程記錄（以百分比表示）。不會顯示網路或互連元件的圖表。您可以指向統計資料、以在特定時間點檢視使用統計資料。

** *寫入MBps歷程記錄總計*
+
僅針對MetroCluster 「流通資源」元件、顯示所有鏡射至MetroCluster 乙方叢集之用的Volume工作負載之總寫入處理量（以百萬位元組/秒（Mbps）為單位）。

** *事件歷史記錄*
+
顯示紅色陰影線、以指出爭用中元件的歷史事件。對於過時的事件、圖表會顯示在偵測到所選事件之前及解決之後發生的事件。




