---
permalink: online-help/reference-edit-aggregate-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以設定警示、以便在產生與Aggregate容量相關的事件時傳送通知、並針對該事件採取修正行動。例如、針對Aggregate完整臨界值、您可以設定警示、以便在條件持續超過指定期間時傳送通知。 
---
= 「編輯Aggregate臨界值」對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定警示、在產生與Aggregate容量相關的事件時傳送通知、也可以針對該事件採取修正行動。例如、針對Aggregate完整臨界值、您可以設定警示、以便在條件持續超過指定期間時傳送通知。

您必須OnCommand 具備「管理員」或「儲存管理員」角色。

「編輯Aggregate臨界值」對話方塊可讓您設定套用至所選Aggregate的Aggregate層級臨界值。如果您設定Aggregate層級臨界值、則它們的優先順序高於全域層級臨界值。您可以在Aggregate層級設定容量、成長和Snapshot複本的臨界值設定。如果未設定這些設定、則會套用全域臨界值。

[NOTE]
====
臨界值不適用於節點的根Aggregate。

====


== 容量區域

「容量」區域可讓您設定下列Aggregate容量臨界值條件：

* *空間幾乎已滿*
+
指定將Aggregate視為接近完整的百分比。它也會顯示對應至指定臨界值的集合體大小。

+
您也可以使用滑桿來設定臨界值。

* *空間已滿*
+
指定將Aggregate視為完整的百分比。它也會顯示對應至指定臨界值的集合體大小。

+
您也可以使用滑桿來設定臨界值。

* *幾乎過度使用*
+
指定將Aggregate視為幾乎過度委派的百分比。

* *過度使用*
+
指定將Aggregate視為過度委派的百分比。

* *直到完整日*
+
指定集合體達到完整容量之前的剩餘天數。





== 成長領域

成長區可讓您設定下列臨界值條件、以利集合體成長：

* *成長率*
+
指定在系統產生Aggregate成長率異常事件之前、將Aggregate成長率視為正常的百分比。

* *成長率敏感度*
+
指定套用至集合體成長率標準差的因素。如果成長率超過計入的標準差、就會產生集合體成長率異常事件。

+
成長率敏感度的值越低、表示Aggregate對於成長率的變化非常敏感。

+
[NOTE]
====
如果您在全域臨界值層級修改Aggregate的成長率敏感度、則變更也會套用至全域臨界值層級之Volume的成長率敏感度。

====




== Snapshot複本區域

Snapshot Copies區域可讓您設定下列Snapshot Reserve臨界值條件：

* * Snapshot保留已滿*
+
指定集合體已耗用其保留給Snapshot複本的所有空間的百分比。

+
您也可以使用滑桿來設定臨界值。





== 命令按鈕

命令按鈕可讓您針對選取的Aggregate執行下列工作：

* *還原為預設值*
+
可讓您將Aggregate層級臨界值還原為全域值。

* *儲存*
+
儲存所有臨界值設定。

* *儲存並關閉*
+
儲存所有臨界值設定、然後關閉對話方塊。

* *取消*
+
忽略臨界值設定的變更（若有）、並關閉對話方塊。


