---
permalink: online-help/reference-management-annotations-page.html 
sidebar: sidebar 
keywords:  
summary: 「管理/附註」頁面可讓您在Unified Manager中建立附註、以便在儲存物件上加上附註、或是編輯或刪除附註。您可以使用註釋=值配對來手動為儲存物件加上註釋、或是設定註釋規則。儲存物件會根據您套用的註釋動態註解。 
---
= 管理/附註頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「管理/附註」頁面可讓您在Unified Manager中建立附註、以便在儲存物件上加上附註、或是編輯或刪除附註。您可以使用註釋=值配對來手動為儲存物件加上註釋、或是設定註釋規則。儲存物件會根據您套用的註釋動態註解。

當您以操作員身分登入時、您只能擁有頁面的讀取存取權。以儲存管理員或Unified Manager管理員身分登入時、您可以存取每個索引標籤中的「新增」、「編輯」或「刪除」按鈕。



== 註釋索引標籤

「附註」索引標籤可讓您在Unified Manager中檢視、建立、編輯或刪除附註。

* *附註清單*
+
顯示預先定義和自訂註釋的名稱。也會顯示與每個註釋相關的註釋值計數。您可以按一下註釋名稱來檢視註釋的詳細資料。





== 摘要區域

您可以檢視所選註釋的下列詳細資料：

* *說明*
+
顯示註釋的說明。

* *建立者*
+
顯示建立附註的使用者名稱。

* *建立日期*
+
顯示建立附註的日期。





== annotation=值配對

顯示可用於所選註釋的註釋值配對和相關儲存物件清單。

* * 價值 *
+
顯示annotation=Value配對的名稱。

* *適用的叢集*
+
顯示以特定註釋=值配對註釋的叢集數目。您可以按一下數字來檢視叢集頁面、其中會顯示與特定值相關聯的叢集篩選清單。

* *適用的儲存虛擬機器（SVM）*
+
顯示以特定註釋=值配對註釋的儲存虛擬機器（SVM）數量。您可以按一下數字來檢視儲存虛擬機器（SVM）頁面、該頁面會顯示與特定值相關聯的儲存虛擬機器（SVM）篩選清單。

* *適用的Volume *
+
顯示以特定註釋=值配對註釋的Volume數量。您可以按一下數字來檢視Volume（磁碟區）頁面、該頁面會顯示與特定值相關聯的磁碟區篩選清單。





== 透過規則建立物件關聯

顯示所選註釋的註釋規則清單、以及相關的儲存物件。

* *排名*
+
顯示要套用至儲存物件的註釋規則順序。

* *規則*
+
顯示註釋規則的名稱。

* *目標物件類型*
+
顯示套用註釋規則的儲存物件類型。

* *關聯的註釋值*
+
顯示套用至儲存物件的annotation=Value配對。

* *適用對象*
+
顯示根據註釋規則註釋的儲存物件計數。





== 手動物件關聯

顯示您已手動設定並與儲存物件相關聯的註釋清單。

* *註釋=值配對*
+
顯示手動評註的名稱和值。

* *適用的叢集*
+
顯示以特定手動附註值註釋的叢集數目。您可以按一下數字來檢視叢集頁面、其中會顯示與特定值相關聯的叢集篩選清單。

* *適用的儲存虛擬機器（SVM）*
+
顯示以特定手動附註值註釋的儲存虛擬機器（SVM）數量。您可以按一下數字來檢視儲存虛擬機器（SVM）頁面、該頁面會顯示與特定值相關聯的儲存虛擬機器（SVM）篩選清單。

* *適用的Volume *
+
顯示以特定手動附註值註釋的Volume數量。您可以按一下數字來檢視Volume（磁碟區）頁面、該頁面會顯示與特定值相關聯的磁碟區篩選清單。





== 命令按鈕

您必須OnCommand 具備「管理員」或「儲存管理員」角色。對於預先定義的註釋、您無法新增或刪除值。

* *新增附註*
+
開啟「新增附註」對話方塊、可讓您建立新的自訂附註、並將值指派給附註。

* *行動*
+
可讓您編輯或刪除選取的註釋說明。

* *編輯*
+
開啟「編輯附註」對話方塊、可讓您修改附註名稱和說明。

* *刪除*
+
可讓您刪除註釋值。您只能在值與任何註釋規則或群組規則無關時刪除。





== 註釋規則索引標籤

「附註規則」索引標籤會顯示您建立的附註規則、以便為儲存物件加上附註。您可以執行新增、編輯、刪除或重新排序註釋規則等工作。您也可以檢視符合附註規則的儲存物件數目。



== 命令按鈕

您必須OnCommand 具備「管理員」或「儲存管理員」角色。

* *新增*
+
顯示「新增附註規則」對話方塊、可讓您為儲存物件建立附註規則。

* *編輯*
+
顯示「編輯附註規則」對話方塊、可讓您重新設定先前設定的附註規則。

* *刪除*
+
刪除選取的註釋規則。

* *重新排序*
+
顯示「重新排序附註規則」對話方塊、可讓您重新排列附註規則的順序。





== 清單檢視

清單檢視會以表格格式顯示您在Unified Manager伺服器中建立的註釋規則。您可以使用欄篩選來自訂顯示的資料。「附註規則」索引標籤的清單檢視和「附註」索引標籤中「相關規則」區段的清單檢視包含下列欄位：

* 排名
* 名稱
* 目標物件類型
* 關聯的註釋值
* 適用的物件


「附註規則」標籤（「相關附註」）會顯示另一欄、顯示套用至儲存物件的附註名稱。
