---
permalink: online-help/reference-dashboard-page.html 
sidebar: sidebar 
keywords:  
summary: 「儀表板/總覽」頁面會以圖表形式顯示叢集、集合體和儲存虛擬機器（SVMs）等儲存物件的健全狀況。根據所產生的可用度、容量、效能及保護相關事件、這些儲存物件會歸類為健全、有風險或發生事件、或是與保護相關的事件、並歸類為健全、警告或錯誤。 
---
= 儀表板/總覽頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「儀表板/總覽」頁面會以圖表形式顯示叢集、集合體和儲存虛擬機器（SVM）等儲存物件的健全狀況。根據所產生的可用度、容量、效能及保護相關事件、這些儲存物件會歸類為健全、有風險或發生事件、或是與保護相關的事件、並歸類為健全、警告或錯誤。



== 叢集無法連線的長條

當無法連線至叢集時、Unified Manager會在每個頁面頂端的列中顯示詳細資料。如果所有叢集都可連線、則此窗格會隱藏。

您可以按下F5來重新整理窗格中顯示的資訊。此動作可確保窗格顯示目前無法連線之叢集的最新資訊。例如、如果移除具有「叢集無法連線」事件的叢集、或事件狀態為「已過時」、則當您重新整理窗格時、該事件的相關資訊將會移除。

您可以按一下「*詳細資料*」按鈕、檢視無法連線的叢集詳細資訊。此動作會開啟「事件」目錄頁面。關閉長條之後、只有當您重新登入Unified Manager時、才會再次顯示長條圖。



== 總覽區

* *可用度窗格*
+
顯示Unified Manager所監控之叢集、集合體及SVM的可用度資訊。儲存物件被分類為健全、有風險或有事件。例如、缺少備用磁碟的叢集狀態會顯示為「有風險」。

+
此窗格也會顯示每個類別中的儲存物件數目。按一下任何物件總計、即可前往該物件的頁面。例如、按一下叢集總計、您就會進入「健全狀況/叢集」資源清冊頁面。按一下欄頂端的數字、即可前往「事件」目錄頁面。

* *容量窗格*
+
顯示由Unified Manager監控之集合體和SVM容量的相關資訊。儲存物件被分類為健全、有風險或有事件。例如、已使用容量已達到完整臨界值的Aggregate狀態會顯示為「有風險」。

+
此窗格也會顯示每個類別中的儲存物件數目。

* *效能窗格*
+
顯示有關由Unified Manager監控之叢集、SVM和磁碟區效能的資訊。根據所產生的效能相關事件、儲存物件會分類為健全、有風險或有事件。例如、磁碟區的I/O回應時間已達到最大臨界值的狀態、會顯示為「有事件」。

+
此窗格也會顯示Unified Manager所監控的叢集、SVM和磁碟區總數。按一下任何物件總計、即可前往該物件的頁面。例如、按一下叢集總計會進入「效能/叢集」資源清冊頁面。

* *保護窗格*
+
顯示Unified Manager監控的保護關係資訊。保護關係分為「健全」、「警告」或「錯誤」。例如、延遲期間超過延遲警告臨界值的關聯會顯示為「警告」。

+
此窗格也會顯示每個保護類別中的儲存物件總數。按一下「延遲狀態」、「非同步資料庫」、「非同步鏡射」或「同步」類別的連結、即可在「保護/磁碟區關係」頁面中找到這些物件的篩選清單。


