---
permalink: online-help/reference-email-notification-format-page.html 
sidebar: sidebar 
keywords:  
summary: 「電子郵件通知格式」頁面會顯示當發生配額相關問題時、傳送給使用者或使用者群組的電子郵件規則（違反軟體限制或達到硬限制）。 
---
= 電子郵件通知格式頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「電子郵件通知格式」頁面會顯示當發生配額相關問題（軟體上限已超出或硬限制已達）時、傳送給使用者或使用者群組的電子郵件規則。

只有在產生下列使用者或使用者群組配額事件時、才會傳送電子郵件通知： 已違反使用者或群組配額磁碟空間軟限制、違反使用者或群組配額檔案計數軟限制、達到使用者或群組配額磁碟空間硬限制、或達到使用者或群組配額檔案計數硬限制。

* *寄件者*
+
顯示您可以修改的電子郵件地址。依預設、這是指定「設定/通知」頁面的電子郵件地址。

* *主題*
+
顯示通知電子郵件的主旨。

* *電子郵件詳細資料*
+
顯示通知電子郵件的文字。您可以根據需求修改文字。例如、您可以提供配額屬性的相關資訊、並減少關鍵字的數量。不過、您不應該修改關鍵字。

+
有效關鍵字如下：

+
** $EVAT_NAME
+
指定導致電子郵件通知的事件名稱。

** $quota目標
+
指定配額適用的qtree或Volume。

** $quota使用百分比
+
指定使用者或使用者群組所使用的磁碟硬體限制、磁碟軟體限制、檔案硬體限制或檔案軟體限制的百分比。

** $quota限制
+
指定使用者或使用者群組達到的磁碟硬體限制或檔案硬體限制、並產生下列其中一個事件：

+
*** 已達到使用者或群組配額磁碟空間硬限制
*** 已達到使用者或群組配額磁碟空間軟限制
*** 已達到使用者或群組配額檔案數硬限制
*** 已達到使用者或群組配額檔案計數軟限制


** $quota已使用
+
指定使用的磁碟空間、或使用者或使用者群組所建立的檔案數目。

** $quota使用者
+
指定使用者或使用者群組名稱。







== 命令按鈕

命令按鈕可讓您預覽、儲存或取消對電子郵件通知格式所做的變更：

* *預覽*
+
顯示通知電子郵件的預覽。

* *還原為原廠預設值*
+
可讓您將通知格式還原為原廠預設值。

* *儲存*
+
儲存對通知格式所做的變更。


