---
permalink: online-help/reference-group-action-volume-thresholds-section.html 
sidebar: sidebar 
keywords:  
summary: 「群組動作磁碟區臨界值」區段可讓您設定磁碟區的群組層級健全狀況臨界值。這些臨界值會套用至群組中的所有磁碟區。當在群組層級設定Volume健全狀況臨界值時、全域健全狀況臨界值不會受到影響。 
---
= 群組動作磁碟區臨界值區段
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「群組動作磁碟區臨界值」區段可讓您設定磁碟區的群組層級健全狀況臨界值。這些臨界值會套用至群組中的所有磁碟區。當在群組層級設定Volume健全狀況臨界值時、全域健全狀況臨界值不會受到影響。

您可以設定下列項目的Volume健全狀況臨界值、以設定群組動作：

* 容量
* 成長
* qtree配額
* Snapshot複本
* inode


如果未針對上述任何類別設定Volume健全狀況臨界值、則會使用全域預設值。您可以設定下列項目的健全狀況臨界值：

* 容量
* 成長
* qtree配額
* Snapshot複本
* inode




== 容量區段

您可以設定下列Volume容量健全狀況臨界值的條件：

* *空間幾乎已滿*
+
指定一個磁碟區被視為幾乎已滿的百分比：

+
** 預設值：80%
+
此臨界值的值必須低於管理伺服器產生事件的Volume Full臨界值值。

** 產生事件：磁碟區幾乎已滿
** 事件嚴重性：警告


* *空間已滿*
+
指定磁碟區被視為完整磁碟區的百分比：

+
** 預設值：90%
** 產生事件：Volume已滿
** 事件嚴重性：錯誤


* *過度使用*
+
指定磁碟區被視為過度委派的百分比：

+
** 預設值：100%
** 產生的事件：Volume過度使用
** 事件嚴重性：錯誤






== 成長區段

您可以針對Volume成長設定下列健全狀況臨界值條件：

* *成長率*
+
指定系統產生Volume成長率異常事件之前、Volume成長率被視為正常的百分比：

+
** 預設值：1%
** 產生的事件：Volume成長率異常
** 事件嚴重性：警告


* *成長率敏感度*
+
指定套用至Volume成長率標準差的因素。如果成長率超過計入的標準差、就會產生Volume成長率異常事件。

+
成長率敏感度的值越低、表示Aggregate對於成長率的變化非常敏感。成長率敏感度的範圍為1到5。

+
** 預設值：2.






== qtree配額區段

您可以設定磁碟區配額的下列健全狀況臨界值條件：

* *幾乎過度使用*
+
指定qtree配額將某個磁碟區視為幾乎過度委派的百分比：

+
** 預設值：95%
** 產生的事件：Volume Qtree配額即將過度使用
** 事件嚴重性：警告


* *過度使用*
+
指定qtree配額將磁碟區視為過度委派的百分比：

+
** 預設值：100%
** 產生的事件：Volume Qtree配額過度使用
** 事件嚴重性：錯誤






== Snapshot Copies區段

您可以為Volume中的Snapshot複本設定下列健全狀況臨界值條件：

* * Snapshot保留已滿*
+
指定保留給Snapshot複本的空間被視為已滿的百分比：

+
** 預設值：90%
** 產生的事件：Volume Snapshot Reserve已滿
** 事件嚴重性：錯誤


* *直到完整日*
+
指定保留給Snapshot複本的空間達到完整容量之前的剩餘天數：

+
** 預設值：7.
** 產生的事件：Volume Snapshot保留天數直到滿為止
** 事件嚴重性：錯誤


* *計數*
+
指定磁碟區上的Snapshot複本數量、這些複本被視為太多：

+
** 預設值：250
** 產生的事件：快照複本太多
** 事件嚴重性：錯誤






== inode區段

您可以為inode設定下列健全狀況臨界值條件：

* *幾乎已滿*
+
指定一個磁碟區被視為消耗其大部分inode的百分比：

+
** 預設值：80%
** 產生的事件：inode幾乎已滿
** 事件嚴重性：警告


* *完整*
+
指定一個磁碟區被視為已使用其所有inode的百分比：

+
** 預設值：90%
** 產生的事件：inode已滿
** 事件嚴重性：錯誤



