---
permalink: online-help/reference-configure-protection-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用Configure Protection（設定保護）對話方塊、為SnapVault 叢集上的所有讀取、寫入和資料保護磁碟區建立SnapMirror和SnapMirror關係、以確保來源磁碟區或主要磁碟區上的資料已複寫。 
---
= 設定保護對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Configure Protection（設定保護）對話方塊、為SnapVault 叢集上的所有讀取、寫入和資料保護磁碟區建立SnapMirror和SnapMirror關係、以確保來源磁碟區或主要磁碟區上的資料已複寫。



== 來源索引標籤

* *拓撲視圖*
+
顯示您正在建立之關係的視覺呈現。拓撲中的來源預設會反白顯示。

* *來源資訊*
+
顯示所選來源磁碟區的詳細資料、包括下列資訊：

+
** 來源叢集名稱
** 來源SVM名稱
** 累計Volume總大小
+
顯示所選所有來源磁碟區的總大小。

** 使用的累計Volume大小
+
顯示所有選取來源磁碟區的累計已用磁碟區大小。

** 來源Volume
+
在表格中顯示下列資訊：

+
*** 來源Volume
+
顯示所選來源磁碟區的名稱。

*** 類型
+
顯示Volume類型。

*** 部分類型SnapLock
+
顯示SnapLock Volume的邊板類型。選項包括「法規遵循」、「企業」和「非SnapLock」。

*** Snapshot複製
+
顯示用於基準傳輸的Snapshot複本。如果來源磁碟區為讀取/寫入、則Snapshot copy（Snapshot複本）欄中的預設值會指出新的Snapshot複本是預設建立的、並用於基準傳輸。如果來源磁碟區是資料保護磁碟區、則Snapshot Copy（快照複本）欄中的Default（預設）值表示未建立新的Snapshot複本、且所有現有的Snapshot複本都會傳輸到目的地。按一下Snapshot複本值會顯示Snapshot複本清單、您可以從中選取現有的Snapshot複本、以供基礎傳輸使用。如果來源類型為資料保護、則無法選取不同的預設Snapshot複本。









== SnapMirror索引標籤

可讓您在建立SnapMirror關係的同時、指定目的地叢集、儲存虛擬機器（SVM）和Aggregate來保護關係、以及目的地的命名慣例。您也可以指定SnapMirror原則和排程。

* *拓撲視圖*
+
顯示您正在建立之關係的視覺呈現。拓撲中的SnapMirror目的地資源預設會反白顯示。

* *目的地資訊*
+
可讓您選取保護關係的目的地資源：

+
** 進階連結
+
建立SnapMirror關係時、啟動「進階目的地設定」對話方塊。

** 叢集
+
列出可用做為保護目的地主機的叢集。此欄位為必填欄位。

** 儲存虛擬機器（SVM）
+
列出所選叢集上可用的SVM。在填入SVM清單之前、必須先選取叢集。此欄位為必填欄位。

** Aggregate
+
列出所選SVM上可用的集合體。在填入Aggregate清單之前、必須先選取叢集。此欄位為必填欄位。Aggregate清單會顯示下列資訊：

+
*** 排名
+
當多個Aggregate滿足目的地的所有需求時、根據下列條件、排名會指出列出Aggregate的優先順序：

+
.... 若要啟用故障網域分離、最好使用位於來源磁碟區節點以外其他節點上的Aggregate。
.... 建議在磁碟區較少的節點上使用Aggregate、以便在叢集中的節點之間實現負載平衡。
.... 若要實現容量平衡、最好使用比其他集合體具有更多可用空間的集合體。等級1表示根據這三項條件、集合體是最受歡迎的。


*** Aggregate名稱
+
Aggregate的名稱

*** 可用容量
*** 集合體上可用於資料的空間量
*** 資源池
+
集合所屬資源池的名稱



** 命名慣例
+
指定套用至目的地Volume的預設命名慣例。您可以接受所提供的命名慣例、也可以建立自訂慣例。命名慣例可以具有下列屬性：%C、%M、%V和%N、其中%C是叢集名稱、%M是SVM名稱、%V是來源Volume、%N是拓撲目的地節點名稱。

+
如果輸入無效、則命名慣例欄位會以紅色強調顯示。按一下「Preview Name」（預覽名稱）連結會顯示您所輸入命名慣例的預覽、預覽文字會隨著您在文字欄位中輸入命名慣例而動態更新。建立關聯時、會在目的地名稱後面加上介於001到999之間的字尾、以取代 `nnn` 這會顯示在預覽文字中、先指派001、再指派第二個、依此類推。



* *關係設定*
+
可讓您指定保護關係使用的最大傳輸率、SnapMirror原則及排程：

+
** 最大傳輸率
+
指定透過網路在叢集之間傳輸資料的最大速率。如果您選擇不使用最大傳輸率、則關聯之間的基礎傳輸不受限制。但是、如果您執行ONTAP 的是Sing 8.2、而且主要叢集和次要叢集相同、則會忽略此設定。

** SnapMirror原則
+
指定ONTAP 關係的SnapMirror原則。預設值為DPDefault。

** 建立原則
+
啟動Create SnapMirror Policy（建立SnapMirror原則）對話方塊、讓您建立並使用新的SnapMirror原則。

** SnapMirror排程
+
指定ONTAP 關係的SnapMirror原則。可用時程包括無、5分鐘、8小時、每日、每小時、 以及每週。預設值為「無」、表示沒有任何排程與關係相關。除非屬於儲存服務、否則不含排程的關係不會有延遲狀態值。

** 建立排程
+
啟動「建立排程」對話方塊、可讓您建立新的SnapMirror排程。







== 選項卡SnapVault

可讓您指定次要叢集、SVM和Aggregate以建立保護關係、以及次要Volume的命名慣例、同時建立SnapVault 一個彼此之間的不協調關係。您也可以指定SnapVault 一個不確定的原則和排程。

* *拓撲視圖*
+
顯示您正在建立之關係的視覺呈現。根據預設、會強調顯示拓撲中的「列舉次要資源」SnapVault 。

* *次要資訊*
+
可讓您選取用於保護關係的次要資源：

+
** 進階連結
+
啟動「進階次要設定」對話方塊。

** 叢集
+
列出可用做為次要保護主機的叢集。此欄位為必填欄位。

** 儲存虛擬機器（SVM）
+
列出所選叢集上可用的SVM。在填入SVM清單之前、必須先選取叢集。此欄位為必填欄位。

** Aggregate
+
列出所選SVM上可用的集合體。在填入Aggregate清單之前、必須先選取叢集。此欄位為必填欄位。Aggregate清單會顯示下列資訊：

+
*** 排名
+
當多個Aggregate滿足目的地的所有需求時、根據下列條件、排名會指出列出Aggregate的優先順序：

+
.... 如果要啟用故障網域分離、最好使用位於主磁碟區節點以外其他節點上的Aggregate。
.... 建議在磁碟區較少的節點上使用Aggregate、以便在叢集中的節點之間實現負載平衡。
.... 若要實現容量平衡、最好使用比其他集合體具有更多可用空間的集合體。等級1表示根據這三項條件、集合體是最受歡迎的。


*** Aggregate名稱
+
Aggregate的名稱

*** 可用容量
*** 集合體上可用於資料的空間量
*** 資源池
+
集合所屬資源池的名稱



** 命名慣例
+
指定套用至次要Volume的預設命名慣例。您可以接受所提供的命名慣例、也可以建立自訂慣例。命名慣例可以具有下列屬性：%C、%M、%V和%N、其中%C為叢集名稱、%M為SVM名稱、%V為來源Volume、%N為拓撲次要節點名稱。

+
如果輸入無效、則命名慣例欄位會以紅色強調顯示。按一下「Preview Name」（預覽名稱）連結會顯示您所輸入命名慣例的預覽、預覽文字會隨著您在文字欄位中輸入命名慣例而動態更新。如果您輸入的值無效、無效資訊會在預覽區域顯示為紅色問號。建立關聯時、會在次要名稱後面加上一個介於001到999之間的字尾、取代 `nnn` 這會顯示在預覽文字中、先指派001、再指派第二個、依此類推。



* *關係設定*
+
可讓您指定SnapVault 保護關係所使用的最大傳輸率、不適用的原則和SnapVault 不適用的排程：

+
** 最大傳輸率
+
指定透過網路在叢集之間傳輸資料的最大速率。如果您選擇不使用最大傳輸率、則關聯之間的基礎傳輸不受限制。但是、如果您執行ONTAP 的是Sing 8.2、而且主要叢集和次要叢集相同、則會忽略此設定。

** 政策SnapVault
+
指定ONTAP SnapVault 關聯的不規則。預設值為XDPDefault。

** 建立原則
+
啟動「建立SnapVault 功能不全原則」對話方塊、讓您建立及使用新SnapVault 的功能不全原則。

** 排程SnapVault
+
指定ONTAP SnapVault 關聯的不一致排程。可用時程包括無、5分鐘、8小時、每日、每小時、 以及每週。預設值為「無」、表示沒有任何排程與關係相關。除非屬於儲存服務、否則不含排程的關係不會有延遲狀態值。

** 建立排程
+
啟動「建立排程」對話方塊、可讓您建立SnapVault 一套「還原排程」。







== 命令按鈕

命令按鈕可讓您執行下列工作：

* *取消*
+
捨棄您的選擇、然後關閉「設定保護」對話方塊。

* *適用*
+
套用您的選擇、並開始保護程序。


