---
permalink: online-help/reference-advanced-secondary-setting-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用「進階次要設定」對話方塊、在次要磁碟區上啟用版本彈性複寫、多個複本備份及空間相關設定。若要變更啟用或停用目前設定、您可以使用「進階次要設定」對話方塊。 
---
= 進階次要設定對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「進階次要設定」對話方塊、在次要磁碟區上啟用版本彈性複寫、多個複本備份及空間相關設定。若要變更啟用或停用目前設定、您可以使用「進階次要設定」對話方塊。

空間相關設定可將儲存的資料量最大化、包括重複資料刪除、資料壓縮、自動擴充及空間保證。

對話方塊包含下列欄位：

* *啟用版本彈性複寫*
+
利用版本彈性的複寫功能來啟用SnapMirror。靈活版本的複寫功能可讓來源Volume受到SnapMirror保護、即使目的地Volume是以ONTAP 舊版的版本執行、但前提是來源Volume和目的地都執行ONTAP 的是更新版本的版本。

+
** 啟用備份
+
如果啟用版本彈性複寫、也可將SnapMirror來源資料的多個Snapshot複本傳輸至SnapMirror目的地、並保留在SnapMirror目的地。



* *啟用重複資料刪除*
+
在SnapVault 二線磁碟區上啟用重複資料刪除功能、使重複資料區塊不再重複、以節省空間。當空間節約至少10%、而且資料覆寫速度不快時、您可能會使用重複資料刪除技術。重複資料刪除常用於虛擬化環境、檔案共用和備份資料。此設定預設為停用。啟用時、此作業會在每次傳輸後啟動。

+
** 啟用壓縮
+
啟用透明資料壓縮。當空間節約至少10%、可能的成本可接受、以及有足夠的系統資源可在非尖峰時間完成壓縮時、您可以使用壓縮。在不受影響的情況下、此設定預設為停用。SnapVault只有在選取重複資料刪除時、才能使用壓縮功能。

** 壓縮內嵌
+
在將資料寫入磁碟之前先壓縮資料、立即節省空間。當系統在尖峰時段的使用率不超過50%、以及系統在尖峰時段可以容納新的寫入和額外的CPU時、您可以使用即時壓縮。此設定只有在選取「啟用壓縮」時才能使用。



* *啟用自動擴充*
+
可讓您在可用空間百分比低於指定臨界值時、只要相關聯的Aggregate上有可用空間、就能自動擴充目的地Volume。

* *最大尺寸*
+
設定磁碟區可以增加的最大百分比。預設值比來源Volume大20%。如果目前大小大於或等於最大自動擴充百分比、則Volume不會自動增加。此欄位只有在啟用自動擴充設定時才會啟用。

* *增量大小*
+
指定在達到來源Volume的最大百分比之前、Volume自動成長的百分比增量。

* *空間保證*
+
確保在次要磁碟區上配置足夠的空間、以確保資料傳輸永遠成功。空間保證設定可以是下列其中一項：

+
** 檔案
** Volume
** 無、例如、您可能有一個200 GB的磁碟區、其中包含總計50 GB的檔案、但這些檔案只能保留10 GB的資料。Volume保證會將200 GB分配給目的地Volume、無論來源上的內容為何。檔案保證會配置50 GB的空間、以確保為來源上的檔案保留足夠的空間；在此案例中選取「無」、表示目的地上只會配置10 GB的空間給來源上的檔案資料實際使用空間。


+
空間保證預設設為Volume。





== 命令按鈕

命令按鈕可讓您執行下列工作：

* *適用*
+
儲存選取的效率設定、並在您按一下「組態保護」對話方塊中的「*套用*」時套用。

* *取消*
+
捨棄您的選擇並關閉「進階目的地設定」對話方塊。



*相關資訊*

http://www.netapp.com/us/media/tr-3966.pdf["NetApp技術報告3966：NetApp資料壓縮與重複資料刪除部署與實作指南（叢集Data ONTAP 式）"]
