---
permalink: online-help/reference-notifications-page.html 
sidebar: sidebar 
keywords:  
summary: 您可以設定Unified Manager伺服器、在事件產生或指派給使用者時傳送通知。您也可以設定通知機制。例如、通知可以以電子郵件或SNMP設陷的形式傳送。 
---
= 設定/通知頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定Unified Manager伺服器、在事件產生或指派給使用者時傳送通知。您也可以設定通知機制。例如、通知可以以電子郵件或SNMP設陷的形式傳送。

您必須OnCommand 具備「管理員」或「儲存管理員」角色。



== 電子郵件

此區域可讓您設定警示通知的下列電子郵件設定：

* *寄件者地址*
+
指定警示通知傳送來源的電子郵件地址。此值也會在共用時用作報告的「寄件者」位址。如果寄件者地址預先填入「OnCommand@localhost.com」地址、您應該將其變更為實際有效的電子郵件地址、以確保所有電子郵件通知都能順利傳送。





== SMTP伺服器

此區域可讓您設定下列的SMTP伺服器設定：

* *主機名稱或IP位址*
+
指定您的SMTP主機伺服器主機名稱、用於傳送警示通知給指定的收件者。

* *使用者名稱*
+
指定SMTP使用者名稱。僅當SMTPAUTH在SMTP伺服器中啟用時、才需要使用SMTP使用者名稱。

* *密碼*
+
指定SMTP密碼。僅當SMTPAUTH在SMTP伺服器中啟用時、才需要使用SMTP使用者名稱。

* *連接埠*
+
指定由SMTP主機伺服器用來傳送警示通知的連接埠。

+
預設值為25。

* *使用ARTTLS*
+
核取此方塊可透過TLS/SSL傳輸協定（也稱為Start_TLS和StartTLS）、在SMTP伺服器與管理伺服器之間提供安全通訊。

* *使用SSL*
+
核取此方塊可透過SSL傳輸協定、在SMTP伺服器與管理伺服器之間提供安全通訊。





== SNMP

此區域可讓您設定下列SNMP設陷設定：

* *版本*
+
根據所需的安全類型、指定您要使用的SNMP版本。選項包括第1版、第3版、第3版（含驗證）和第3版（含驗證與加密）。預設值為版本1。

* *設陷目的地主機*
+
指定接收管理伺服器所傳送之SNMP設陷的主機名稱或IP位址（IPV4或IPV6）。

* *外傳陷阱連接埠*
+
指定SNMP伺服器接收管理伺服器傳送之設陷的連接埠。

+
預設值為162。

* *社群*
+
存取主機的社群字串。

* *引擎ID*
+
指定SNMP代理程式的唯一識別碼、並由管理伺服器自動產生。引擎ID適用於SNMP版本3、SNMP版本3搭配驗證、以及SNMP版本3搭配驗證與加密。

* *使用者名稱*
+
指定SNMP使用者名稱。使用者名稱可用於SNMP版本3、SNMP版本3搭配驗證、以及SNMP版本3搭配驗證與加密。

* *驗證傳輸協定*
+
指定用於驗證使用者的傳輸協定。傳輸協定選項包括MD5和SHa。預設值為md5。驗證傳輸協定適用於具備驗證功能的SNMP版本3、以及具備驗證與加密功能的SNMP版本3。

* *驗證密碼*
+
指定驗證使用者時所使用的密碼。驗證密碼適用於具有驗證功能的SNMP版本3、以及具有驗證和加密功能的SNMP版本3。

* *隱私權協議*
+
指定用於加密SNMP訊息的隱私權傳輸協定。傳輸協定選項包括AES 128和Des。預設值為AES 128。具有驗證和加密功能的SNMP版本3提供隱私權傳輸協定。

* *隱私密碼*
+
指定使用隱私權傳輸協定時的密碼。具有驗證和加密功能的SNMP版本3提供隱私密碼。


