---
permalink: online-help/reference-snapmirror-relationship-events.html 
sidebar: sidebar 
keywords:  
summary: SnapMirror關係事件可讓您取得SnapMirror關係狀態的相關資訊、以便監控潛在問題。事件會依影響區域分組、包括事件和陷阱名稱、影響層級、來源類型和嚴重性。 
---
= SnapMirror關係事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror關係事件可讓您取得SnapMirror關係狀態的相關資訊、以便監控潛在問題。事件會依影響區域分組、包括事件和陷阱名稱、影響層級、來源類型和嚴重性。



== 影響領域：保護

星號（*）表示已轉換為Unified Manager事件的EMS事件。

|===
| 事件名稱（陷阱名稱） | 影響層級 | 來源類型 | 嚴重性 


 a| 
鏡射複寫不良（ocumEvtSnapmirror關係不良）
 a| 
風險
 a| 
SnapMirror關係
 a| 
警告



 a| 
鏡射複寫中斷（ocumEvtSnapmirror關係StateBrokenoff）
 a| 
風險
 a| 
SnapMirror關係
 a| 
錯誤



 a| 
鏡射複寫初始化失敗（ocumEvtSnapmirror關係初始化失敗）
 a| 
風險
 a| 
SnapMirror關係
 a| 
錯誤



 a| 
鏡射複寫更新失敗（ocumEvtSnapmirror關係更新失敗）
 a| 
風險
 a| 
SnapMirror關係
 a| 
錯誤



 a| 
鏡射複寫延遲錯誤（ocumEvtSnapMirrorRelationshipLag錯誤）
 a| 
風險
 a| 
SnapMirror關係
 a| 
錯誤



 a| 
鏡射複寫延遲警告（ocumEvtSnapMirrorRelationshiplag警告）
 a| 
風險
 a| 
SnapMirror關係
 a| 
警告



 a| 
鏡射複寫重新同步失敗（ocumEvtSnapmirror關係重新同步失敗）
 a| 
風險
 a| 
SnapMirror關係
 a| 
錯誤



 a| 
鏡射複寫DeletedocumEvtSnapmirror關係已刪除
 a| 
風險
 a| 
SnapMirror關係
 a| 
警告



 a| 
同步複寫不同步*
 a| 
風險
 a| 
SnapMirror關係
 a| 
警告



 a| 
同步複寫已還原*
 a| 
活動
 a| 
SnapMirror關係
 a| 
資訊



 a| 
同步複寫自動重新同步失敗*
 a| 
風險
 a| 
SnapMirror關係
 a| 
錯誤

|===