---
permalink: online-help/reference-create-snapvault-policy-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 「建立SnapVault 不規則」對話方塊可讓您建立原則、以設定SnapVault 進行不規則地傳輸的優先順序。您可以使用原則來最大化從主要磁碟區傳輸到次要磁碟區的效率。 
---
= 「建立SnapVault 不規則」對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「建立SnapVault 不規則」對話方塊可讓您建立原則、以設定SnapVault 進行不規則地傳輸的優先順序。您可以使用原則來最大化從主要磁碟區傳輸到次要磁碟區的效率。

* *目的地叢集*
+
您在SnapVault 「組態保護」對話方塊的「還原」索引標籤中選取的叢集名稱。

* *目的地SVM*
+
您在SnapVault 「組態保護」對話方塊的「SVM」索引標籤中選取的SVM名稱。

* *原則名稱*
+
您為新原則提供的名稱。原則名稱可以包含A到Z、a到z、0到9、句點（.）、連字號（-）、 和下劃線（_）。

* *傳輸優先順序*
+
執行傳輸的優先順序。您可以選取「正常」或「低」。傳輸與指定一般傳輸優先順序之原則的關係、會在具有指定低傳輸優先順序之原則的原則之前執行。預設設定為「正常」。

* *意見*
+
可選欄位、您可在其中新增最多255個字元的關於SnapVault 此功能的註解。

* *忽略存取時間*
+
指定是否忽略僅變更存取時間之檔案的遞增傳輸。

* *複寫標籤*
+
在表格中列出ONTAP 由功能組選取的Snapshot複本相關規則、其中的原則中有特定的複寫標籤。您也可以取得下列資訊和行動：

+
** 命令按鈕
+
命令按鈕可讓您執行下列動作：

+
*** 新增
+
可讓您建立Snapshot複本標籤和保留計數。

*** 編輯保留計數
+
可讓您變更現有Snapshot複本標籤的保留計數。保留計數必須為1到251之間的數字。所有規則的所有保留計數總和不得超過251。

*** 刪除
+
可讓您刪除現有的Snapshot複本標籤。



** Snapshot複製標籤
+
顯示Snapshot複本標籤。如果您選取一個或多個具有相同本機Snapshot複本原則的磁碟區、則會顯示原則中每個標籤的項目。如果您選取多個具有兩個以上本機Snapshot複本原則的磁碟區、則表格會顯示所有原則的所有標籤

** 排程
+
顯示與每個Snapshot複本標籤相關的排程。如果標籤有多個相關排程、則該標籤的排程會顯示在以逗號分隔的清單中。如果您選取多個具有相同標籤但排程不同的磁碟區、排程會顯示「'differe'」、表示有多個排程與所選磁碟區相關聯。

** 目的地保留計數
+
顯示Snapshot複本的數量、以及SnapVault 保留在不二線系統上的指定標籤。具有多個排程的標籤保留計數會顯示每個標籤和排程配對的保留計數總和。如果您使用兩個或多個本機Snapshot複本原則選取多個磁碟區、則保留計數為空白。




