---
permalink: online-help/reference-performance-statistics-displayed-in-the-data-breakdown-charts.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用圖表來檢視Volume的效能趨勢。您也可以檢視讀取與寫入、網路傳輸協定活動、QoS原則群組節流對延遲的影響、讀取與寫入快取儲存的比率、工作負載所用的叢集CPU總時間、以及特定的叢集元件等統計資料。 
---
= 效能統計資料會顯示在資料明細表中
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用圖表來檢視Volume的效能趨勢。您也可以檢視讀取與寫入、網路傳輸協定活動、QoS原則群組節流對延遲的影響、讀取與寫入快取儲存的比率、工作負載所用的叢集CPU總時間、以及特定的叢集元件等統計資料。

這些檢視最多可顯示當天的30天統計資料。在歷史資料圖表中、如果您選取超過1天的時間範圍、則圖表會根據您的螢幕解析度、顯示天數內延遲和IOPS的最大值。

[NOTE]
====
您可以使用*全選*核取方塊來選取或取消選取所有列出的圖表選項。

====
* * 延遲 *
+
下表詳細說明所選工作負載的延遲或回應時間資訊：

+
** *叢集元件*
+
顯示所選磁碟區所使用之每個叢集元件所花費時間的圖表。

+
此圖表可協助您判斷每個元件的延遲影響、因為它與總延遲有關。您可以使用每個零組件旁的核取方塊來顯示及隱藏其圖表。

+
對於QoS原則群組、資料只會顯示給使用者定義的原則群組。系統定義的原則群組（例如預設原則群組）會顯示零。

** *讀取/寫入延遲*
+
顯示所選時間範圍內、從所選Volume工作負載成功讀取和寫入要求的延遲圖表。

+
寫入要求為橘色行、讀取要求則為藍線。這些要求是特定於所選Volume工作負載的延遲、而非叢集上的所有工作負載。

+
[NOTE]
====
讀取和寫入統計資料未必一定會加到延遲圖表中顯示的總延遲統計資料中。這是預期的行為、取決於Unified Manager如何收集及分析工作負載的讀寫統計資料。

====
** *原則群組影響*
+
顯示受QoS原則群組之處理量限制影響之所選Volume工作負載延遲百分比的圖表。

+
如果工作負載受到節流控制、則百分比會指出節流在特定時間點造成延遲的程度。百分比值表示節流量：

+
*** 0%=無節流
*** >0%=節流
*** 超過20%=重大節流如果叢集可以處理更多工作、您可以增加原則群組限制來減少節流。另一個選項是將工作負載移至較不忙碌的集合體。




+
[NOTE]
====
圖表會顯示使用者定義的QoS原則群組中、只有設定處理量限制的工作負載。如果工作負載位於系統定義的原則群組（例如預設原則群組）或原則群組（沒有QoS限制）中、就不會顯示此功能。對於QoS原則群組、您可以將游標指向原則群組名稱、以顯示其處理量限制及上次修改的時間。如果原則群組在相關叢集新增至Unified Manager之前已修改、則上次修改時間是Unified Manager首次探索叢集的日期和時間。

====
* * IOPS *
+
下表詳細說明所選工作負載的IOPS資料：

+
** *讀取/寫入/其他*
+
顯示圖表、顯示選定時間範圍內每秒讀取和寫入IOPS及其他IOPS的數量。

+
其他IOPS則是由用戶端啟動的非讀取或寫入的傳輸協定活動。例如、在NFS環境中、這可能是中繼資料作業、例如getattr、setattr或fsstat。在CIFS環境中、這可能是屬性查詢、目錄清單或防毒掃描。寫入IOPS為橘色線、讀取要求則為藍線。這些要求是特定於所選Volume工作負載的所有作業、而非叢集上的所有作業。



* * Mbps*
+
下表詳細說明所選工作負載的處理量資料：

+
** *快取命中率*
+
顯示在所選時間範圍內、快取滿足用戶端應用程式讀取要求的百分比圖表。

+
快取可以位於Flash Cache卡或Flash Pool Aggregate中的固態硬碟（SSD）上。快取命中率（藍色）是從快取讀取。快取遺漏（橘色）是從Aggregate中的磁碟讀取。這些要求是特定於所選的Volume工作負載、而非叢集上的所有工作負載。

+
您可以在Unified Manager Health（Unified Manager健全狀況）頁面和OnCommand 《系統管理程式》中、檢視更多有關Volume快取使用量的詳細資訊。



* *元件*
+
下表詳細說明所選工作負載所使用的叢集元件資料：

+
** *叢集CPU時間*
+
顯示所選工作負載所使用之叢集中所有節點的CPU使用時間（單位為毫秒）圖表。

+
圖表會顯示網路處理與資料處理的CPU使用時間組合。此外、系統定義工作負載的CPU時間也會包含在內、這些工作負載會與所選工作負載相關聯、並使用相同的節點進行資料處理。您可以使用圖表來判斷工作負載是否為叢集上CPU資源的高使用者。您也可以使用圖表、搭配「延遲」圖表下的讀取/寫入延遲圖表、或是IOPS圖表下的讀取/寫入/其他圖表、來決定隨著時間而對工作負載活動所做的變更如何影響叢集CPU使用率。

** *磁碟使用率*
+
顯示圖表、顯示儲存集合體中資料磁碟在所選時間範圍內的使用率百分比。

+
使用率僅包括來自所選Volume工作負載的磁碟讀取和寫入要求。不包含從快取讀取。使用率是特定於所選磁碟區工作負載、而非所有磁碟上的工作負載。如果受監控的Volume涉及到Volume移動、則此圖表中的使用率值適用於磁碟區移動到的目標Aggregate。




