---
permalink: online-help/reference-aggregate-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: Aggregate的「組態/健全狀況臨界值」頁面可讓您設定受監控之Aggregate的全域健全狀況臨界值。全域設定選項時、會修改所有物件的預設值。不過、如果物件層級的預設值已變更、則不會修改全域值。 
---
= Aggregate的組態/健全狀況臨界值頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aggregate的「組態/健全狀況臨界值」頁面可讓您設定受監控之Aggregate的全域健全狀況臨界值。全域設定選項時、會修改所有物件的預設值。不過、如果物件層級的預設值已變更、則不會修改全域值。

您必須OnCommand 具備「管理員」或「儲存管理員」角色。

當超過臨界值時、就會產生事件。您可以針對此類事件採取修正行動。

臨界值不適用於節點的根Aggregate。

您可以設定下列項目的Aggregate健全狀況臨界值：容量、Aggregate成長及Aggregate Snapshot複本。



== 容量區域

「容量」區域可讓您設定下列Aggregate容量臨界值條件。請注意、如果在位於集合體上的磁碟區上啟用「自動擴充」、則會根據自動擴充所設定的最大磁碟區大小（而非原始磁碟區大小）、將Aggregate容量臨界值視為違反。

* *空間幾乎已滿*
+
指定將Aggregate視為接近完整的百分比：

+
** 預設值：80%
+
此臨界值的值必須低於管理伺服器產生事件之Aggregate完整臨界值的值。

** 產生的事件：Aggregate幾乎已滿
** 事件嚴重性：警告


* *空間已滿*
+
指定將Aggregate視為完整的百分比：

+
** 預設值：90%
** 產生的事件：Aggregate已滿
** 事件嚴重性：錯誤


* *幾乎過度使用*
+
指定將Aggregate視為幾乎過度委派的百分比：

+
** 預設值：95%
+
此臨界值的值必須低於管理伺服器產生事件的Aggregate Over提交 完整臨界值的值。

** 產生的事件：Aggregate幾乎過度使用
** 事件嚴重性：警告


* *過度使用*
+
指定將Aggregate視為過度委派的百分比：

+
** 預設值：100%
** 產生的事件：Aggregate過度委派
** 事件嚴重性：錯誤


* *直到完整日*
+
指定集合體達到完整容量之前的剩餘天數：

+
** 預設值：7.
** 產生的事件：累積天數直到完整為止
** 事件嚴重性：錯誤






== 成長領域

成長區可讓您設定下列臨界值條件、以利集合體成長：

* *成長率*
+
指定在系統產生Aggregate成長率異常事件之前、將Aggregate成長率視為正常的百分比：

+
** 預設值：1%
** 產生的事件：Aggregate成長率異常
** 事件嚴重性：警告


* *成長率敏感度*
+
指定套用至集合體成長率標準差的因素。如果成長率超過計入的標準差、就會產生集合體成長率異常事件。

+
成長率敏感度的值越低、表示Aggregate對於成長率的變化非常敏感。成長率敏感度的範圍為1到5。

+
** 預設值：2.


+
[NOTE]
====
如果您在全域臨界值層級修改Aggregate的成長率敏感度、則變更也會套用至全域臨界值層級之Volume的成長率敏感度。

====




== Snapshot複本區域

Snapshot Copies區域可讓您設定下列Snapshot Reserve臨界值條件：

* * Snapshot保留已滿*
+
指定集合體已耗用所有保留給Snapshot複本的空間的百分比：

+
** 預設值：90%
** 產生的事件：Aggregate Snapshot Reserve已滿
** 事件嚴重性：警告






== 命令按鈕

* *還原為原廠預設值*
+
可讓您將組態設定還原為原廠預設值。

* *儲存*
+
儲存所選選項的組態設定。


