---
permalink: online-help/reference-management-groups-page.html 
sidebar: sidebar 
keywords:  
summary: 「管理/群組」頁面可讓您在Unified Manager中建立群組、輕鬆管理儲存物件。群組是儲存物件（叢集、磁碟區和SVMs）的動態集合、由您為群組建立的群組規則定義。 
---
= 「管理/群組」頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「管理/群組」頁面可讓您在Unified Manager中建立群組、輕鬆管理儲存物件。群組是儲存物件（叢集、磁碟區和SVM）的動態集合、是由您為群組建立的群組規則所定義。

「管理/群組」頁面包含可讓您新增、刪除或編輯群組、群組規則及群組動作的索引標籤。當您以操作員身分登入時、您只能擁有頁面的讀取存取權。以儲存管理員或Unified Manager管理員身分登入時、您可以存取每個索引標籤中的「新增」、「編輯」或「刪除」按鈕。



== 群組索引標籤

「群組」索引標籤會顯示您所建立群組的名稱和說明。您可以執行新增、編輯或刪除群組等工作。此索引標籤也會顯示與群組相關聯的群組規則和群組動作數目、群組中的叢集數目、SVM和磁碟區數目。



== 命令按鈕

* *新增*
+
顯示「新增群組」對話方塊、可讓您新增群組、並提供群組的名稱和說明。

+
您也可以稍後將群組規則套用至群組、以納入儲存物件。

* *編輯*
+
顯示「編輯群組」對話方塊、可讓您編輯所選群組的名稱和說明。

* *刪除*
+
刪除選取的群組。





== 清單檢視

清單檢視會以表格格式顯示您在Unified Manager中建立的群組。您可以使用欄篩選來自訂顯示的資料。依預設、清單會依群組名稱排序。

* *名稱*
+
顯示群組名稱。

* *說明*
+
顯示群組的說明。

* *相關規定*
+
顯示新增至群組的規則數目。

* *相關行動*
+
顯示新增至群組的群組動作數目。

* *適用的叢集*
+
顯示群組中包含的叢集數目。

* *適用的SVMS*
+
顯示群組中包含的SVM數量。

* *適用的Volume *
+
顯示包含在群組中的磁碟區數目。





== 群組規則索引標籤

「群組規則」索引標籤會顯示您為包含儲存物件的群組所建立的群組規則。您可以執行新增、編輯或刪除群組規則等工作。此索引標籤也會顯示建立群組規則的群組名稱、以及套用規則的儲存物件。您也可以檢視符合群組規則的儲存物件數目。



== 命令按鈕

* *新增*
+
顯示「新增群組規則」對話方塊、可讓您為儲存物件建立群組規則。

* *編輯*
+
顯示「編輯群組規則」對話方塊、可讓您重新設定先前設定的群組規則。

* *刪除*
+
刪除選取的群組規則。





== 清單檢視

清單檢視會以表格格式顯示您為特定儲存物件（叢集、磁碟區或SVM）所建立的群組規則、以及符合所定義群組規則的儲存物件計數。

* *名稱*
+
顯示規則名稱。

* *關聯的群組*
+
顯示已定義群組規則的群組名稱。

* *目標物件類型*
+
顯示套用群組規則的儲存物件類型。

* *適用對象*
+
根據群組規則顯示群組中包含的儲存物件計數。





== 群組動作索引標籤

「群組動作」索引標籤會顯示您為群組定義的群組動作名稱和類型。您可以執行新增、編輯、刪除或重新排列群組動作等工作。索引標籤也會顯示套用群組動作的群組名稱。



== 命令按鈕

* *新增*
+
顯示「新增動作」對話方塊、可讓您為一組儲存物件建立群組動作。例如、您可以設定群組中儲存物件的臨界值層級。

* *編輯*
+
顯示「編輯動作」對話方塊、可讓您重新設定先前設定的群組動作。

* *刪除*
+
刪除選取的群組動作。

* *重新排序*
+
顯示重新排列群組動作對話方塊、重新排列群組動作的順序。





== 清單檢視

清單檢視會以表格格式顯示您為Unified Manager伺服器中的群組所建立的群組動作。您可以使用欄篩選來自訂顯示的資料。

* *排名*
+
顯示要套用至群組中儲存物件的群組動作順序。

* *名稱*
+
顯示群組動作的名稱。

* *關聯的群組*
+
顯示已定義群組動作的群組名稱。

* *行動類型*
+
顯示可對群組中的儲存物件執行的群組動作類型。

+
您無法為群組建立相同動作類型的多個群組動作。例如、您可以建立群組動作來設定群組的Volume臨界值。不過、您無法為同一個群組建立另一個群組動作來變更Volume臨界值。

* *說明*
+
顯示群組動作的說明。


