---
permalink: online-help/reference-node-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: 使用「效能/節點資訊」頁面可檢視節點的實體和邏輯屬性清單。這些資訊可能有助於回答效能相關問題。 
---
= 效能/節點資訊頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用「效能/節點資訊」頁面可檢視節點的實體和邏輯屬性清單。這些資訊可能有助於回答效能相關問題。



== 節點屬性

* * IP位址*
+
節點管理LIF的IPV4或IPv6位址。

* * FQDN *
+
節點管理LIF的完整網域名稱（FQDN）。

* *作業系統版本*
+
安裝在節點上的版本的功能ONTAP 。

* *型號/系列*
+
節點的平台型號。

* *容量（可用/總計）*
+
節點可用的總儲存容量（以GB為單位）、以及目前可用的儲存容量。

* *叢集*
+
此節點所屬的叢集名稱。您可以按一下名稱以顯示叢集詳細資料的「Performance / Cluster Explorer（效能/叢集資源管理器）」頁面。

* * HA合作夥伴*
+
HA合作夥伴節點的名稱（若適用）。您可以按一下名稱、在「Performance / Node Explorer（效能/節點資源管理器）」頁面中顯示合作夥伴節點詳細資料。

* *集合體*
+
此節點上的集合體數目。您可以按一下數字、在「效能/集合體庫存」頁面中顯示集合體。

+
[NOTE]
====
此處列出的數字可能與「效能/集合體庫存」頁面中的數字不符、因為庫存頁面不含根集合體。

====
* *連接埠*
+
此節點上的連接埠數目。您可以按一下號碼、在「效能/連接埠庫存」頁面中顯示連接埠。

+
[NOTE]
====
此處列出的數字可能與「效能/連接埠庫存」頁面中的數字不符、因為庫存頁面不含節點管理連接埠。

====
* *聯絡人/地點*
+
如果可用、則此節點的相關聯絡管理員名稱、以及節點的位置。

* 核心數/速度*
+
如果可用、控制器上的CPU核心數目、以及CPU核心的速度。

* * RAM*
+
控制器上可用的總記憶體容量（若有）。





== Flash裝置

[NOTE]
====
Flash Cache資料僅會針對節點顯示、而且只有在節點中安裝Flash Cache模組時才會顯示。

====
* *插槽編號*
+
安裝Flash Cache模組的插槽編號。

* *狀態*
+
模組的作業狀態。有效值：

+
** 線上
** 離線失敗
** 離線臨界值


* *型號/系列*
+
模組的型號。

* *韌體修訂版*
+
安裝在模組上的韌體版本。

* *容量*
+
已安裝Flash Cache模組的大小。


