---
permalink: online-help/reference-rules-to-generate-user-and-group-quota-email-address-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 「產生使用者和群組配額的規則電子郵件地址」頁面可讓您建立規則、根據與叢集、SVM、磁碟區、qtree、使用者、 或使用者群組。當超出配額時、系統會將通知傳送至指定的電子郵件地址。 
---
= 產生使用者和群組配額電子郵件地址頁面的規則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「產生使用者和群組配額的規則電子郵件地址」頁面可讓您建立規則、根據與叢集、SVM、磁碟區、qtree、使用者、 或使用者群組。當超出配額時、系統會將通知傳送至指定的電子郵件地址。



== 規則區域

您必須定義配額電子郵件地址的規則。您也可以新增註解來說明規則。



== 如何定義規則

您必須依照您要執行的順序輸入規則。如果符合第一條規則的條件、則會根據此規則產生電子郵件地址。如果不符合準則、則會考量下一個規則的準則、依此類推。每一行都會列出不同的規則。預設規則是清單中的最後一個規則。您可以變更規則的優先順序。不過、您無法變更預設規則的順序。

例如、如果您想要使用電子郵件地址qtree1@xyz.com接收有關qtre1配額外洩的通知、並針對所有其他qtree使用電子郵件地址admin@xyz.com、則必須依照下列順序列出規則：

* 如果（$qtree ='qtree1'）、則qtree1@xyz.com
* 如果（$qtree =*）、則admin@xyz.com


如果您指定的規則沒有符合任何條件、則會使用預設規則：

如果（$user_OR_group =*）、則$user_OR_group @$domain

如果有多個使用者具有相同的配額、則使用者名稱會顯示為以逗號分隔的值、且這些規則不適用於配額。



== 新增留言的方式

您可以新增註解來說明規則。您應該在每個留言開始時使用#、每一行都會列出個別的留言。



== 規則語法

規則的語法必須是下列其中一項：

* 如果（_validvariable**operer_*）、則_emailID_@_domain_
+
`if` 是關鍵字、且為小寫。運算子是=。電子郵件ID可以包含任何字元、有效變數$user_or_group、$useror、$group、或任意字元與有效變數$user_or_group、$useror或$group的組合。網域名稱可以包含任何字元、有效變數$domain,或是任何字元與有效變數$domain.有效的變數可以是大寫或小寫、但不能同時是兩者的組合。例如、$DOMAINA和$DOMAINA均有效、但$Domain不是有效的變數。

* 如果（_validvariable**operer_'_string_'）、則_emailID_@_domain__
+
`if` 為關鍵字且為小寫。操作者可以是 `contains` 或=。電子郵件ID可以包含任何字元、有效變數$user_or_group、$useror、$group、或任意字元與有效變數$user_or_group、$useror或$group的組合。網域名稱可以包含任何字元、有效變數$domain,或是任何字元與有效變數$domain.有效的變數可以是大寫或小寫、但不能同時是兩者的組合。例如、$DOMAINA和$DOMAINA均有效、但$Domain不是有效的變數。





== 命令按鈕

命令按鈕可讓您儲存、驗證或取消建立的規則：

* *驗證*
+
驗證所建立規則的語法。如果驗證期間發生錯誤、則會顯示產生錯誤的規則及錯誤訊息。

* *還原為原廠預設值*
+
可讓您將位址規則還原為原廠預設值。

* *儲存*
+
驗證規則的語法、並在沒有錯誤時儲存規則。如果驗證期間發生錯誤、則會顯示產生錯誤的規則及錯誤訊息。


