---
permalink: online-help/reference-capacity-all-volumes-view.html 
sidebar: sidebar 
keywords:  
summary: 「健全狀況/磁碟區容量與使用率」頁面可讓您檢視叢集中磁碟區容量與使用率的相關資訊。此資訊可讓您瞭解可能的容量風險、並檢視已設定、已使用及未使用的Volume容量。此外、這些資訊也能協助您做出有關啟用空間節約功能（例如重複資料刪除和精簡配置）的決策。 
---
= 健全狀況/磁碟區容量與使用率頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「健全狀況/磁碟區容量與使用率」頁面可讓您檢視叢集中磁碟區容量與使用率的相關資訊。此資訊可讓您瞭解可能的容量風險、並檢視已設定、已使用及未使用的Volume容量。此外、這些資訊也能協助您做出有關啟用空間節約功能（例如重複資料刪除和精簡配置）的決策。

使用*匯出*按鈕、將所有受監控磁碟區的詳細資料匯出為以逗號分隔的值 (`.csv`）檔案。

* *叢集*
+
叢集名稱。

* * SVM*
+
包含磁碟區的儲存虛擬機器（SVM）名稱。

* * Volume *
+
Volume名稱。

* *總資料容量*
+
Volume中的總資料容量（已使用及可用）。

* *已用資料容量*
+
Volume中使用的資料容量。

* *已用資料%*
+
以百分比表示Volume中已使用的資料。

* *可用的資料容量*
+
Volume中的可用資料容量。

* *可用資料%*
+
磁碟區中可用的資料容量、以百分比表示。

* *每日成長率%*
+
每24小時在磁碟區內發生的成長率。

* *天滿*
+
Volume達到完整容量之前的預估剩餘天數。

* *空間完整臨界值%*
+
被視為已滿的磁碟區所使用的空間百分比。

* *空間接近完整臨界值%*
+
在被視為幾乎已滿的磁碟區中所使用的空間百分比。

* *成長率臨界值%*
+
在系統產生Volume成長率異常事件之前、被視為正常的Volume成長率。

* *成長率敏感度臨界值*
+
套用至Volume成長率標準差的因素。如果成長率超過計入的標準差、就會產生Volume成長率異常事件。

* *直到完整臨界值的天數*
+
達到完整容量之前的剩餘天數。

* * Snapshot溢位%*
+
Snapshot複本使用的資料空間百分比。

* * Snapshot保留已用容量*
+
Volume中Snapshot複本使用的空間量。

* * Snapshot保留已使用%*
+
磁碟區中Snapshot複本使用的空間量、以百分比表示。

* * Snapshot保留可用容量*
+
磁碟區中Snapshot複本的可用空間量。

* * Snapshot保留可用%*
+
磁碟區中Snapshot複本可用空間的百分比。

* * Snapshot保留總容量*
+
顯示磁碟區中的Snapshot複本總容量。

* * Snapshot複本保留完整臨界值%*
+
保留給Snapshot複本的空間被視為已滿的百分比。

* * Snapshot複本計數臨界值*
+
磁碟區上的Snapshot複本數量被視為太多。

* * Snapshot會複製數天直到完整臨界值*
+
保留給Snapshot複本的空間達到完整容量之前的剩餘天數。

* * inode數量*
+
Volume中的inode數。

* * inode使用率%*
+
磁碟區中使用的inode空間百分比。

* * inode完整臨界值%*
+
將某個Volume視為已使用其所有inode的百分比。

* *幾乎完全臨界值為%*的inode
+
將某個Volume視為已消耗其大部分inode的百分比。

* *配額已認可容量*
+
保留給磁碟區中配額的空間。

* *配額過度委派容量*
+
系統產生「Volume配額過度使用」事件之前、可用於配額的空間量。

* *配額過度使用臨界值%*
+
磁碟區上用於配額的空間被視為過度使用的百分比。

* *配額接近過度使用臨界值%*
+
磁碟區上用於配額的空間被視為幾乎過度使用的百分比。

* * Snapshot自動刪除*
+
是否啟用或停用自動刪除Snapshot複本。

* *重複資料刪除*
+
是否為磁碟區啟用或停用重複資料刪除。

* *重複資料刪除空間節約效益*
+
使用重複資料刪除技術、在磁碟區中節省的空間量。

* *壓縮*
+
是啟用或停用磁碟區的壓縮。

* *壓縮空間節約效益*
+
使用壓縮在磁碟區中儲存的空間量。

* *快取原則*
+
與所選磁碟區相關聯的快取原則。

+
此原則提供有關如何為磁碟區進行Flash Pool快取的資訊。如需快取原則的詳細資訊、請參閱健全狀況/磁碟區目錄頁面。

* *快取保留優先順序*
+
用於保留快取集區的優先順序。

* *精簡配置*
+
是否為所選磁碟區設定空間保證。有效值為「是」和「否」

* *自動擴充*
+
當磁碟區空間不足時、它是否會自動增加大小。

* *空間保證*
+
與磁碟區相關的儲存保證選項。

* *保護角色*
+
為磁碟區設定的保護角色。

* *州*
+
正在匯出的Volume狀態。

* *《類型*》SnapLock
+
Volume是SnapLock 指不屬於SnapLock或不屬於SnapLock Volume的磁碟區。

* *《終止日期*》SnapLock
+
The不再是截止日期SnapLock 。

* *分層政策*
+
為磁碟區設定的分層原則。僅在部署於啟用FabricPool的Aggregate時有效。


