---
permalink: online-help/reference-initialize-update-relationship-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 「初始化/更新」對話方塊可讓您針對新的保護關係執行首次基準傳輸、或是在關係已初始化且您想要執行手動、非計畫性的遞增更新時更新關係。 
---
= 初始化/更新對話方塊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「初始化/更新」對話方塊可讓您針對新的保護關係執行首次基準傳輸、或是在關係已初始化且您想要執行手動、非計畫性的遞增更新時更新關係。



== 傳輸選項索引標籤

「傳輸選項」索引標籤可讓您變更傳輸的初始化優先順序、以及變更傳輸期間使用的頻寬。

* *傳輸優先順序*
+
執行傳輸的優先順序。您可以選取「正常」或「低」。與指定一般傳輸優先順序的原則之間的關係、會在指定低傳輸優先順序的原則之前執行。依預設會選取「正常」。

* *最大傳輸率*
+
指定透過網路在叢集之間傳輸資料的最大速率。如果您選擇不使用最大傳輸率、則關聯之間的基礎傳輸不受限制。但是、如果您執行ONTAP 的是Sing 8.2、而且主要叢集和次要叢集相同、則會忽略此設定。如果您選取多個具有不同最大傳輸速率的關聯、可以指定下列其中一個最大傳輸速率設定：

+
** 使用在個別關係設定或編輯期間指定的值
+
選取此選項時、初始化和更新作業會使用每個關係建立或編輯時指定的最大傳輸率。只有在初始化或更新具有不同傳輸率的多個關聯時、才能使用此欄位。

** 無限
+
表示在關係之間傳輸時沒有頻寬限制。只有在初始化或更新具有不同傳輸率的多個關聯時、才能使用此欄位。

** 將頻寬限制為
+
選取此選項時、網路頻寬會限制為您指定的值。您可以輸入數值、然後選取每秒KB數（KB）、每秒MB數（Mbps）、每秒GB數（Gbps）或每秒TB數（Tbps）。您指定的最大傳輸率必須大於1 KB且小於4 Tbps。







== 來源Snapshot複本索引標籤

「來源Snapshot複本」標籤會顯示用於基礎傳輸之來源Snapshot複本的下列資訊：

* *來源Volume *
+
顯示對應來源Volume的名稱。

* *目的地Volume *
+
顯示所選目的地磁碟區的名稱。

* *來源類型*
+
顯示Volume類型。類型可以是讀取/寫入或資料保護。

* * Snapshot複製*
+
顯示用於資料傳輸的Snapshot複本。按一下「Snapshot複本」值會顯示「選取來源Snapshot複本」對話方塊、您可以在其中選取特定的Snapshot複本以進行傳輸、視您的保護關係類型和執行的作業而定。資料保護類型來源無法使用指定不同Snapshot複本的選項。





== 命令按鈕

命令按鈕可讓您執行下列工作：

* *取消*
+
捨棄您的選擇並關閉「初始化/更新」對話方塊。

* *提交*
+
儲存您的選擇並開始初始化或更新工作。


