---
permalink: online-help/reference-qtree-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: Qtree容量與使用率報告可讓您分析系統qtree的容量與使用率、以瞭解由於叢集容量減少而可能發生的風險。 
---
= qtree容量與使用率報告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Qtree容量與使用率報告可讓您分析系統qtree的容量與使用率、以瞭解由於叢集容量減少而可能發生的風險。



== qtree容量與使用率報告表格檢視

* *叢集*
+
顯示包含qtree的叢集名稱。

* *儲存虛擬機器*
+
顯示包含qtree的儲存虛擬機器（SVM）名稱。

* * Volume *
+
顯示包含qtree的磁碟區名稱。

* * Qtree *
+
顯示qtree的名稱。

* *配額類型*
+
指定配額是用於使用者、使用者群組或qtree。

* *使用者或群組*
+
顯示使用者或使用者群組的名稱。每個使用者和使用者群組都會有多列。當配額類型為qtree時、會顯示_not applicable _。如果未設定配額、則該欄為空白。

* *使用磁碟%*
+
顯示所用磁碟空間的百分比。如果設定了磁碟硬體限制、此值會根據磁碟硬體限制而定。如果配額設定沒有磁碟硬體限制、則此值會根據磁碟區資料空間而定。如果未設定配額、或qtree所屬的磁碟區上的配額已關閉、則會顯示_not applicable _。

* *磁碟硬碟限制*
+
顯示配置給qtree的磁碟空間上限。當達到此限制且不允許進一步寫入磁碟時、Unified Manager會產生重大事件。如果配額設定為無磁碟硬體限制、如果未設定配額、或qtree所屬的磁碟區上的配額已關閉、則該值會顯示為_Unlimit_。

* *磁碟軟體限制*
+
顯示在產生警告事件之前、已配置給qtree的磁碟空間。如果配額設定沒有磁碟軟體限制、配額未設定、或配額在qtree所屬的磁碟區上為關閉、則該值會顯示為_Unlimit_。

* *使用檔案%*
+
顯示qtree中使用的檔案百分比。如果設定了檔案硬限制、此值會根據檔案硬限制而定。如果未設定配額、未設定檔案硬限制的配額、或qtree所屬的磁碟區上的配額已關閉、則該值會顯示為_not applicable。

* *檔案硬限制*
+
顯示qtree上允許的檔案數量硬限制。如果配額設定沒有檔案硬限制、配額未設定、或配額在qtree所屬的磁碟區上為關閉、則該值會顯示為_Unlimit_。

* *檔案軟限制*
+
顯示qtree上允許的檔案數量軟限制。如果配額設定沒有檔案軟體限制、配額未設定、或配額在qtree所屬的磁碟區上為關閉、則該值會顯示為_Unlimit_。


