---
permalink: online-help/reference-event-details-page.html 
sidebar: sidebar 
keywords:  
summary: 從「事件詳細資料」頁面、您可以檢視所選事件的詳細資料、例如事件嚴重性、影響層級、影響區域及事件來源。您也可以檢視有關可能修正的其他資訊、以解決此問題。 
---
= 活動詳細資料頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從「事件詳細資料」頁面、您可以檢視所選事件的詳細資料、例如事件嚴重性、影響層級、影響區域及事件來源。您也可以檢視有關可能修正的其他資訊、以解決此問題。

* *活動名稱*
+
事件名稱和事件上次出現的時間。

+
對於非效能事件、當事件處於「New（新增）」或「Known（已確認）」狀態時、不會知道最後看到的資訊、因此會隱藏。

* *事件說明*
+
活動的簡短說明。

+
在某些情況下、事件說明會提供觸發事件的原因。

* *元件爭用中*
+
對於動態效能事件、本節會顯示代表叢集邏輯和實體元件的圖示。如果元件發生爭用、其圖示會圈選並反白顯示為紅色。

+
可能會顯示下列元件：

+
** *網路*
+
代表iSCSI傳輸協定或叢集光纖通道（FC）傳輸協定所發出的I/O要求等待時間。等待時間是指在叢集回應I/O要求之前、等待iSCSI Ready to Transfer（R2T）或FCP Transfer Ready（XFER_RDY）交易完成所花費的時間。如果網路元件發生爭用、表示區塊傳輸協定層的等待時間過長、會影響一或多個工作負載的延遲。

** *網路處理*
+
代表叢集內與傳輸協定層和叢集之間I/O處理相關的軟體元件。在偵測到事件之後、處理網路處理的節點可能已經變更。如果網路處理元件發生爭用、表示網路處理節點的高使用率會影響一或多個工作負載的延遲。

** * QoS原則*
+
代表工作負載所屬的儲存服務品質（QoS）原則群組。如果原則群組元件發生爭用、表示原則群組中的所有工作負載都會受到設定的處理量限制所限制、這會影響其中一或多個工作負載的延遲。

** *叢集互連*
+
代表叢集節點實體連接的纜線和介面卡。如果叢集互連元件發生爭用、表示叢集互連的I/O要求等待時間過長、會影響一或多個工作負載的延遲。

** *資料處理*
+
代表叢集內與叢集與包含工作負載的儲存Aggregate之間I/O處理相關的軟體元件。自偵測到事件後、處理資料的節點可能已變更。如果資料處理元件發生爭用、表示資料處理節點的高使用率會影響一或多個工作負載的延遲。

** *《資源*》MetroCluster
+
代表MetroCluster 用MetroCluster 作鏡射資料的各種資源、包括NVRAM和交換器間連結（ISL）、這些資源用於鏡射整個叢集之間的資料。如果存在爭奪、表示來自本機叢集上工作負載的高寫入處理量、或是連結健全狀況問題會影響本機叢集上一或多個工作負載的延遲。MetroCluster如果叢集並非MetroCluster 採用E32組態、則不會顯示此圖示。

** * Aggregate或SSD Aggregate Ops *
+
代表工作負載執行所在的儲存Aggregate。如果Aggregate元件發生爭用、表示Aggregate上的高使用率會影響一或多個工作負載的延遲。集合體由所有HDD組成、或混合使用HDD和SSD（Flash Pool Aggregate）。「SSD Aggregate」（「SD Aggregate」）包含所有SSD（All Flash Aggregate）、或是混合使用SSD和雲端層（FabricPool a Sd Aggregate）。

** *雲端延遲*
+
代表叢集內與叢集與雲端層之間I/O處理相關的軟體元件、以儲存使用者資料。如果雲端延遲元件發生爭用、表示來自雲端層上裝載磁碟區的大量讀取內容、會影響一或多個工作負載的延遲。

** *同步SnapMirror *
+
代表叢集中的軟體元件、該元件會以SnapMirror同步關係、將使用者資料從主要磁碟區複寫到次要磁碟區。如果同步SnapMirror元件發生爭用、表示SnapMirror同步作業的活動會影響一或多個工作負載的延遲。





其他主題將說明「事件資訊」、「系統診斷」及「建議動作」等區段。



== 命令按鈕

命令按鈕可讓您執行下列工作：

* *附註圖示*
+
可讓您新增或更新事件的相關附註、並檢閱其他使用者留下的所有附註。



*動作功能表*

* *指派給我*
+
將事件指派給您。

* *指派給其他人*
+
開啟「指派擁有者」對話方塊、可讓您指派或重新指派事件給其他使用者。

+
當您將事件指派給使用者時、系統會在所選事件的事件清單中新增使用者名稱和指派事件的時間。

+
您也可以將擁有權欄位保留空白、以取消指派事件。

* *認知*
+
確認所選的事件、以免您繼續收到重複警示通知。

+
當您確認某個事件時、您的使用者名稱和您確認該事件的時間會新增至所選事件的事件清單（確認者）。當您確認某個事件時、您必須負責管理該事件。

* *標示為已解決*
+
可讓您將事件狀態變更為「已解決」。

+
解決事件時、您的使用者名稱和解決事件的時間會新增至所選事件的事件清單（解決者）。針對事件採取修正行動之後、您必須將事件標示為「已解決」。

* *新增警示*
+
顯示「新增警示」對話方塊、可讓您新增所選事件的警示。


