---
permalink: online-help/reference-user-defined-threshold-policies-page-opm.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用「組態/效能臨界值」頁面來檢視所有目前定義的效能臨界值原則。本頁也提供建立、複製、編輯及刪除臨界值原則的功能。 
---
= 「組態/效能臨界值」頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「組態/效能臨界值」頁面來檢視所有目前定義的效能臨界值原則。本頁也提供建立、複製、編輯及刪除臨界值原則的功能。

效能臨界值原則清單會依原則名稱的字母順序排序。您可以按一下欄標題、依該欄排序原則。如果您要尋找特定原則、可以使用篩選器和搜尋機制來精簡清單清單中顯示的臨界值原則清單。



== 篩選與搜尋列

「*篩選*」按鈕可讓您只顯示符合特定條件的原則、藉此精簡臨界值原則清單。

「*搜尋*」按鈕可讓您輸入完整或部分原則名稱來搜尋特定原則、以精簡清單清單中顯示的臨界值原則清單。



== 命令按鈕

* *建立*
+
建立新的效能臨界值原則。

* *複製*
+
根據您選取的原則複本建立新的效能臨界值原則。

* *編輯*
+
修改您選取的效能臨界值原則。使用原則的所有儲存物件都會更新、以使用修訂的原則。

* *刪除*
+
刪除您選取的效能臨界值原則。原則會從使用原則的所有儲存物件中移除。您可以按一下「相關聯的物件」欄中的項目、以檢視目前使用此原則的物件。





== 臨界值原則清單

* *原則名稱*
+
顯示臨界值原則的名稱。您可以將游標放在原則名稱上、以檢視原則的詳細資料。

* *說明*
+
顯示臨界值原則的簡短說明。

* *第一條件*
+
顯示臨界值原則的主要條件、包括已定義的效能計數器、警告觸發值和臨界觸發值。您可以將游標放在條件名稱上、以檢視條件的詳細資料。

* *第二條件*
+
顯示次要臨界值原則條件（若已定義）。您可以將游標放在條件名稱上、以檢視條件的詳細資料。如果未定義第二個條件、則此欄為空白。

+
[NOTE]
====
定義第二個條件時、只有在兩個條件都遭到違反時、才會產生事件。

====
* *相關物件*
+
顯示可套用臨界值原則的儲存物件類型、以及使用原則的物件數目。此欄位為空白、直到您將原則指派給至少一個物件為止。

+
您可以按一下欄標題、依物件類型排序原則：Volume、LUN、Aggregate等。您可以按一下原則名稱、顯示目前使用臨界值原則之物件所填入的詳細目錄頁面。


