---
permalink: online-help/task-moving-workloads-to-an-aggregate-on-a-different-node.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用Unified Manager來協助識別不同節點上的Aggregate、而該節點的忙碌度低於工作負載目前執行的節點、然後將選取的磁碟區移至該Aggregate。將高效能工作負載移至較不忙碌節點上的集合體、可讓兩個節點上的工作負載更有效率地執行。 
---
= 將工作負載移至不同節點上的集合體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Unified Manager來協助識別不同節點上的Aggregate、而該節點的忙碌度低於工作負載目前執行的節點、然後將選取的磁碟區移至該Aggregate。將高效能工作負載移至較不忙碌節點上的集合體、可讓兩個節點上的工作負載更有效率地執行。



== 開始之前

* 您必須OnCommand 具備「操作員」、「資訊管理員」或「儲存管理員」角色。
* 您必須記錄目前發生效能問題的節點名稱。
* 您必須記錄節點收到效能事件的日期和時間。
* 您必須記錄事件ID、例如「'p-SDT-clus1-NOT-6982'」。
* Unified Manager必須收集並分析一個月以上的效能資料。




== 關於這項工作

這些步驟可協助您識別下列資源、以便將高效能工作負載移至使用率較低的節點：

* 相同叢集上的節點使用率較低
* 新節點上使用率最低的集合體
* 目前節點上執行效能最高的磁碟區




== 步驟

. 識別叢集中使用率最低的節點：
+
.. 在「*事件*詳細資料」頁面中、按一下節點所在叢集的名稱。
+
叢集詳細資料會顯示在「效能/叢集登陸」頁面中。

.. 在「*摘要*」頁面上、按一下「*管理物件*」窗格中的「*節點*」。
+
隨即顯示此叢集上的節點清單。

.. 按一下「*使用率*」欄、依使用率最低的節點排序節點。
+
您也可以識別擁有最大*可用容量*的節點。這會提供您可能想要將工作負載移至的潛在節點清單。

.. 記下您要將工作負載移至的節點名稱。


. 在新節點上識別使用率最低的集合體：
+
.. 在左導覽窗格中、按一下*效能*>*集合體*。
+
隨即顯示「效能/集合體」頁面。

.. 按一下「*篩選*」、從左下拉式功能表中選取「*節點*」、在文字欄位中輸入節點名稱、然後按一下「*套用篩選*」。
+
效能/集合體會與此節點上可用的集合體清單一起重新顯示。

.. 按一下「*使用率*」欄、依使用率最低的情況來排序集合體。
+
您也可以識別擁有最大*可用容量*的集合體。這會提供您可能想要將工作負載移至的潛在集合體清單。

.. 記下您要將工作負載移至的Aggregate名稱。


. 從收到事件的節點識別高效能工作負載：
+
.. 返回活動的*事件*詳細資料頁面。
.. 在*「受影響的磁碟區*」欄位中、按一下磁碟區數量的連結。
+
「效能/磁碟區」頁面會顯示該節點上已篩選的磁碟區清單。

.. 按一下*總容量*欄、依最大配置空間排序磁碟區。
+
這會提供您可能想要移動的潛在磁碟區清單。

.. 記下您要移動的磁碟區名稱、以及這些磁碟區目前所在的集合體名稱。


. 將磁碟區移至新節點上識別為使用率低的集合體。
+
您可以使用OnCommand 下列OnCommand Workflow Automation 工具來執行「移動」作業：《系統管理程式》、《VMware指令集》、ONTAP 《VMware指令集》或《VMware指令集》。





== 完成後

幾天後、檢查您是否從這個節點或Aggregate收到相同類型的事件。
