---
permalink: online-help/task-creating-a-snapmirror-relationship-with-version-flexible-replication.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用版本彈性複寫來建立SnapMirror關係。靈活版本的複寫功能可讓您實作SnapMirror保護、即使來源和目的地磁碟區是在ONTAP 不同版本的支援下執行。 
---
= 利用版本彈性複寫建立SnapMirror關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用版本彈性複寫來建立SnapMirror關係。靈活版本的複寫功能可讓您實作SnapMirror保護、即使來源和目的地磁碟區是在ONTAP 不同版本的支援下執行。



== 開始之前

* 您必須OnCommand 具備「管理員」或「儲存管理員」角色。
* 您必須設定Workflow Automation。
* 來源和目的地的SVM必須各自啟用SnapMirror授權。
* 來源和目的地的SVM必須以ONTAP 支援版本彈性複寫的版本的支援、才能在每個版本的支援下執行。




== 關於這項工作

SnapMirror搭配版本靈活的複寫功能、即使是在異質儲存環境中、也能實作SnapMirror保護功能、因為在異質儲存環境中、並非所有儲存設備都在同一個ONTAP 版本的SnapMirror下執行；不過、在SnapMirror下執行版本靈活複寫的鏡射作業、並不會像傳統區塊複寫SnapMirror一樣快速執行。



== 步驟

. 顯示您要保護的磁碟區的*組態保護*對話方塊。
+
** 如果您正在檢視「健全狀況/磁碟區詳細資料」頁面的「保護」索引標籤、請在具有您要保護之磁碟區名稱的拓撲檢視上按一下滑鼠右鍵、然後從功能表中選取「*保護*」>「* SnapMirror *」。
** 如果您正在檢視「健全狀況/磁碟區」目錄頁面、請找出您要保護的磁碟區、然後在該磁碟區上按一下滑鼠右鍵、再從功能表中選取*保護*>* SnapMirror。此時將顯示Configure Protection（配置保護）對話框。


. 按一下「* SnapMirror *」以檢視「* SnapMirror *」索引標籤。
. 完成「*組態保護*」對話方塊中的「*目的地資訊*」區域和「*關係設定*」區域。
+
如果您指定的目的地SVM是在ONTAP 比您保護的來源Volume更早版本的情況下執行、而且該舊版本支援版本彈性複寫、則此工作會自動使用版本彈性複寫來設定SnapMirror。

. 如果您指定的目的地SVM執行的ONTAP 版本與來源磁碟區相同、但您仍想設定SnapMirror使用版本彈性複寫、請按一下*進階*以啟用版本彈性複寫、然後按一下*套用*。
. 按一下「 * 套用 * 」。
+
您將返回「Health（健全狀況）/ Volume（磁碟區）」詳細資料頁面。

. 按一下「*健全狀況/磁碟區*」詳細資料頁面頂端的保護組態工作連結。
+
工作工作工作和詳細資料會顯示在「保護/工作詳細資料」頁面。

. 在「*保護/工作*詳細資料」頁面中、按一下「*重新整理*」以更新與保護組態工作相關的工作清單和工作詳細資料、並決定工作何時完成。
. 工作完成後、請按一下瀏覽器上的*上一頁*、返回*健全狀況/ Volume *詳細資料頁面。
+
新關係會顯示在「健全狀況/ Volume詳細資料」頁面的拓撲檢視中。


