---
permalink: online-help/task-creating-a-snapvault-protection-relationship-from-the-health-volumes-page.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用「Health / Volumes」（健全狀況/磁碟區）目錄頁面、為SnapVault 同一部儲存虛擬機器（SVM）上的一或多個磁碟區建立彼此的不一致關係、以便進行資料備份以保護資料。 
---
= 從SnapVault 「Health / Volumes」（健全狀況/磁碟區）目錄頁面建立不受保護的關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「Health / Volumes」（健全狀況/磁碟區）目錄頁面、為SnapVault 同一部儲存虛擬機器（SVM）上的一或多個磁碟區建立彼此之間的不一致關係、以便進行資料備份以保護資料。



== 開始之前

您必須OnCommand 具備「管理員」或「儲存管理員」角色。



== 關於這項工作

下列情況不會顯示*保護*功能表：

* 如果RBAC設定不允許此動作：例如、如果您只有操作員權限
* 當Volume ID未知時：例如、當您有叢集間關係、但尚未探索到目的地叢集時




== 步驟

. 在左導覽窗格中、按一下*健全狀況*>*磁碟區*。
. 在*健全狀況/磁碟區*目錄頁面中、以滑鼠右鍵按一下您要保護的磁碟區、然後選取*保護*。
+
或者、若要在相同的儲存虛擬機器（SVM）上建立多個保護關係、請在「Health / Volumes（健全狀況/磁碟區）」目錄頁面中選取一或多個磁碟區、然後按一下工具列上的* prot保護*。

. 從SnapVault 功能表中選取*《*》。
+
此時會啟動「設定保護」對話方塊。

. 按一下* SnapVault 《*》*《* SnapVault 》*《*》*《*》*》索引標籤、並設定次要Volume資訊。
. 按一下*進階*以視需要設定重複資料刪除、壓縮、自動擴充及空間保證、然後按一下*套用*。
. 填寫* SnapVault 目的地資訊*區域和*關係設定*區域（位於*《*》*索引標籤）。
. 按一下「 * 套用 * 」。
+
系統會將您返回「Health / Volumes」（健全狀況/磁碟區）目錄頁面。

. 按一下「*健全狀況/磁碟區*」目錄頁面頂端的保護組態工作連結。
+
如果您只建立一種保護關係、則會顯示「保護/工作詳細資料」頁面；不過、如果您建立的是多個保護關係、則會顯示與保護作業相關的所有工作的篩選清單。

. 執行下列其中一項：
+
** 如果您只有一個工作、請按一下「*重新整理*」以更新與保護組態工作相關的工作清單和工作詳細資料、並決定工作何時完成。
** 如果您有多個工作：
+
... 按一下工作清單中的工作。
... 按一下「*重新整理*」以更新與保護組態工作相關的工作清單和工作詳細資料、並判斷工作何時完成。
... 使用*上一步*按鈕返回篩選清單、並檢視其他工作。





