---
permalink: online-help/task-creating-a-snapmirror-protection-relationship-from-the-health-volumes-page.html 
sidebar: sidebar 
keywords:  
summary: 使用「健全狀況/磁碟區」目錄頁面、您可以在同一個SVM上選取多個磁碟區、一次建立多個SnapMirror保護關係。 
---
= 從「健全狀況/磁碟區」目錄頁面建立SnapMirror保護關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用「健全狀況/磁碟區」目錄頁面、您可以在同一個SVM上選取多個磁碟區、一次建立多個SnapMirror保護關係。



== 開始之前

* 您必須OnCommand 具備「管理員」或「儲存管理員」角色。
* 您必須設定Workflow Automation。




== 關於這項工作

下列情況不會顯示*保護*功能表：

* 如果RBAC設定不允許此動作：例如、如果您只有操作員權限
* 當Volume ID未知時：例如、當您有叢集間關係、但尚未探索到目的地叢集時




== 步驟

. 在「*健全狀況/磁碟區*」目錄頁面中、以滑鼠右鍵按一下您要保護的磁碟區。
+
或者、若要在同一個SVM上建立多個保護關係、請在「Health / Volumes」（健全狀況/磁碟區）目錄頁面中選取一或多個磁碟區、然後按一下工具列上的* protection *>* SnapMirror*。

+
此時將顯示Configure Protection（配置保護）對話框。

. 按一下「* SnapMirror *」以檢視「* SnapMirror *」索引標籤、並設定目的地資訊。
. 按一下*進階*以視需要設定空間保證、然後按一下*套用*。
. 完成「* SnapMirror *」標籤中的「*目的地資訊*」區域和「*關係設定*」區域。
. 按一下「 * 套用 * 」。
+
系統會將您返回「Health / Volumes」（健全狀況/磁碟區）目錄頁面。

. 按一下「*健全狀況/磁碟區*」目錄頁面頂端的保護組態工作連結。
+
如果您只建立一種保護關係、則會顯示「保護/工作詳細資料」頁面；不過、如果您建立的是多個保護關係、則會顯示與保護作業相關的所有工作清單。

. 執行下列其中一項：
+
** 如果您只有一個工作、請按一下「*重新整理*」以更新與保護組態工作相關的工作清單和工作詳細資料、並決定工作何時完成。
** 如果您有多個工作：
+
... 按一下工作清單中的工作。
... 按一下「*重新整理*」以更新與保護組態工作相關的工作清單和工作詳細資料、並判斷工作何時完成。
... 使用*上一步*按鈕返回篩選清單、並檢視其他工作。








== 結果

根據您在組態期間指定的目的地SVM或您在進階設定中啟用的選項、所產生的SnapMirror關係可能是以下幾種可能的差異之一：

* 如果您指定的目的地SVM與ONTAP 來源磁碟區的SVM執行版本相同或更新、則預設結果是區塊複寫型SnapMirror關係。
* 如果您指定的目的地SVM與ONTAP 來源Volume的相同或更新版本相同（8.3或更新版本）執行、但您在進階設定中啟用了版本彈性複寫、則會產生SnapMirror與版本彈性複寫的關係。
* 如果您指定的目的地SVM是以ONTAP 舊版的版本進行運作、或是以比來源磁碟區版本更高的版本執行、而舊版則支援版本彈性複寫、則SnapMirror與版本彈性複寫之間的關係會自動產生。

