---
permalink: online-help/task-creating-a-snapmirror-protection-relationship-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用「健全狀況/磁碟區詳細資料」頁面來建立SnapMirror關係、以便啟用資料複寫來保護資料。SnapMirror複寫可讓您在來源資料遺失時、從目的地磁碟區還原資料。 
---
= 從「健全狀況/ Volume詳細資料」頁面建立SnapMirror保護關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「健全狀況/磁碟區詳細資料」頁面來建立SnapMirror關係、以便啟用資料複寫來保護資料。SnapMirror複寫可讓您在來源資料遺失時、從目的地磁碟區還原資料。



== 開始之前

* 您必須OnCommand 具備「管理員」或「儲存管理員」角色。
* 您必須設定Workflow Automation。




== 關於這項工作

下列情況不會顯示*保護*功能表：

* 如果RBAC設定不允許此動作：例如、如果您只有操作員權限
* 如果Volume FlexGroup 是一個不確定的Volume
* 當Volume ID未知時：例如、當您有叢集間關係、但尚未探索到目的地叢集時


您最多可同時執行10個保護工作、而不會影響效能。當您同時執行11至30個工作時、可能會遇到效能影響。不建議同時執行超過30個工作。



== 步驟

. 在「*健全狀況/磁碟區*」詳細資料頁面的「*保護*」索引標籤中、在拓撲檢視中按一下滑鼠右鍵、即可看到您要保護的磁碟區名稱。
. 從功能表中選取*保護*>* SnapMirror *。
+
此時將顯示Configure Protection（配置保護）對話框。

. 按一下「* SnapMirror *」以檢視「* SnapMirror *」索引標籤、並設定目的地資訊。
. 按一下*進階*以視需要設定空間保證、然後按一下*套用*。
. 完成「*組態保護*」對話方塊中的「*目的地資訊*」區域和「*關係設定*」區域。
. 按一下「 * 套用 * 」。
+
您將返回「Health（健全狀況）/ Volume（磁碟區）」詳細資料頁面。

. 按一下「*健全狀況/磁碟區*」詳細資料頁面頂端的保護組態工作連結。
+
工作的工作和詳細資料會顯示在「保護/工作詳細資料」頁面中。

. 在「*保護/工作*詳細資料」頁面中、按一下「*重新整理*」以更新與保護組態工作相關的工作清單和工作詳細資料、並決定工作何時完成。
. 工作完成後、請按一下瀏覽器上的*上一頁*、返回*健全狀況/ Volume *詳細資料頁面。
+
新關係會顯示在「健全狀況/ Volume詳細資料」頁面的拓撲檢視中。





== 結果

根據您在組態期間指定的目的地SVM或您在進階設定中啟用的選項、所產生的SnapMirror關係可能是以下幾種可能的差異之一：

* 如果您指定的目的地SVM與ONTAP 來源磁碟區的SVM執行版本相同或更新、則預設結果是區塊複寫型SnapMirror關係。
* 如果您指定的目的地SVM與ONTAP 來源Volume的相同或更新版本（8.3或更新版本）執行、但您在進階設定中啟用了版本彈性複寫、則會產生SnapMirror與版本彈性複寫的關係。
* 如果您指定的目的地SVM是以ONTAP 舊版的支援版本為基礎執行、或是比來源磁碟區版本更高的版本、而舊版則支援版本彈性複寫、則SnapMirror與版本彈性複寫之間的關係會自動產生。

