---
permalink: online-help/task-moving-workloads-to-a-node-in-a-different-ha-pair.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用Unified Manager來協助識別不同高可用度（HA）配對中節點上的集合體、其可用效能容量比目前執行工作負載的HA配對更多。然後、您可以將選取的磁碟區移至新HA配對上的集合體。 
---
= 將工作負載移至不同HA配對中的節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Unified Manager來協助識別不同高可用度（HA）配對中節點上的集合體、其可用效能容量比目前執行工作負載的HA配對更多。然後、您可以將選取的磁碟區移至新HA配對上的集合體。



== 開始之前

* 您必須OnCommand 具備「操作員」、「資訊管理員」或「儲存管理員」角色。
* 您的叢集必須至少包含兩個HA配對
+
如果叢集中只有一個HA配對、則無法使用此補救程序。

* 您必須在HA配對中記錄目前有效能問題的兩個節點名稱。
* 您必須記錄節點收到效能事件的日期和時間。
* 您必須記錄事件ID、例如「'p-SDT-clus1-NOT-6982'」。
* Unified Manager必須收集並分析效能資料一個月以上。




== 關於這項工作

將高效能工作負載移至具有更高可用效能容量的節點上的集合體、可讓兩個節點上的工作負載更有效率地執行。此程序可協助您識別下列資源、以便將高效能工作負載移至在不同HA配對上具有更多可用效能容量的節點：

* 相同叢集上不同HA配對中的節點、可用效能容量最大
* 新節點上可用效能容量最大的集合體
* 目前節點上執行效能最高的磁碟區




== 步驟

. 識別屬於同一叢集上不同HA配對的節點：
+
.. 在「*事件詳細資料*」頁面上、按一下節點所在叢集的名稱。
+
叢集詳細資料會顯示在「效能/叢集登陸」頁面中。

.. 在「*摘要*」頁面上、按一下「*管理物件*」窗格中的「*節點*」。
+
此叢集上的節點清單會顯示在「Performance / Node」（效能/節點）頁面中。

.. 記下不同HA配對中的節點名稱、以及目前發生效能問題的HA配對。


. 在新的HA配對中找出可用效能容量最大的節點：
+
.. 在「*效能/節點*」頁面上、按一下「*使用的效能容量*」欄、即可依使用的最小百分比來排序節點。
+
這會提供您可能想要將工作負載移至的潛在節點清單。

.. 記下您要將工作負載移至的不同HA配對上的節點名稱。


. 在具有最大可用效能容量的新節點上識別Aggregate：
+
.. 在「*效能/節點*」頁面上、按一下節點。
+
節點詳細資料會顯示在「Performance / Node Explorer（效能/節點資源管理器）」頁面中。

.. 在*檢視與比較*功能表中、選取*此節點*上的集合體。
+
此節點上的集合體會顯示在網格中。

.. 按一下「*效能使用容量*」欄、依最少使用的項目來排序集合體。
+
這會提供您可能想要將工作負載移至的潛在集合體清單。

.. 記下您要將工作負載移至的Aggregate名稱。


. 從收到事件的節點識別高效能工作負載：
+
.. 返回活動的*事件*詳細資料頁面。
.. 在*「受影響的磁碟區*」欄位中、按一下第一個節點的磁碟區數目連結。
+
「效能/磁碟區」頁面會顯示該節點上已篩選的磁碟區清單。

.. 按一下*總容量*欄、依最大配置空間排序磁碟區。
+
這會提供您可能想要移動的潛在磁碟區清單。

.. 記下您要移動的磁碟區名稱、以及這些磁碟區目前所在的集合體名稱。
.. 針對此事件的第二個節點執行步驟4c和4d、以識別您想要從該節點移出的可能磁碟區。


. 將磁碟區移至您在新節點上擁有最大可用效能容量的集合體。
+
您可以使用OnCommand 下列OnCommand Workflow Automation 工具來執行「移動」作業：《系統管理程式》、《VMware指令集》、ONTAP 《VMware指令集》或《VMware指令集》。





== 完成後

幾天後、您可以檢查是否從這個節點或Aggregate收到相同類型的事件。
