---
permalink: online-help/task-initializing-or-updating-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 您可以針對新的保護關係執行首次基準傳輸、或是更新關係（如果關係已初始化且您想要執行手動、非計畫性的遞增更新）、以便立即傳輸資料。 
---
= 從「Health（健全狀況）/ Volume（磁碟區）」詳細資料頁面初始化或更新保護關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以針對新的保護關係執行首次基準傳輸、或是更新關係（如果關係已初始化且您想要執行手動、非計畫性的遞增更新）、以便立即傳輸資料。



== 開始之前

* 您必須OnCommand 具備「管理員」或「儲存管理員」角色。
* 您必須設定OnCommand Workflow Automation 好「不可用」。




== 步驟

. 在「*健全狀況/磁碟區*」詳細資料頁面的「*保護*」索引標籤中、找出您要初始化或更新的保護關係、然後在該關係上按一下滑鼠右鍵。
. 從菜單中選擇*初始化/更新*。
+
或者、從*動作*功能表中、選取*關係*>*初始化/更新*、以初始化或更新您目前正在檢視其詳細資料的關係。

+
隨即顯示「初始化/更新」對話方塊。

. 在*傳輸選項*索引標籤中、選取傳輸優先順序和最大傳輸率。
. 按一下「*來源Snapshot Copies *」；然後在「* Snapshot Copy*」欄中、按一下「* Default *」。
+
此時將顯示Select來源Snapshot Copy（選擇來源Snapshot複製）對話框。

. 如果您想要指定現有的Snapshot複本、而非傳輸預設的Snapshot複本、請按一下*現有的Snapshot Copy*、然後從清單中選取Snapshot複本。
. 按一下*提交*。
+
您會回到「初始化/更新」對話方塊。

. 如果您選取多個來源進行初始化或更新、請按一下「*預設*」、以取得您要指定現有Snapshot複本的下一個讀寫來源。
+
您無法為資料保護磁碟區選取不同的Snapshot複本。

. 按一下*提交*開始初始化或更新工作。
+
初始化或更新工作隨即啟動、您會返回「Health（健全狀況）/ Volume（磁碟區）」詳細資料頁面、頁面頂端會顯示工作連結。

. 按一下「*健全狀況/磁碟區*詳細資料」頁面上的「*檢視工作*」、即可追蹤每個初始化或更新工作的狀態。
+
畫面會顯示篩選後的工作清單。

. 按一下每個工作以查看其詳細資料。
. 按一下瀏覽器上的返回箭頭、返回*健全狀況/ Volume *詳細資料頁面。
+
當所有工作工作順利完成時、初始化或更新作業即告完成。


