---
permalink: online-help/task-moving-workloads-to-a-different-aggregate.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用Unified Manager來協助識別目前工作負載所在的Aggregate較不忙碌的Aggregate、然後將選取的磁碟區或LUN移至該Aggregate。將高效能工作負載移至較不忙碌的集合體、或是啟用Flash儲存設備的集合體、可讓工作負載更有效率地執行。 
---
= 將工作負載移至不同的Aggregate
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Unified Manager來協助識別目前工作負載所在的Aggregate較不忙碌的Aggregate、然後將選取的磁碟區或LUN移至該Aggregate。將高效能工作負載移至較不忙碌的集合體、或是啟用Flash儲存設備的集合體、可讓工作負載更有效率地執行。



== 開始之前

* 您必須OnCommand 具備「操作員」、「資訊管理員」或「儲存管理員」角色。
* 您必須記錄目前有效能問題的Aggregate名稱。
* 您必須記錄彙總接收事件的日期和時間。
* 您必須記錄事件ID、例如、「p－SDT－clus1－AG－2542」。
* Unified Manager必須收集並分析一個月以上的效能資料。




== 關於這項工作

這些步驟可協助您識別下列資源、以便將高效能工作負載移至使用率較低的Aggregate：

* 相同叢集上的集合體使用率較低
* 目前Aggregate上效能最高的磁碟區




== 步驟

. 識別叢集中使用率最低的集合體：
+
.. 在「*事件*詳細資料」頁面中、按一下集合所在叢集的名稱。
+
叢集詳細資料會顯示在「效能/叢集登陸」頁面中。

.. 在「*摘要*」頁面上、按一下「*管理物件*」窗格中的「*集合體*」。
+
隨即顯示此叢集上的集合體清單。

.. 按一下「*使用率*」欄、依使用率最低的情況來排序集合體。
+
您也可以識別擁有最大*可用容量*的集合體。這會提供您可能想要將工作負載移至的潛在集合體清單。

.. 記下您要將工作負載移至的Aggregate名稱。


. 從收到事件的集合體識別高效能磁碟區：
+
.. 按一下發生效能問題的Aggregate。
+
Aggregate詳細資料會顯示在「效能/ Aggregate Explorer」頁面中。

.. 從*時間範圍*選取器中選取*過去30天*、然後按一下*套用範圍*。
+
這可讓您檢視比預設72小時更長的效能歷程記錄期間。您想要移動一個使用大量資源且一致的磁碟區、而不只是在過去72小時內。

.. 從*檢視與比較*控制項中、選取*此Aggregate上的Volume *。
+
畫面上會顯示此集合體上的所有資料區和資料區的清單FlexVol 。FlexGroup

.. 依最高Mbps及最高IOPS排序磁碟區、即可查看效能最高的磁碟區。
.. 記下要移至不同集合體的磁碟區名稱。


. 將高效能磁碟區移至您認為使用率低的集合體。
+
您可以使用OnCommand 下列OnCommand Workflow Automation 工具來執行「移動」作業：《系統管理程式》、《VMware指令集》、ONTAP 《VMware指令集》或《VMware指令集》。





== 完成後

幾天後、檢查您是否從這個節點或Aggregate收到相同類型的事件。
