---
permalink: online-help/task-initializing-or-updating-protection-relationships.html 
sidebar: sidebar 
keywords:  
summary: 在「保護/磁碟區關係」頁面中、您可以針對新的保護關係執行首次基準傳輸、或是更新關係（如果關係已初始化且您想要執行手動、非計畫性的遞增更新以立即傳輸）。 
---
= 從「保護/磁碟區關係」頁面初始化或更新保護關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在「保護/磁碟區關係」頁面中、您可以針對新的保護關係執行首次基準傳輸、或是更新關係（如果關係已初始化且您想要執行手動、非計畫性的遞增更新以立即傳輸）。



== 開始之前

* 您必須OnCommand 具備「管理員」或「儲存管理員」角色。
* 您必須設定OnCommand Workflow Automation 好「不可用」。




== 步驟

. 在「*保護/磁碟區關係*」頁面中、以滑鼠右鍵按一下某個磁碟區、然後選取一個或多個具有您要更新或初始化關係的磁碟區、然後在工具列上按一下「*初始化/更新*」。
+
隨即顯示「初始化/更新」對話方塊。

. 在*傳輸選項*索引標籤中、選取傳輸優先順序和最大傳輸率。
. 按一下「*來源Snapshot Copies *」；然後在「* Snapshot Copy*」欄中、按一下「* Default *」。
+
此時將顯示Select來源Snapshot Copy（選擇來源Snapshot複製）對話框。

. 如果您想要指定現有的Snapshot複本、而非傳輸預設的Snapshot複本、請按一下*現有的Snapshot Copy*、然後從清單中選取Snapshot複本。
. 按一下*提交*。
+
您會回到「初始化/更新」對話方塊。

. 如果您選取多個來源進行初始化或更新、請針對您要指定現有Snapshot複本的下一個來源、按一下*預設*。
. 按一下*提交*開始初始化或更新工作。
+
初始化或更新工作隨即啟動、您會返回「保護/磁碟區關係」頁面、頁面頂端會顯示工作連結。

. 按一下「*健全狀況/磁碟區*」目錄頁上的「*檢視工作*」、即可追蹤每個初始化或更新工作的狀態。
+
畫面會顯示篩選後的工作清單。

. 按一下每個工作以查看其詳細資料。
. 按一下瀏覽器上的*上一頁*箭頭、即可返回*保護/磁碟區關係*頁面。
+
當所有工作順利完成時、即會完成初始化或更新作業。


