---
permalink: online-help/task-creating-snapmirror-relationships-with-version-flexible-replication-with-backup-option.html 
sidebar: sidebar 
keywords:  
summary: 您可以利用版本彈性的複寫與備份選項功能來建立SnapMirror關係。備份選項功能可讓您實作SnapMirror保護、並在目的地位置保留多個版本的備份複本。 
---
= 使用具有備份選項的版本彈性複寫來建立SnapMirror關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以利用版本彈性的複寫與備份選項功能來建立SnapMirror關係。備份選項功能可讓您實作SnapMirror保護、並在目的地位置保留多個版本的備份複本。



== 開始之前

* 您必須OnCommand 具備「管理員」或「儲存管理員」角色。
* 您必須設定Workflow Automation。
* 來源和目的地的SVM必須各自啟用SnapMirror授權。
* 來源和目的地的SVM都必須SnapVault 啟用不含功能的授權。
* 來源和目的地的SVM必須以ONTAP 支援版本彈性複寫的版本支援的更新版本（8.3或更新版本）來執行。




== 關於這項工作

使用備份選項功能設定SnapMirror、可讓您利用SnapMirror災難恢復功能（例如Volume容錯移轉功能）來保護資料、同時提供SnapVault 諸如多重備份複本保護等功能。



== 步驟

. 顯示您要保護的磁碟區的*組態保護*對話方塊。
+
** 如果您正在檢視「健全狀況/磁碟區詳細資料」頁面的「保護」索引標籤、請在拓撲檢視中按一下滑鼠右鍵、以檢視您要保護的磁碟區名稱、然後從功能表中選取「*保護*」>「* SnapMirror *」。
** 如果您正在檢視「健全狀況/磁碟區」目錄頁面、請找出您要保護的磁碟區、然後在該磁碟區上按一下滑鼠右鍵、再從功能表中選取*保護*>* SnapMirror。此時將顯示Configure Protection（配置保護）對話框。


. 按一下「* SnapMirror *」以檢視「* SnapMirror *」索引標籤。
. 完成「*組態保護*」對話方塊中的「*目的地資訊*」區域和「*關係設定*」區域。
. 按一下*進階*以顯示*進階目的地設定*對話方塊。
. 如果尚未選取「*版本-彈性複寫*」核取方塊、請立即選取。
. 選取「*含備份選項*」核取方塊以啟用備份選項功能、然後按一下「*套用*」。
. 按一下「 * 套用 * 」。
+
您將返回「Health（健全狀況）/ Volume（磁碟區）」詳細資料頁面。

. 按一下「*健全狀況/磁碟區*」詳細資料頁面頂端的保護組態工作連結。
+
工作工作工作和詳細資料會顯示在「保護/工作詳細資料」頁面。

. 在「*保護/工作*詳細資料」頁面中、按一下「*重新整理*」以更新與保護組態工作相關的工作清單和工作詳細資料、並決定工作何時完成。
. 工作完成後、請按一下瀏覽器上的*上一頁*、返回*健全狀況/ Volume *詳細資料頁面。
+
新關係會顯示在「健全狀況/ Volume詳細資料」頁面的拓撲檢視中。


