---
settings:
  name: OnCommand Unified Manager 9.5
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: 統一化管理程式9.5文件OnCommand
    url: "/index.html"
  - title: 版本資訊
    url: "/release-notes.html"
  - title: 開始使用
    entries:
    - title: VMware vSphere的快速入門安裝
      url: "/qsg-vapp.html"
    - title: Linux快速入門安裝
      url: "/qsg-linux.html"
    - title: Windows快速入門安裝
      url: "/qsg-windows.html"
  - section: install
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - title: 法律聲明
    url: "/legal-notices.html"
