---
permalink: performance-checker/concept-cluster-configuration-and-performance-data-collection-activity.html 
sidebar: sidebar 
keywords:  
summary: 叢集組態資料的收集時間間隔為15分鐘。例如、新增叢集之後、Unified Manager UI中會顯示叢集詳細資料需要15分鐘。此時間間隔也適用於對叢集進行變更的情況。 
---
= 叢集組態與效能資料收集活動
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
叢集組態資料的收集時間間隔為15分鐘。例如、新增叢集之後、Unified Manager UI中會顯示叢集詳細資料需要15分鐘。此時間間隔也適用於對叢集進行變更的情況。

例如、如果您將兩個新的磁碟區新增至叢集中的SVM、則會在下一個輪詢時間間隔之後、在UI中看到這些新物件、最多可達15分鐘。

Unified Manager每五分鐘從所有受監控的叢集收集一次目前的效能統計資料。它會分析這些資料、找出效能事件和潛在問題。它保留30天的五分鐘歷史效能資料、以及390天的一小時歷史效能資料。這可讓您檢視本月的非常精細的效能詳細資料、以及長達一年的一般效能趨勢。

收集輪詢會偏移數分鐘、因此不會同時傳送每個叢集的資料、這可能會影響效能。

下表說明Unified Manager執行的收集活動：

|===
| 活動 | 時間間隔 | 說明 


 a| 
效能統計資料調查
 a| 
每5分鐘
 a| 
從每個叢集收集即時效能資料。



 a| 
統計分析
 a| 
每5分鐘
 a| 
在每次統計資料輪詢之後、Unified Manager會將收集的資料與使用者定義、系統定義和動態臨界值進行比較。

如果違反任何效能臨界值、Unified Manager會產生事件並傳送電子郵件給指定的使用者（如果已設定）。



 a| 
組態輪詢
 a| 
每15分鐘
 a| 
從每個叢集收集詳細的庫存資訊、以識別所有的儲存物件（節點、SVM、Volume等）。



 a| 
摘要
 a| 
每小時
 a| 
將最新的12個5分鐘效能資料收集總結為每小時平均。

每小時平均值會用於部分UI頁面、保留390天。



 a| 
預測分析與資料剪除
 a| 
每天午夜之後
 a| 
分析叢集資料、為未來24小時的磁碟區延遲和IOPS建立動態臨界值。

從資料庫刪除任何30天之前的5分鐘效能資料。



 a| 
資料剪除
 a| 
每天上午2點之後
 a| 
從資料庫刪除任何超過390天的事件和動態臨界值。



 a| 
資料剪除
 a| 
每天上午3：30之後
 a| 
從資料庫刪除任何超過390天的一小時效能資料。

|===