---
permalink: performance-checker/concept-what-a-data-continuity-collection-cycle-is.html 
sidebar: sidebar 
keywords:  
summary: 資料持續性收集週期會擷取即時叢集效能收集週期之外的效能資料、預設每五分鐘執行一次。資料持續性集合可讓Unified Manager填補無法收集即時資料時所發生的統計資料落差。 
---
= 什麼是資料持續性收集週期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
資料持續性收集週期會擷取即時叢集效能收集週期之外的效能資料、預設每五分鐘執行一次。資料持續性集合可讓Unified Manager填補無法收集即時資料時所發生的統計資料落差。

資料持續性收集僅支援安裝ONTAP 於使用支援更新版本的軟體版本8.3.1的叢集。

Unified Manager會在發生下列事件時、針對歷史效能資料執行資料持續性收集輪詢：

* 叢集一開始會新增至Unified Manager。
+
Unified Manager會收集過去15天的歷史效能資料。這可讓您在新增叢集數小時後、檢視其兩週的歷史效能資訊。

+
此外、系統定義的臨界值事件也會在前一個期間（如果有）報告。

+
[NOTE]
====
目前未收集15天的歷史Volume統計資料。

====
* 目前的效能資料收集週期並未準時完成。
+
如果即時效能意見調查超過五分鐘的收集時間、就會啟動資料持續性收集週期、以收集該遺失的資訊。若未收集資料持續性、則會跳過下一個收集期間。

* Unified Manager已無法存取一段時間、之後又重新上線、如下所示：
+
** 它已重新啟動。
** 在軟體升級期間或建立備份檔案時、系統都會關閉。
** 網路中斷已修復。


* 叢集無法存取已有一段時間、之後會恢復連線、如下所示：
+
** 網路中斷已修復。
** 廣域網路連線緩慢、延遲了效能資料的正常收集。




資料持續性收集週期最多可收集24小時的歷史資料。如果Unified Manager停機時間超過24小時、UI頁面會出現效能資料落差。

無法同時執行資料持續性收集週期和即時資料收集週期。資料持續性收集週期必須在啟動即時效能資料收集之前完成。如果需要收集資料持續性以收集一小時以上的歷史資料、您會在效能儀表板頂端看到該叢集的橫幅訊息。
