---
permalink: performance-checker/concept-collecting-data-and-monitoring-workload-performance.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager每5分鐘收集並分析工作負載活動、以識別效能事件、並每15分鐘偵測一次組態變更。它最多可保留30天5分鐘的歷史效能和事件資料、並使用此資料預測所有受監控工作負載的預期範圍。 
---
= 收集資料並監控工作負載效能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager每5分鐘收集並分析工作負載活動、以識別效能事件、並每15分鐘偵測一次組態變更。它最多可保留30天5分鐘的歷史效能和事件資料、並使用此資料預測所有受監控工作負載的預期範圍。

[NOTE]
====
本章說明動態臨界值的運作方式、以及如何使用它們來協助監控工作負載效能。本章不適用於因使用者定義或系統定義的效能臨界值外洩所造成的統計資料或事件。

====
Unified Manager必須收集至少3天的工作負載活動、才能開始進行分析、並在「效能/磁碟區詳細資料」頁面和「事件詳細資料」頁面上顯示I/O回應時間和作業的預期範圍之前。在收集此活動時、預期範圍不會顯示工作負載活動所發生的所有變更。在收集3天的活動後、Unified Manager會調整預期範圍、每24小時於上午12：00調整一次、以反映工作負載活動的變化、並建立更準確的效能臨界值。

在Unified Manager監控磁碟區的前4天內、如果自上次資料收集後超過24小時、「效能/磁碟區詳細資料」頁面上的圖表將不會顯示該磁碟區的預期範圍。在上次收集之前偵測到的事件仍可使用。

[NOTE]
====
夏令時間（Dst）會變更系統時間、改變監控工作負載的預期效能統計範圍。Unified Manager會立即開始修正預期範圍、大約需要15天才能完成。在此期間、您可以繼續使用Unified Manager、但由於Unified Manager使用預期範圍來偵測事件、因此部分事件可能不準確。在時間變更之前偵測到的事件不受影響。手動將叢集或Unified Manager伺服器上的時間變更為較早的時間、也會影響事件分析結果。

====