---
permalink: performance-checker/concept-what-the-expected-range-of-performance-is.html 
sidebar: sidebar 
keywords:  
summary: 預期的值範圍是預測、或預測在特定時間預期的效能值上限和下限。針對工作負載延遲、較高的值會形成效能臨界值。當實際值超過效能臨界值時、Unified Manager會觸發效能事件警示。 
---
= 預期的效能範圍為何
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
預期的值範圍是預測、或預測在特定時間預期的效能值上限和下限。針對工作負載延遲、較高的值會形成效能臨界值。當實際值超過效能臨界值時、Unified Manager會觸發效能事件警示。

例如、在正常營業時間上午9：00之間下午5：00、大部分員工可能會在上午9：00之間查看電子郵件上午10：30電子郵件伺服器的需求增加、表示在此期間後端儲存設備的工作負載活動增加。員工可能會注意到電子郵件用戶端的回應時間過慢。

午餐時間為下午12：00以及下午1：00而且在工作日結束後下午5：00、大部分員工可能會離開電腦。對電子郵件伺服器的需求通常會減少、也會減少對後端儲存設備的需求。或者、也可以排程工作負載作業、例如儲存備份或掃毒、這些作業會在下午5：00之後開始並增加後端儲存設備的活動。

在數天內、工作負載活動的增加和減少、決定了預期的活動範圍、以及工作負載的上限和下限。當物件的實際工作負載活動超出上限或下限、且在一段時間內仍在邊界之外時、這可能表示物件過度使用或未充分使用。



== 預期範圍的形成方式

Unified Manager必須收集至少3天的工作負載活動、才能開始進行分析、並在GUI中顯示I/O回應時間與作業的預期範圍之前。所需的最低資料收集量並不包含工作負載活動所發生的所有變更。在收集活動的前3天之後、Unified Manager會調整預期範圍、每24小時於上午12：00調整一次、以反映工作負載活動的變化、並建立更精確的效能臨界值。

[NOTE]
====
夏令時間（Dst）會變更系統時間、改變監控工作負載的預期效能統計範圍。Unified Manager會立即開始修正預期範圍、大約需要15天才能完成。在此期間、您可以繼續使用Unified Manager、但由於Unified Manager使用預期範圍來偵測事件、因此部分事件可能不準確。在時間變更之前偵測到的事件不受影響。手動將叢集或Unified Manager伺服器上的時間變更為較早的時間、也會影響事件分析結果。

====