---
permalink: performance-checker/concept-roles-of-workloads-involved-in-a-performance-incident.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager使用角色來識別工作負載在效能事件中的參與度。角色包括受害者、牛隻和鯊魚。使用者定義的工作負載可以同時成為受害者、欺負者和鯊魚。 
---
= 效能事件所涉及的工作負載角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager使用角色來識別工作負載在效能事件中的參與度。角色包括受害者、牛隻和鯊魚。使用者定義的工作負載可以同時成為受害者、欺負者和鯊魚。

|===
| 角色 | 說明 


 a| 
受害者
 a| 
使用者定義的工作負載、其效能因過度使用叢集元件的其他工作負載（稱為bulies）而降低。只有使用者定義的工作負載會被識別為受害者。Unified Manager會根據受害者的延遲差異來識別受害者工作負載、在事件期間、實際延遲比預期的延遲範圍大幅增加。



 a| 
霸凌
 a| 
使用者定義或系統定義的工作負載、其過度使用叢集元件、導致其他工作負載（稱為「受害者」）的效能降低。Unified Manager會根據叢集元件使用量的差異來識別不正常的工作負載、在事件期間、實際使用量已大幅增加、超出預期的使用範圍。



 a| 
鯊魚
 a| 
使用者定義的工作負載、其叢集元件的使用率最高、與事件中涉及的所有工作負載相比。Unified Manager會根據事件期間使用的叢集元件來識別Shark工作負載。

|===
叢集上的工作負載可共用許多叢集元件、例如儲存Aggregate和CPU、以進行網路和資料處理。當工作負載（例如Volume）增加叢集元件的使用量、使元件無法有效率地滿足工作負載需求時、元件就會發生爭用。過度使用叢集元件的工作負載是一種不理想的情況。共享這些元件的其他工作負載、以及效能受到市場影響的工作負載、都是受害者。系統定義工作負載的活動（例如重複資料刪除或Snapshot複本）也可能升級為「霸凌」。

當Unified Manager偵測到事件時、它會識別所有相關的工作負載和叢集元件、包括導致事件的龐大工作負載、爭用的叢集元件、以及因高負荷活動增加而效能降低的受害者工作負載。

[NOTE]
====
如果Unified Manager無法辨識高效能的工作負載、它只會針對受害者工作負載和相關叢集元件發出警示。

====
Unified Manager可識別受欺負工作負載的工作負載、並識別這些相同工作負載何時會變成高負荷。工作負載本身可能是一種欺負。例如、由原則群組限制所抑制的高效能工作負載、會使原則群組中的所有工作負載受到節流、包括本身。在進行中的效能事件中、身為一名流氓或受害者的工作負載、可能會改變其角色、或不再是事件參與者。在「效能/磁碟區詳細資料」頁面的「事件清單」表格中、當所選磁碟區變更其參與者角色時、就會顯示角色變更的日期和時間。
