---
permalink: performance-checker/reference-components-of-the-node-failover-planning-page.html 
sidebar: sidebar 
keywords:  
summary: 「效能/節點容錯移轉規劃」頁面的元件會顯示在網格和比較窗格中。這些章節可讓您評估節點容錯移轉對接管節點效能的影響。 
---
= 節點容錯移轉規劃頁面的元件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「效能/節點容錯移轉規劃」頁面的元件會顯示在網格和比較窗格中。這些章節可讓您評估節點容錯移轉對接管節點效能的影響。



== 效能統計資料網格

「效能/節點容錯移轉規劃」頁面會顯示一個網格、其中包含所使用延遲、IOPS、使用率和效能容量的統計資料。

[NOTE]
====
此頁面和「效能/節點效能總管」頁面中顯示的IOPS值可能不同。

====
在網格中、每個節點都會被指派下列其中一個角色：

* 主要
+
當合作夥伴故障時接管HA合作夥伴的節點。根物件永遠是主要節點。

* 合作夥伴
+
容錯移轉案例中發生故障的節點。

* 預估接管
+
與主節點相同。此節點的效能統計資料顯示接管節點接管故障合作夥伴後的效能表現。



[NOTE]
====
雖然接管節點的工作負載相當於容錯移轉後兩個節點的合併工作負載、但預估接管節點的統計資料並非主節點和合作夥伴節點的統計資料總和。例如、如果主要節點的延遲為2毫秒/作業、而合作夥伴節點的延遲為3毫秒/作業、則預估接管節點的延遲可能為4毫秒/作業此值是Unified Manager執行的計算。

====
如果您想要成為根物件、可以按一下「合作夥伴」節點的名稱。顯示「Performance / Node Performance Explorer（效能/節點效能總管）」頁面之後、您可以按一下「*容錯移轉規劃*」索引標籤、查看此節點故障案例的效能如何變更。例如、如果Node1為主要節點、而Node2為合作夥伴節點、您可以按一下Node2將其設定為主要節點。如此一來、您就能瞭解預估效能如何隨節點故障而改變。



== 比較窗格

下列清單說明依預設在「比較」窗格中顯示的元件：

* *活動圖表*
+
它們的顯示格式與「效能/節點效能總管」頁面中的格式相同。它們僅適用於主節點。

* *計數器圖表*
+
它們會顯示網格中所示效能計數器的歷史統計資料。在每個圖表中、預估接管節點的圖表會顯示在任何特定時間發生容錯移轉時的預估效能。

+
例如、假設使用率圖表顯示估計的接管節點在上午11點的73%2月8日。如果當時發生容錯移轉、則接管節點的使用率將達到73%。

+
歷史統計資料可協助您找出啟動容錯移轉的最佳時間、將接管節點過載的可能性降至最低。只有在接管節點的預期效能可接受時、您才能排程容錯移轉。



根據預設、根物件和合作夥伴節點的統計資料都會顯示在「比較」窗格中。與「效能/節點效能總管」頁面不同、此頁面不會顯示*「新增*」按鈕、讓您新增物件以進行統計資料比較。

您可以使用與「效能/節點效能總管」頁面相同的方式自訂「比較」窗格。下列清單顯示自訂圖表的範例：

* 按一下節點名稱、即可在「計數器」圖表中顯示或隱藏節點的統計資料。
* 按一下*縮放檢視*、即可在新視窗中顯示特定計數器的詳細圖表。

