---
permalink: performance-checker/reference-types-of-performance-counter-charts.html 
sidebar: sidebar 
keywords:  
summary: 有標準效能圖表可顯示所選儲存物件的計數器值。每個明細計數器圖表都會顯示區分為讀取、寫入及其他類別的總計值。此外、某些明細計數器圖表會在「縮放」檢視中顯示圖表時、顯示其他詳細資料。 
---
= 效能對照表類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
有標準效能圖表可顯示所選儲存物件的計數器值。每個明細計數器圖表都會顯示區分為讀取、寫入及其他類別的總計值。此外、某些明細計數器圖表會在「縮放」檢視中顯示圖表時、顯示其他詳細資料。

下表顯示可用的效能計數器圖表。

|===
| 可用的圖表 | 圖表說明 


 a| 
活動
 a| 
顯示與根物件統計圖表相關的重大、錯誤、警告和資訊事件。除了效能事件之外、還會顯示健全狀況事件、以完整瞭解效能可能受到影響的原因。



 a| 
延遲-總計
 a| 
回應應用程式要求所需的毫秒數。請注意、平均延遲值為I/O加權。



 a| 
延遲-明細
 a| 
延遲總計中顯示的資訊相同、但效能資料會分成讀取、寫入和其他延遲。此圖表選項僅適用於選取的物件為SVM、節點、Aggregate、Volume、LUN、或命名空間。



 a| 
延遲：叢集元件
 a| 
「延遲總計」中顯示的資訊相同、但效能資料會依叢集元件分隔成延遲。此圖表選項僅適用於選取的物件為Volume時。



 a| 
IOPS -總計
 a| 
每秒處理的輸入/輸出作業數。



 a| 
IOPS：明細
 a| 
IOPS總計中顯示的資訊相同、但效能資料分為讀取、寫入和其他IOPS。在「縮放」檢視中顯示時、Volume圖表會顯示QoS最小和最大處理量值（若已設定ONTAP 於此）。

此圖表選項僅適用於所選物件為SVM、節點、Aggregate、Volume、LUN、 或命名空間。



 a| 
IOPS：傳輸協定
 a| 
IOPS總計中顯示的資訊相同、但效能資料會分成CIFS、NFS、FCP、NVMe及iSCSI傳輸協定流量的個別圖表。此圖表選項僅適用於選取的物件為SVM時。



 a| 
IOPS/TB -總計
 a| 
根據工作負載所耗用的總空間（以TB為單位）、每秒處理的輸入/輸出作業數。也稱為I/O密度、此計數器可測量特定儲存容量所能提供的效能。在「縮放」檢視中顯示時、Volume圖表會顯示預期QoS和尖峰處理量值（若設定ONTAP 為「支援」）。

此圖表選項僅適用於選取的物件為Volume時。



 a| 
Mbps -總計
 a| 
每秒從物件傳輸的資料MB數。



 a| 
Mbps -明細
 a| 
Mbps圖表中顯示的資訊相同、但將Mbps資料分隔成磁碟讀取、Flash Cache讀取、寫入和其他。在「縮放」檢視中顯示時、Volume圖表會顯示QoS最大處理量值（若設定ONTAP 為「QoS」）。

此圖表選項僅適用於所選物件為SVM、節點、Aggregate、Volume、LUN、 或命名空間。

[NOTE]
====
Flash Cache資料僅會針對節點顯示、而且只有在節點中安裝Flash Cache模組時才會顯示。

====


 a| 
使用的效能容量-總計
 a| 
節點或Aggregate正在使用的效能容量百分比。

[NOTE]
====
效能容量資料只有在叢集中的節點安裝ONTAP 有VMware 9.0或更新版本的軟體時才能使用。

====


 a| 
使用的效能容量-明細
 a| 
效能容量已將資料分成使用者傳輸協定和系統背景處理程序。此外、還會顯示可用的效能容量。



 a| 
可用IOPS -總計
 a| 
此物件目前可用（可用）的每秒輸入/輸出作業數。此數值是Unified Manager計算出物件可執行的IOPS總計減去目前使用的IOPS的結果。此圖表選項僅適用於選取的物件為節點或Aggregate時。

[NOTE]
====
只有在叢集中的節點安裝ONTAP 有支援更新版本的軟體時、才能使用可用的IOPS資料。

====


 a| 
使用率-總計
 a| 
使用中物件的可用資源百分比。使用率表示節點使用率、Aggregate的磁碟使用率、以及連接埠的頻寬使用率。此圖表選項僅適用於選取的物件為節點、Aggregate或連接埠時。



 a| 
快取遺失比率-總計
 a| 
從磁碟傳回而非從快取傳回的用戶端應用程式讀取要求百分比。此圖表選項僅適用於選取的物件為Volume時。

|===