---
permalink: performance-checker/reference-performance-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 本頁提供所選FlexVol 之VMware Volume FlexGroup 、VMware Volume或FlexGroup 不完整的工作負載的所有I/O活動和作業的詳細效能統計資料。您可以選取特定的時間範圍來檢視磁碟區的統計資料和事件。這些事件可識別可能影響I/O效能的效能事件和變更。 
---
= 「效能/ Volume詳細資料」頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本頁提供所選FlexVol 之VMware Volume FlexGroup 、VMware Volume或FlexGroup 不完整的工作負載的所有I/O活動和作業的詳細效能統計資料。您可以選取特定的時間範圍來檢視磁碟區的統計資料和事件。這些事件可識別可能影響I/O效能的效能事件和變更。



== 歷史資料圖表

繪製所選Volume的歷史效能分析資料。您可以按一下並拖曳滑桿來指定時間範圍。滑桿會增加和減少時間範圍。時間範圍以外的資料會呈現灰色。您可以使用圖表底部的滑桿、在歷史資料之間移動時間範圍視窗。整個頁面（包括顯示的圖表和事件）會反映時間範圍內可用的資料。Unified Manager在此頁面上保留最多30天的歷史資料。

[NOTE]
====
在歷史資料圖表中、如果您選取超過1天的時間範圍、則圖表會根據您的螢幕解析度、顯示回應時間和IOPS的最大值（天數）。

====


== 選項

* *時間選擇器*
+
指定檢視整個頁面的Volume效能統計資料的時間範圍。您可以按一下1天（* 1D*）到30天（* 30d*）、或按一下*自訂*來選取自訂範圍。對於自訂範圍、您可以選取開始和結束日期、然後按一下*更新*以更新整個頁面。

+
[NOTE]
====
如果您按一下「事件詳細資料」頁面上某個磁碟區的名稱連結來存取「效能/磁碟區詳細資料」頁面、則預設會自動選取時間範圍、例如當日之前的1天或5天。當您在歷史資料圖表中移動滑桿時、時間範圍會變更為自訂範圍、但不會選取*自訂*時間選取器。預設時間選取器仍會保持選取狀態。

====
* *將資料細分為*
+
提供您可新增至「效能/磁碟區詳細資料」頁面的圖表清單、以顯示所選磁碟區更詳細的效能統計資料。


