---
permalink: performance-checker/task-responding-to-a-system-defined-qos-policy-group-performance-event.html 
sidebar: sidebar 
keywords:  
summary: 當工作負載處理量（IOPS、IOPS/TB或MBps）超過定義ONTAP 的「QoS」原則設定、且工作負載延遲受到影響時、Unified Manager會產生QoS原則警告事件。這些系統定義的事件可在許多工作負載受到延遲影響之前、提供修正潛在效能問題的機會。 
---
= 回應QoS原則群組效能事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當工作負載處理量（IOPS、IOPS/TB或Mbps）超過定義ONTAP 的「QoS」原則設定、且工作負載延遲受到影響時、Unified Manager會產生QoS原則警告事件。這些系統定義的事件可在許多工作負載受到延遲影響之前、提供修正潛在效能問題的機會。



== 開始之前

* 您必須OnCommand 具備「操作員」、「資訊管理員」或「儲存管理員」角色。
* 必須有新的、已確認的或過時的效能事件。




== 關於這項工作

當工作負載處理量在前一小時的每個效能收集期間超過定義的QoS原則設定時、Unified Manager會針對QoS原則外洩事件產生警告事件。在每個收集期間、工作負載處理量可能只會在短時間內超過QoS臨界值、但Unified Manager只會在圖表上顯示收集期間的「平均」處理量。因此、您可能會收到QoS事件、但工作負載的處理量可能未超過圖表中所示的原則臨界值。

您可以使用System Manager或ONTAP 列舉一些指令來管理原則群組、包括下列工作：

* 為工作負載建立新的原則群組
* 新增或移除原則群組中的工作負載
* 在原則群組之間移動工作負載
* 變更原則群組的處理量限制
* 將工作負載移至不同的Aggregate或節點




== 步驟

. 顯示「*事件*」詳細資料頁面、以檢視有關事件的資訊。
. 檢閱* Description*、其中說明導致事件的臨界值外洩。
+
例如、「vol1_NFS1上的IOPS值為1、652 IOPS、已觸發警示事件來識別工作負載的潛在效能問題」、表示Volume vol1_NFS1上發生QoS最大IOPS事件。

. 請檢閱「*事件資訊*」區段、以查看事件發生時間及事件發生時間的詳細資料。
+
此外、對於共享QoS原則處理量的磁碟區或LUN、您可以看到使用最多IOPS或Mbps的前三大工作負載名稱。

. 在「*系統診斷*」區段下、檢閱兩個圖表：一個是整體平均IOPS或Mbps（視事件而定）、另一個是延遲。如此安排時、您可以看到當工作負載接近QoS上限時、哪些叢集元件最會影響延遲。
+
對於共享QoS原則事件、前三大工作負載會顯示在處理量圖表中。如果有三個以上的工作負載共用QoS原則、則會將其他工作負載新增至「other t后 的工作負載」類別。此外、延遲圖表也會顯示QoS原則中所有工作負載的平均延遲。

+
請注意、對於調適性QoS原則事件、IOPS和Mbps圖表會根據ONTAP 磁碟區大小、顯示從指派的IOPS/TB臨界值原則中轉換的IOPS或Mbps值。

. 在「*建議動作*」區段下、檢閱建議並判斷您應該執行哪些動作、以避免工作負載延遲增加。
+
如有需要、請按一下*「說明」*按鈕、以檢視您可執行的建議行動詳細資料、以嘗試解決效能事件。


