---
permalink: performance-checker/task-responding-to-a-system-defined-node-resources-overutilized-performance-event.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager會在單一節點的作業效率超出範圍時、產生過度使用的節點資源警示事件、進而可能影響工作負載延遲。這些系統定義的事件可在許多工作負載受到延遲影響之前、提供修正潛在效能問題的機會。 
---
= 回應節點資源過度使用的效能事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager會在單一節點的作業效率超出範圍時、產生過度使用的節點資源警示事件、進而可能影響工作負載延遲。這些系統定義的事件可在許多工作負載受到延遲影響之前、提供修正潛在效能問題的機會。



== 開始之前

* 您必須OnCommand 具備「操作員」、「資訊管理員」或「儲存管理員」角色。
* 必須有新的或過時的效能事件。




== 關於這項工作

Unified Manager會針對節點資源過度使用的原則外洩事件、尋找使用超過100%效能容量達30分鐘以上的節點。

您可以使用System Manager或ONTAP VMware指令來修正這類效能問題、包括下列工作：

* 建立QoS原則、並將其套用至任何過度使用系統資源的磁碟區或LUN
* 降低已套用工作負載之原則群組的QoS最大處理量限制
* 將工作負載移至不同的Aggregate或節點
* 將磁碟新增至節點、或升級至CPU速度更快、RAM更多的節點、以增加容量




== 步驟

. 顯示「*事件*」詳細資料頁面、以檢視有關事件的資訊。
. 檢閱* Description*、其中說明導致事件的臨界值外洩。
+
例如、訊息「'per.使用的容量（使用簡易性）值為139%、已觸發警示事件來識別資料處理單元中的潛在效能問題。」表示節點簡易性02上的效能容量過度使用、並影響節點效能。

. 在「*系統診斷*」區段中、檢閱三個圖表：一個是節點上使用的效能容量、一個是最重要工作負載使用的平均儲存IOPS、另一個是最重要工作負載的延遲。以這種方式安排時、您可以看到哪些工作負載是造成節點延遲的原因。
+
您可以將游標移到IOPS圖表上、檢視哪些工作負載已套用QoS原則、哪些工作負載未套用QoS原則。

. 在「*建議動作*」區段下、檢閱建議並判斷您應該執行哪些動作、以避免工作負載延遲增加。
+
如有需要、請按一下*「說明」*按鈕、以檢視您可執行的建議行動詳細資料、以嘗試解決效能事件。


