---
permalink: performance-checker/task-configuring-a-connection-between-a-unified-manager-server-and-an-external-data-provider.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager可將叢集效能資料傳送至外部伺服器。您可以指定要傳送的統計資料類型、以及資料傳送的時間間隔。 
---
= 設定從Unified Manager伺服器到外部資料供應商的連線
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager可將叢集效能資料傳送至外部伺服器。您可以指定要傳送的統計資料類型、以及資料傳送的時間間隔。



== 開始之前

* 您必須擁有授權使用者ID、才能登入Unified Manager伺服器的維護主控台。
* 您必須擁有下列外部資料提供者的相關資訊：
+
** 伺服器名稱或IP位址（IPv4或IPv6）
** 伺服器預設連接埠（若未使用預設連接埠2003）


* 您必須設定遠端伺服器和協力廠商軟體、才能從Unified Manager伺服器接收統計資料。
* 您必須知道要傳送的統計資料群組：
+
** 效能指標：效能監控統計資料
** resource_utilization：資源使用率與效能監控統計資料
** 探查：所有統計資料


* 您必須知道傳輸統計資料的時間間隔：5、10或15分鐘
+
根據預設、Unified Manager會以5分鐘的時間間隔收集統計資料。如果您將傳輸時間間隔設為10（或15）分鐘、則每次傳輸期間所傳送的資料量會比使用預設的5分鐘時間間隔大兩（或三）倍。

+
[NOTE]
====
如果您將Unified Manager效能收集時間間隔變更為10或15分鐘、則必須變更傳輸時間間隔、使其等於或大於Unified Manager收集時間間隔。

====




== 關於這項工作

您可以設定一個Unified Manager伺服器與一個外部資料提供者伺服器之間的連線。



== 步驟

. 以維護使用者身分登入Unified Manager伺服器的維護主控台。
+
此時會顯示Unified Manager維護主控台提示。

. 在維護主控台中、輸入*外部資料供應商*功能表選項的編號。
+
隨即顯示「外部伺服器連線」功能表。

. 輸入「*新增/修改伺服器連線*」功能表選項的編號。
+
此時會顯示目前的伺服器連線資訊。

. 出現提示時、輸入 `y` 以繼續。
. 出現提示時、輸入目的地伺服器的IP位址或名稱、以及伺服器連接埠資訊（如果與預設連接埠2003不同）。
. 出現提示時、輸入 `y` 以驗證您輸入的資訊是否正確。
. 按任意鍵返回「外部伺服器連線」功能表。
. 鍵入*修改伺服器組態*功能表選項的編號。
+
此時會顯示目前的伺服器組態資訊。

. 出現提示時、輸入 `y` 以繼續。
. 出現提示時、請輸入要傳送的統計資料類型、統計資料傳送時間間隔、以及是否要立即傳輸統計資料：
+
|===
| 適用於... | 輸入... 


 a| 
統計群組ID
 a| 
`0` -效能指標（預設）

`1` 資源使用率

`2` -探查



 a| 
廠商標籤
 a| 
外部伺服器上儲存統計資料的資料夾說明名稱。「'NetApp-Performance」為預設名稱、但您可以輸入其他值。

您可以使用點分表示法來定義階層式資料夾結構。例如、輸入 `stats.performance.netapp` 統計資料將位於*統計資料*>*效能*>* NetApp *。



 a| 
傳輸時間間隔
 a| 
`5` （預設）、 `10`或 `15` 分鐘



 a| 
啟用/停用
 a| 
`0` -停用

`1` -啟用（預設）

|===
. 出現提示時、輸入 `y` 以驗證您輸入的資訊是否正確。
. 按任意鍵返回「外部伺服器連線」功能表。
. 類型 `x` 結束維護主控台。




== 結果

設定連線之後、所選效能資料會在您指定的時間間隔傳送到目的地伺服器。測量數據開始出現在Graphite之前、需要幾分鐘的時間。您可能需要重新整理瀏覽器、才能在度量階層中查看新的度量。
