---
permalink: performance-checker/task-identifying-trends-of-i-o-response-time-on-cluster-components.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用Unified Manager來檢視Volume工作負載所有受監控叢集元件的效能趨勢。您可以看到、隨著時間的推移、哪些元件的使用率最高、使用量是否來自讀取或寫入要求、以及使用量如何影響工作負載回應時間。 
---
= 識別叢集元件的I/O回應時間趨勢
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Unified Manager來檢視Volume工作負載所有受監控叢集元件的效能趨勢。您可以看到、隨著時間的推移、哪些元件的使用率最高、使用量是否來自讀取或寫入要求、以及使用量如何影響工作負載回應時間。



== 開始之前

* 您必須OnCommand 具備「操作員」、「資訊管理員」或「儲存管理員」角色。
* 您必須識別要分析的磁碟區或相關LUN名稱。
* 若要顯示30天的效能統計資料、Unified Manager必須從叢集收集並分析至少30天的效能統計資料。




== 關於這項工作

識別叢集元件的效能趨勢有助於系統管理員決定叢集是否過度使用或未充分使用。

如果您正在檢視「事件詳細資料」頁面、可以按一下磁碟區的名稱、直接前往「效能/磁碟區詳細資料」頁面。



== 步驟

. 在*搜尋*列中、輸入磁碟區的名稱。
+
磁碟區名稱會顯示在搜尋結果中。

. 按一下磁碟區名稱。
+
Volume會顯示在「Performance / Volume Details（效能/ Volume詳細資料）」頁面上。

. 在歷史資料圖表上、按一下* 30d*以顯示過去30天的歷史資料。
. 按一下*「解密資料依據*」。
. 在「*延遲*」下、選取「*叢集元件*」和「*讀取/寫入延遲*」。
. 按一下*提交*。
+
這兩個圖表都會顯示在「延遲」圖表下方。

. 請參閱*叢集元件*圖表。
+
此圖表會依照叢集元件來細分回應時間總計。Aggregate的回應時間最高。

. 比較*叢集元件*圖表與*延遲*圖表。
+
「延遲」圖表會顯示總計回應時間的尖峰、這些尖峰會與Aggregate的回應時間尖峰一致。在30天的時間範圍結束時、有幾個時間超過效能臨界值。

. 檢閱*讀取/寫入延遲*圖表。
+
此圖表顯示寫入要求的回應時間比讀取要求的時間長、表示用戶端應用程式等待寫入要求的時間比平常長。

. 將*讀取/寫入延遲*圖表與*延遲*圖表進行比較。
+
與「叢集元件」圖表中的Aggregate相符的整體回應時間尖峰、也會與讀取/寫入延遲圖表中的寫入資料一致。系統管理員必須決定是否必須處理使用工作負載的用戶端應用程式、或是否過度使用Aggregate。


