---
permalink: performance-checker/task-creating-user-defined-performance-threshold-policies.html 
sidebar: sidebar 
keywords:  
summary: 您可以為儲存物件建立效能臨界值原則、以便在效能計數器超過特定值時傳送通知。事件通知指出叢集發生效能問題。 
---
= 建立使用者定義的效能臨界值原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以為儲存物件建立效能臨界值原則、以便在效能計數器超過特定值時傳送通知。事件通知指出叢集發生效能問題。



== 開始之前

您必須OnCommand 扮演「管理員角色」。



== 關於這項工作

您可以在「建立臨界值原則」頁面上輸入臨界值、以建立效能臨界值原則。您可以定義此頁面中的所有原則值來建立新原則、也可以複製現有原則並變更複本中的值（稱為_cloning）。

有效的臨界值為數字0.001到10,000,000、百分比為0.001到100、效能使用率為0.001到200。

[NOTE]
====
目前版本提供臨界值、可在計數器值超過臨界值設定時傳送事件。當計數器值低於臨界值設定時、您無法設定傳送事件的臨界值。

====


== 步驟

. 在左側導覽窗格中、選取*組態*>*效能臨界值*。
+
此時會顯示「組態/效能臨界值」頁面。

. 根據您要建置新原則、或是想要複製類似原則並修改複製版本、按一下適當的按鈕。
+
|===
| 至... | 按一下... 


 a| 
建立新原則
 a| 
*建立*



 a| 
複製現有原則
 a| 
選取現有原則、然後按一下* Clone（複製）*

|===
+
此時會顯示「建立臨界值原則」頁面或「複製臨界值原則」頁面。

. 指定您要為特定儲存物件設定的效能計數器臨界值、以定義臨界值原則：
+
.. 選取儲存物件類型、並指定原則的名稱和說明。
.. 選取要追蹤的效能計數器、並指定定義「警告」和「重大」事件的限制值。
+
您必須定義至少一個「警告」或一個「嚴重」限制。您不需要定義這兩種限制類型。

.. 如有需要、請選取次要效能計數器、並指定「警告」和「重大」事件的限制值。
+
包括次要計數器時、兩個計數器都必須在違反臨界值之前超過限制值、而且必須報告事件。只能使用組合原則來設定特定的物件和計數器。

.. 選取事件傳送必須違反限制值的持續時間。


+
複製現有原則時、您必須輸入原則的新名稱。

. 按一下「*儲存*」以儲存原則。
+
您將返回「組態/效能臨界值」頁面。頁面頂端的成功訊息會確認已建立臨界值原則、並提供該物件類型之「Inventory」頁面的連結、以便您立即將新原則套用至儲存物件。





== 完成後

如果您要在此時將新的臨界值原則套用至儲存物件、可以按一下*移至object_type now*連結、前往「Inventory」頁面。
