---
permalink: health-checker/concept-common-unified-manager-administrative-workflows-and-tasks.html 
sidebar: sidebar 
keywords:  
summary: 與Unified Manager相關的一些常見管理工作流程和工作包括：選取要監控的儲存叢集；診斷對資料可用度、容量和保護造成不良影響的情況；建立保護關係；還原遺失的資料；設定及管理Infinite Volumes；以及將診斷資料搭售及傳送給技術支援（如有必要）。 
---
= 通用的Unified Manager健全狀況工作流程與工作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
與Unified Manager相關的一些常見管理工作流程和工作包括：選取要監控的儲存叢集；診斷對資料可用度、容量和保護造成不良影響的情況；建立保護關係；還原遺失的資料；設定及管理Infinite Volumes；以及將診斷資料搭售及傳送給技術支援（如有必要）。

Unified Manager可讓儲存管理員檢視儀表板、評估受管理儲存叢集的整體容量、可用度及保護健全狀況、然後快速識別、找出、診斷及指派以解決可能發生的任何特定問題。

與叢集、儲存虛擬機器（SVM）、Volume、FlexGroup S27 Volume或保護關係有關的最重要問題、會影響託管儲存物件的儲存容量、資料可用度或保護可靠性、這些問題會顯示在儀表板/概觀頁面的系統健全狀況圖表和事件中。當發現關鍵問題時、本頁會提供連結、以支援適當的疑難排解工作流程。

Unified Manager也可納入包含相關管理工具（例如OnCommand Workflow Automation 、VMware®VMware®VMware®）的工作流程、以支援儲存資源的直接組態。

本文件說明與下列管理工作相關的一般工作流程：

* 診斷及管理可用度問題
+
如果硬體故障或儲存資源組態問題導致「儀表板/總覽」頁面顯示資料可用度事件、儲存管理員可以依照內嵌的連結來檢視受影響儲存資源的連線資訊、檢視疑難排解建議、並將問題解決指派給其他管理員。

* 設定及監控效能事件
+
支援此功能的管理員可監控及管理所監控儲存系統資源的效能OnCommand 。如需詳細資訊、請參閱《管理叢集效能的_Unified Manager工作流程指南》。

* 診斷及管理Volume容量問題
+
如果「儀表板/總覽」頁面中顯示Volume儲存容量問題、儲存管理員可以依照內嵌的連結來檢視與受影響Volume儲存容量相關的目前和歷史趨勢、檢視疑難排解建議、並將問題解決指派給其他管理員。

* 設定、監控及診斷保護關係問題
+
建立及設定保護關係之後、儲存管理員可以在「儀表板/總覽」頁面中檢視與保護關係相關的潛在問題、並可依照內嵌連結檢視保護關係的目前狀態、受影響關係的目前及歷史保護工作成功資訊、以及疑難排解建議、並將問題解決方案指派給其他系統管理員。儲存管理員也可以設定及管理SnapMirror與SnapVault SnapMirror關係。

* 建立備份檔案並從備份檔案還原資料。
* 將儲存物件與附註建立關聯
+
儲存物件與附註建立關聯後、儲存管理員即可篩選及檢視與儲存物件相關的事件、讓儲存管理員能夠排定優先順序、並解決與事件相關的問題。

* 傳送支援服務包給技術支援人員
+
儲存管理員可以使用維護主控台擷取支援套件、並將其傳送給技術支援部門。當問題需要比AutoSupport 消息所提供的更詳細的診斷和疑難排解時、必須將支援服務組合寄送給技術支援部門。

* 建立新報告以供匯入
+
儲存管理員可以建立新的 `.rptdesign` 使用商業智慧與報告工具（BIRT）的Eclipse外掛程式來建立檔案。這些報告可匯入Unified Manager UI、並在「報告」頁面中檢視。

+
「報告」頁面上顯示的報告會提供儲存物件的目前狀態。您可以根據目前的使用量、做出重要決策（例如關於儲存採購的決策）。這些報告提供磁碟區、磁碟櫃和集合體等儲存物件的詳細檢視。

+
Unified Manager UI中的「報告」頁面可讓您檢視所產生報告的詳細資訊。您可以從「報告」頁面搜尋特定報告、儲存報告及刪除報告。您也可以排程、共用及匯入此頁面的報告。

* 建立、設定、監控及保護無限磁碟區
+
在使用Workflow Automation工具建立、設定及定義Infinite Volume的儲存類別之後、儲存管理員可以使用Unified Manager來監控、設定通知臨界值、以及定義該Volume及其儲存類別的資料原則。此外、儲存管理員也可以使用WFA和Unified Manager來設定Infinite Volume的資料保護。


