---
permalink: health-checker/reference-network-configuration-menu.html 
sidebar: sidebar 
keywords:  
summary: 「網路組態」功能表可讓您管理網路設定。當Unified Manager使用者介面無法使用時、您應該使用此功能表。 
---
= 網路組態功能表
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「網路組態」功能表可讓您管理網路設定。當Unified Manager使用者介面無法使用時、您應該使用此功能表。

[NOTE]
====
如果Unified Manager安裝在Red Hat Enterprise Linux、CentOS或Microsoft Windows上、則無法使用此功能表。

====
下列功能表選項可供使用。

* *顯示IP位址設定*
+
顯示虛擬應用裝置目前的網路設定、包括IP位址、網路、廣播位址、網路遮罩、閘道、 和DNS伺服器。

* *變更IP位址設定*
+
可讓您變更虛擬應用裝置的任何網路設定、包括IP位址、網路遮罩、閘道或DNS伺服器。如果您使用維護主控台將網路設定從DHCP切換為靜態網路、則無法編輯主機名稱。您必須選取*提交變更*、變更才會生效。

* *顯示網域名稱搜尋設定*
+
顯示用於解析主機名稱的網域名稱搜尋清單。

* *變更網域名稱搜尋設定*
+
可讓您變更解析主機名稱時要搜尋的網域名稱。您必須選取*提交變更*、變更才會生效。

* *顯示靜態路由*
+
顯示目前的靜態網路路由。

* *變更靜態路由*
+
可讓您新增或刪除靜態網路路由。您必須選取*提交變更*、變更才會生效。

+
** *新增路由*
+
可讓您新增靜態路由。

** *刪除路由*
+
可讓您刪除靜態路由。

** *返回*
+
返回*主功能表*。

** *退出*
+
結束維護主控台。



* *停用網路介面*
+
停用任何可用的網路介面。如果只有一個網路介面可用、您就無法停用它。您必須選取*提交變更*、變更才會生效。

* *啟用網路介面*
+
啟用可用的網路介面。您必須選取*提交變更*、變更才會生效。

* *提交變更*
+
套用對虛擬應用裝置的網路設定所做的任何變更。您必須選取此選項、才能執行任何變更、或是變更不會發生。

* * Ping主機*
+
Ping目標主機以確認IP位址變更或DNS組態。

* *還原為預設設定*
+
將所有設定重設為原廠預設值。您必須選取*提交變更*、變更才會生效。

* *返回*
+
返回*主功能表*。

* *退出*
+
結束維護主控台。


