---
permalink: health-checker/task-generating-and-uploading-a-support-bundle.html 
sidebar: sidebar 
keywords:  
summary: 您可以產生包含完整診斷資訊的支援服務組合、以便擷取並傳送給技術支援部門、以取得疑難排解說明。由於某些類型的資料可能會使用大量的叢集資源、或需要很長時間才能完成、因此您可以指定要納入或排除在支援服務包中的資料類型。 
---
= 產生支援服務組合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以產生包含完整診斷資訊的支援服務組合、以便擷取並傳送給技術支援部門、以取得疑難排解說明。由於某些類型的資料可能會使用大量的叢集資源、或需要很長時間才能完成、因此您可以指定要納入或排除在支援服務包中的資料類型。



== 開始之前

您必須以維護使用者的身分存取維護主控台。



== 關於這項工作

Unified Manager僅儲存兩個最近產生的支援組合。舊版支援服務組合將從系統中刪除。

[NOTE]
====
在Windows系統上、命令 `supportbundle.bat` 不再支援產生支援服務組合。

====


== 步驟

. 在維護主控台*主功能表*中、選取*支援/診斷*。
. 選擇*產生支援產品組合*。
. 選取或取消選取下列資料類型、以納入或排除支援服務組合：
+
** *資料庫傾印*
+
MySQL Server資料庫的傾印。

** *堆傾印*
+
Unified Manager主要伺服器程序狀態的快照。此選項預設為停用、只有在客戶支援要求時才應選取。

** *擷取錄影*
+
記錄Unified Manager與受監控叢集之間的所有通訊。



+
[NOTE]
====
如果您取消選取所有資料類型、仍會使用其他Unified Manager資料產生支援服務組合。

====
. 類型 `g`，然後按Enter鍵以產生支援服務包。
+
由於產生支援服務包是一項記憶體密集作業、因此系統會提示您確認是否確定要在此時產生支援服務組合。

. 類型 `y`，然後按Enter鍵以產生支援服務包。
+
如果您目前不想產生支援服務組合、請輸入 `n`，然後按Enter鍵。

. 如果您在支援套裝組合中加入資料庫傾印檔案、系統會提示您指定要納入效能統計資料的時段。包括效能統計資料可能需要大量時間和空間、因此您也可以在不包含效能統計資料的情況下傾印資料庫：
+
.. 以「月份-月份-月份-月份-月份-日期」格式輸入開始日期。
+
例如、輸入 `20170101` 2017年1月1日。輸入 `n` 如果您不想納入效能統計資料、

.. 輸入統計資料的天數、從上午12點開始算起在指定的開始日期。
+
您可以輸入1到10之間的數字。



+
如果您要納入效能統計資料、系統會顯示收集效能統計資料的期間。

. 選擇*產生支援產品組合*。
+
產生的支援服務組合位於 `/support` 目錄。





== 完成後

產生支援套件後、您可以使用SFTP用戶端或UNIX或Linux CLI命令來擷取。在Windows安裝上、您可以使用遠端桌面（RDP）來擷取支援服務組合。

產生的支援服務組合位於 `/support` VMware系統上的目錄、請至 `/opt/netapp/data/support/` 在Linux系統和中 `ProgramData\NetApp\OnCommandAppData\ocum\support` 在Windows系統上。
