---
permalink: health-checker/task-restoring-data-using-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用「健全狀況/磁碟區詳細資料」頁面上的還原功能、從Snapshot複本還原覆寫或刪除的檔案、目錄或整個磁碟區。 
---
= 使用健全狀況/ Volume詳細資料頁面還原資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「健全狀況/磁碟區詳細資料」頁面上的還原功能、從Snapshot複本還原覆寫或刪除的檔案、目錄或整個磁碟區。



== 開始之前

您必須OnCommand 具備「管理員」或「儲存管理員」角色。



== 關於這項工作

您無法還原NTFS檔案串流。

還原選項在下列情況下無法使用：

* Volume ID未知：例如、當您有叢集間關係、但尚未探索目的地叢集時。
* Volume FlexGroup 是一個不一樣的體積。
* 該磁碟區已設定為SnapMirror同步複寫。




== 步驟

. 在「*健全狀況/磁碟區*」詳細資料頁面的「*保護*」索引標籤中、在拓撲檢視中按一下滑鼠右鍵、即可看到您要還原的磁碟區名稱。
. 從功能表中選取*還原*。
+
或者、從* Actions（動作）*功能表中選取* Restore（還原）*、以保護您正在檢視其詳細資料的目前磁碟區。

+
此時會顯示「還原」對話方塊。

. 選取您要從中還原資料的磁碟區和Snapshot複本（如果與預設不同）。
. 選取您要還原的項目。
+
您可以還原整個磁碟區、也可以指定要還原的資料夾和檔案。

. 選取您要還原所選項目的位置：*原始位置*或*替代現有位置*。
. 如果您選取替代的現有位置、請執行下列其中一項：
+
** 在還原路徑文字欄位中、輸入您要還原資料的位置路徑、然後按一下*選取目錄*。
** 按一下*瀏覽*以啟動瀏覽目錄對話方塊、並完成下列步驟：
+
... 選取您要還原的叢集、SVM和Volume。
... 在「名稱」表格中、選取目錄名稱。
... 單擊*選擇目錄*。




. 按一下 * 還原 * 。
+
還原程序隨即開始。

+
[NOTE]
====
如果Cloud Volumes ONTAP 在發生NDMP錯誤的情況下、還原作業在還原HA叢集之間失敗、您可能需要在目的地叢集中新增明確的AWS路由、以便目的地能夠與來源系統的叢集管理LIF通訊。您可以使用OnCommand NetApp Cloud Manager執行此組態步驟。

====

