---
permalink: health-checker/task-performing-suggested-remedial-actions-for-a-full-volume.html 
sidebar: sidebar 
keywords:  
summary: 在收到「Volume Space Full」錯誤事件之後、您將在「Event details」（事件詳細資料）頁面上檢閱建議的補救行動、並決定執行其中一項建議的行動。 
---
= 針對完整Volume執行建議的補救行動
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在收到「Volume Space Full」錯誤事件之後、您將在「Event details」（事件詳細資料）頁面上檢閱建議的補救行動、並決定執行其中一項建議的行動。



== 開始之前

您必須OnCommand 具備「管理員」或「儲存管理員」角色。

具有任何角色的使用者可以執行此工作流程中使用Unified Manager的所有工作。



== 關於這項工作

在此範例中、您已在Unified Manager儀表板/概觀頁面上看到Volume Space Full錯誤事件、並按一下事件名稱。

您可能針對整個Volume執行的補救行動包括：

* 在磁碟區上啟用自動擴充、重複資料刪除或壓縮功能
* 調整磁碟區大小或移動磁碟區
* 刪除或移動磁碟區中的資料


雖然所有這些行動都必須從OnCommand 《不景系統管理程式》或ONTAP 《不景點CLI》執行、但您可以使用Unified Manager來尋找可能需要的資訊、以判斷要採取哪些行動。



== 步驟

. 在「*事件*詳細資料」頁面中、按一下「來源」欄位中的磁碟區名稱、即可檢視受影響磁碟區的詳細資料。
. 在「*健全狀況/磁碟區*」詳細資料頁面上、按一下「*組態*」、即可看到磁碟區上已啟用重複資料刪除與壓縮功能。
+
您決定調整Volume的大小。

. 在「*相關裝置*」窗格中、按一下託管Aggregate的名稱、即可查看Aggregate是否能容納較大的磁碟區。
. 在「*健全狀況/ Aggregate *」詳細資料頁面上、您會發現裝載完整Volume的集合體具有足夠的未認可容量、因此您可以使用OnCommand 「系統管理程式」來調整Volume大小、使其擁有更多容量。

