---
permalink: config/task-adding-clusters.html 
sidebar: sidebar 
keywords:  
summary: 您可以將叢集新增OnCommand 至「支援整合管理程式」、以便監控叢集。這包括取得叢集資訊（例如叢集的健全狀況、容量、效能和組態）的能力、以便找出並解決可能發生的任何問題。 
---
= 新增叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將叢集新增OnCommand 至「支援整合管理程式」、以便監控叢集。這包括取得叢集資訊（例如叢集的健全狀況、容量、效能和組態）的能力、以便找出並解決可能發生的任何問題。



== 開始之前

* 您必須OnCommand 具備「管理員」或「儲存管理員」角色。
* 您必須具備下列資訊：
+
** 主機名稱或叢集管理IP位址
+
主機名稱是Unified Manager用來連線至叢集的FQDN或簡稱。主機名稱必須解析為叢集管理IP位址。

+
叢集管理IP位址必須是管理儲存虛擬機器（SVM）的叢集管理LIF。如果使用節點管理LIF、則作業會失敗。

** 系統管理員使用者名稱和密碼Data ONTAP
+
此帳戶必須將「應用程式」存取權限設為_ontapi_、_ssh _和_http _的_admin_角色。

** 可在叢集上設定的傳輸協定類型（HTTP或HTTPS）、以及用於連線至叢集的連接埠號碼


+
[NOTE]
====
您可以使用Unified Manager NAT IP位址、新增位於NAT/防火牆後方的叢集。任何連線的Workflow Automation或SnapProtect 非功能性系統也必須位於NAT/防火牆之後、SnapProtect 而非功能性API呼叫則必須使用NAT IP位址來識別叢集。

====
* Unified Manager FQDN必須能夠ping通ONTAP 整個系統。
+
您可以使用下列ONTAP 指令執行驗證： `ping -node node_name -destination Unified_Manager_FQDN`。

* 您必須在Unified Manager伺服器上有足夠的空間。當資料庫目錄中超過90%的空間已耗用時、您將無法將叢集新增至伺服器。




== 關於這項工作

若要進行支援、您必須同時新增本機和遠端叢集、而且叢集必須正確設定。MetroCluster

只要您已在叢集上設定第二個叢集管理LIF、讓Unified Manager的每個執行個體都透過不同的LIF連線、您就可以使用兩個Unified Manager執行個體來監控單一叢集。



== 步驟

. 在左導覽窗格中、按一下*組態*>*叢集資料來源*。
. 在「*組態/叢集資料來源*」頁面上、按一下「*新增*」。
. 在「*新增叢集*」對話方塊中、指定所需的值、例如叢集的主機名稱或IP位址、使用者名稱、密碼、通訊協定及連接埠號碼。
+
根據預設、會選取HTTPS傳輸協定和連接埠443。

+
您可以將叢集管理IP位址從IPv6變更為IPv4、或從IPv6變更為IPv6。下一個監控週期完成後、新的IP位址會反映在叢集網格和叢集組態頁面中。

. 按一下*提交*。
. 如果選取HTTPS、請執行下列步驟：
+
.. 在「*授權主機*」對話方塊中、按一下「*檢視憑證*」以檢視叢集的憑證資訊。
.. 按一下「*是*」。
+
Unified Manager只會在一開始新增叢集時檢查憑證。Unified Manager不會檢查每個API呼叫ONTAP 的認證資料以供參考。

+
如果憑證已過期、您就無法新增叢集。您必須先更新SSL憑證、然後再新增叢集。







== 結果

在探索新叢集的所有物件（約15分鐘）之後、Unified Manager會開始收集前15天的歷史效能資料。這些統計資料是使用資料持續性收集功能來收集。此功能可在新增叢集之後、立即為叢集提供超過兩週的效能資訊。在資料持續性收集週期完成之後、系統會依預設每五分鐘收集一次即時叢集效能資料。

[NOTE]
====
由於收集15天的效能資料會佔用大量CPU資源、因此建議您將新增的叢集重新分段、以使資料持續性收集輪詢不會同時在太多叢集上執行。此外、如果您在資料持續性收集期間重新啟動Unified Manager、收集作業將會暫停、而且效能圖表中會出現遺漏時間範圍的落差。

====
[TIP]
====
如果您收到無法新增叢集的錯誤訊息、請檢查下列問題是否存在：

* 如果兩個系統上的時鐘未同步、且Unified Manager HTTPS憑證開始日期晚於叢集上的日期。您必須確保時鐘是使用NTP或類似服務來同步。
* 如果叢集已達到EMS通知目的地的最大數量、則無法新增Unified Manager位址。根據預設、叢集上只能定義20個EMS通知目的地。


====