---
permalink: install/task-installing-unified-manager-linux.html 
sidebar: sidebar 
keywords:  
summary: 您可以在實體或虛擬Red Hat Enterprise Linux或CentOS平台上安裝Unified Manager。 
---
= 在Red Hat Enterprise Linux或CentOS上安裝Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在實體或虛擬Red Hat Enterprise Linux或CentOS平台上安裝Unified Manager。



== 開始之前

* 您要安裝Unified Manager的系統必須符合系統和軟體需求。
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[硬體系統需求]

+
xref:reference-red-hat-and-centos-software-and-installation-requirements.adoc[Red Hat與CentOS軟體與安裝需求]

* 您必須已下載Unified Manager``.zip`` 檔案從NetApp 支援網站 功能區移至目標系統。
* 您必須擁有支援的網頁瀏覽器。
* 您的終端機模擬軟體必須已啟用sc復原 功能。




== 關於這項工作

Red Hat Enterprise Linux或CentOS系統可能已安裝所需支援軟體（Java、MySQL、其他公用程式）的所有必要版本、或可能只安裝部分必要軟體、或是新安裝的系統、但未安裝任何必要軟體。



== 步驟

. 登入您要安裝Unified Manager的伺服器。
. 輸入適當的命令、以評估目標系統上可能需要安裝或升級哪些軟體、以支援安裝：
+
|===
| 必要軟體與最低版本 | 用於驗證軟體和版本的命令 


 a| 
OpenJDK11版
 a| 
`java -version`



 a| 
MySQL 5.7.23社群版本
 a| 
`rpm -qa | grep -i mysql`



 a| 
p7zip 9.20.1
 a| 
`rpm -qa | grep p7zip`

|===
. 如果所列軟體的任何版本早於所需版本、請輸入適當的命令來解除安裝該模組：
+
|===
| 要解除安裝的軟體 | 解除安裝軟體的命令 


 a| 
MySQL

[NOTE]
====
解除安裝任何不是MySQL 5.7.23 Community Edition或更新版本的版本。

==== a| 
`rpm -e` <``mysql_package_name``>

[NOTE]
====
如果收到相依性錯誤、您必須新增 `--nodeps` 解除安裝元件的選項。

====


 a| 
所有其他模組
 a| 
`yum remove` `module_name`

|===
. 瀏覽至您下載安裝的目錄 `.zip` 歸檔並展開Unified Manager產品組合： `unzip OnCommandUnifiedManager-rhel7-9.5.zip`
+
必要的 `.rpm` Unified Manager的模組會解壓縮至目標目錄。

. 驗證目錄中是否有下列模組可用： `ls *.rpm`
+
** `ocie-au-<version>.x86_64.rpm`
** `ocie-server-<version>.x86_64.rpm`
** `ocie-serverbase-<version>.x86_64.rpm`
** `netapp-application-server-<version>.x86_64.rpm`
** `netapp-platform-base-<version>.x86_64.rpm`
** `netapp-ocum-<version>.x86_64.rpm`


. 執行安裝前指令碼、確保沒有系統組態設定或任何安裝的軟體會與安裝Unified Manager衝突： `pre_install_check.sh`
+
安裝前指令碼會檢查系統是否有有效的Red Hat訂閱、以及是否有權存取所需的軟體儲存庫。如果指令碼發現任何問題、您必須在安裝Unified Manager之前修正問題。

+
[NOTE]
====
如果需要手動下載安裝所需的套件、則必須執行步驟7 _only。如果您的系統可以存取網際網路、而且所有必要的套件都可供使用、請前往步驟8。

====
. 對於未連線至網際網路或未使用Red Hat Enterprise Linux儲存庫的系統、請執行下列步驟以判斷是否缺少任何必要的套件、然後下載這些套件：
+
.. 在您要安裝Unified Manager的系統上、檢視可用和無法使用的套件清單： `yum install *.rpm --assumeno`
+
「正在安裝：」區段中的項目是目前目錄中可用的套件、而「正在安裝相依套件：」區段中的項目是您系統上遺失的套件。

.. 在可存取網際網路的系統上、下載遺失的套件： `yum install <package_name\> --downloadonly --downloaddir=.`
+
[NOTE]
====
由於Red Hat Enterprise Linux系統並未一律啟用外掛程式「yum外掛程式-downloadonly」、因此您可能需要啟用下載套件的功能、而不需安裝： `yum install yum-plugin-downloadonly`

====
.. 將遺失的套件從網際網路連線的系統複製到安裝系統。


. 安裝軟體： `yum install *.rpm`
+
此命令會安裝 `.rpm` 套件、所有其他必要的支援軟體、以及Unified Manager軟體。

+
[NOTE]
====
請勿使用替代命令（例如 `+rpm -ivh ...+`）。在Red Hat Enterprise Linux或CentOS系統上成功安裝Unified Manager時、必須將所有Unified Manager檔案及相關檔案以特定順序安裝至由自動強制執行的特定目錄結構 `yum install *.rpm` 命令。

====
. 請忽略安裝訊息後立即顯示的電子郵件通知。
+
電子郵件會通知root使用者初始cron工作失敗、對安裝沒有不良影響。

. 安裝訊息完成後、捲動回訊息、直到看到系統顯示Unified Manager Web UI的IP位址或URL、維護使用者名稱（umadmin）和預設密碼的訊息。
+
此訊息類似於下列內容：

+
[listing]
----
OnCommand Unified Manager installed successfully.
Use a web browser and one of the following URL(s) to configure and access the Unified Manager GUI.
https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/

Log in to Unified Manager in a web browser by using following details:
  username: umadmin
  password: admin
----
. 記錄IP位址或URL、指派的使用者名稱（umadmin）和目前密碼。
. 如果您在安裝Unified Manager之前使用自訂主目錄建立umadmin使用者帳戶、則必須指定umadmin使用者登入Shell：``usermod -s /bin/maintenance-user-shell.sh umadmin``




== 完成後

您可以存取Web UI來執行Unified Manager的初始設定、如《_ OnCommand 》《Unified Manager系統組態指南》中所述。
